### ISSUE TITLE
[Modular CLI]: modular install mojo stalls during Codespaces install

### ISSUE THREAD

**Issue by bgyss** [modularml/mojo#577] opened 2023-09-07 18:34 UTC
### Issue description

Currently unable to get through the mojo installation in a GitHub Codespaces environment. Expected the installation to finish but it has stalled multiple times during the testing phase of the install.

### Steps to reproduce

The following is the command that I entered with all the output I'm currently seeing:

```
@bgyss ➜ /workspaces/mojo (main) $ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/codespace/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0 (from -r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1))
  Downloading find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting papermill==2.4.0 (from -r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading papermill-2.4.0-py3-none-any.whl (38 kB)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/codespace/.local/lib/python3.10/site-packages (from -r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.0)
Collecting ansiwrap (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting click (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for click from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: pyyaml in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: nbformat>=5.1.2 in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: nbclient>=0.2.0 in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Collecting tqdm>=4.32.2 (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for tqdm>=4.32.2 from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.31.0)
Collecting entrypoints (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Requirement already satisfied: tenacity in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: tornado>=6.2 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: traitlets>=5.3 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.9.0)
Requirement already satisfied: platformdirs>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: fastjsonschema in /home/codespace/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /home/codespace/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Collecting textwrap3>=0.9.2 (from ansiwrap->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.22)
Requirement already satisfied: attrs>=22.2.0 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 3.5 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 6.0 MB/s eta 0:00:00
Installing collected packages: textwrap3, find_libpython, tqdm, entrypoints, click, ansiwrap, papermill
Successfully installed ansiwrap-0.8.4 click-8.1.7 entrypoints-0.4 find_libpython-0.3.0 papermill-2.4.0 textwrap3-0.9.2 tqdm-4.66.1
Testing `MODULAR_HOME=/home/codespace/.modular`
* `/home/codespace/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
```
The installation just hangs at this point.

### Version Info

```shell
Modular CLI version: modular 0.1.4 (6b54d308)
OS info from Codespaces VM: distro=ubuntu  version=20.04  codename=focal  arch=x86_64
```

**Comment by bzcheeseman** [comment] 2023-09-07 18:49
Dupe of https://github.com/modularml/mojo/issues/538 - please follow discussion there :)

**Closed** 2023-09-07 18:52 UTC
Labels: modular-cli
