### ISSUE TITLE
[Docs] Weird search behaviour

### ISSUE THREAD

**Issue by Yelinz** [modularml/mojo#962] opened 2023-09-30 13:13 UTC
### Where is the problem?

https://docs.modular.com/mojo/stdlib/math/math.html?q=exp(

### What can we do better?

![Screenshot from 2023-09-30 15-09-09](https://github.com/modularml/mojo/assets/30687616/954a1715-4ded-4321-8f7a-a523cc1f8642)

After searching for something with `(` subsequently the search button vanishes.

1. Search for example `exp(`
2. Select the found result
3. Search disappears
4. Navigate to other page to fix it

### Anything else?

Havent tested it with other special characters

**Comment by scottamain** [comment] 2023-10-06 21:29
Thanks for reporting this. We're working on a new version of the docs website where I cannot reproduce this, so this should be resolved in the near future.

**Closed by scottamain** 2023-10-06 21:29 UTC
Labels: documentation
