### ISSUE TITLE
[BUG]: Crash if a template type is returned instead of a value

### ISSUE THREAD

**Issue by isuckatcs** [modularml/mojo#1607] opened 2024-01-08 16:10 UTC
### Bug description

The following **invalid** snippet crashes.
```
@value
struct Foo[t: Int]:
    fn __call__(self):
        pass


fn foo[t: Int]() -> Foo[t]:
    return Foo[t]


fn main():
    pass
```
```
mojo: /__w/modular/modular/KGEN/lib/MojoParser/ExprEmitter.cpp:1399: M::KGEN::LIT::BValue M::KGEN::LIT::ExprEmitter::emitStoreToLValue(ASTExprAnd<M::KGEN::LIT::CValue>, M::KGEN::LIT::LValue, M::KGEN::LIT::ExprContext): Assertion `value.ir.getRValueType().isEqualCanon(destLV.getRValueType()) && "Types should match"' failed.
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo repro.mojo
1.      Crash resolving decl body at loc(".../repro.mojo":7:1)
    >> fn foo[t: Int]() -> Foo[t]:
       ^..........................
    >>     return Foo[t]
       .................<
2.      Crash parsing statement at loc(".../repro.mojo":8:5)
    >>     return Foo[t]
           ^............<
```

### Steps to reproduce

- Run the above snippet with the Mojo interpreter

### System information

```shell
- Ubuntu 22.04.3 LTS (WSL 2)
- mojo 0.6.1 (876ded2e)
- modular 0.3.1 (589ce200)
```

**Comment by nmsmith** [comment] 2024-01-22 08:10
Here's a smaller code snippet that reproduces the crash:
```
fn foo() -> String: return String
```

Strangely, if you change the type to `Int`, the crash doesn't occur.

Also, this issue is possibly a duplicate of https://github.com/modularml/mojo/issues/1538.

**Comment by arthurevans** [comment] 2024-01-22 17:44
I think this issue is fixed in main. Although the error it returns could be more helpful: 
"cannot implicitly convert 'Foo[t]' value to 'Foo[t]' in return value"

**Comment by laszlokindrat** [comment] 2024-02-08 14:50
Thanks for opening the ticket! The error no longer reproduces on top of main, but I agree with @arthurevans that the error message is not the best. I made some improvements, so in the next release you would get something like this:
```mojo
fn foo() -> String:
  return String  # error: cannot implicitly convert 'String' type value to an instance of 'String' in return value (hint: did you mean to instantiate 'String'?)
```

**Closed** 2024-02-08 19:32 UTC
Labels: bug, mojo-lang, mojo, crash
