### ISSUE TITLE
[BUG] Pointer is not working properly

### ISSUE THREAD

**Issue by a62690705** [modularml/mojo#2235] opened 2024-04-07 11:27 UTC
### Bug description

```mojo
def main():
    var v = 8
    var ptr = Pointer[Int](v)

    print(ptr)


Output

0x8
``` 

The location of the variable v was supposed to be printed in memory as 0x8ffed2bfe0b0, but it did not happen.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?     https://docs.modular.com/mojo/playground
- Provide version information for Mojo by pasting the output of `mojo -v`   24.2
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by past-moon** [comment] 2024-04-09 20:08
Looks like this is because you are actually calling `Pointer.__init__(address: Self) -> Self` where the 8 is being cast to the `address` type, so you essentially are making a pointer with the value 8 instead of a pointer to the stack variable that contains the 8.

Try instead
```mojo
def main():
    var v = 8
    var ptr = Reference(v).get_unsafe_pointer()

    print(ptr)
```
```
$ mojo /tmp/test.mojo
0x7ffc5be5cfd8
```

Now you get the stack address of the variable

**Comment by arthurevans** [comment] 2024-04-09 23:33
@past-moon is correct. You can also do this without using `Reference` like this:

```mojo
var ptr = Pointer.address_of(v)
```

Using `Reference.get_unsafe_pointer()` requires another import, but it also works in the case where the value you want a pointer to is a borrowed (hence immutable) reference. Of course, getting a pointer to the value lets you mutate it, which is one reason why it's unsafe.

Closing this issue, however, since Pointer is working as intended.

**Closed by arthurevans** 2024-04-09 23:33 UTC
Labels: bug, mojo
