### ISSUE TITLE
[BUG] Compiler bug in while loop

### ISSUE THREAD

**Issue by mzaks** [modularml/mojo#2821] opened 2024-05-25 11:36 UTC
### Bug description

Compiler crash:

```
#0 0x00000001040f799c llvm_strlcpy (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x1000bf99c)
 #1 0x00000001040f5c88 llvm_strlcpy (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x1000bdc88)
 #2 0x00000001040f803c llvm_strlcpy (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x1000c003c)
 #3 0x0000000189e67584 (/usr/lib/system/libsystem_platform.dylib+0x180477584)
 #4 0x00000001053501a8 mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x1013181a8)
 #5 0x0000000105672480 mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x10163a480)
 #6 0x0000000105672eb8 mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x10163aeb8)
 #7 0x0000000105679108 mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x101641108)
 #8 0x0000000105678e84 mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x101640e84)
 #9 0x0000000189d60548 (/usr/lib/libc++.1.dylib+0x180370548)
#10 0x000000010575fb4c mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x101727b4c)
#11 0x00000001057659fc mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x10172d9fc)
#12 0x0000000105765004 mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x10172d004)
#13 0x00000001057650a0 mbedtls_version_get_number (/Users/mzaks/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo+0x10172d0a0)
#14 0x0000000189e36f94 (/usr/lib/system/libsystem_pthread.dylib+0x180446f94)
#15 0x0000000189e31d34 (/usr/lib/system/libsystem_pthread.dylib+0x180441d34)
mojo crashed!
```

### Steps to reproduce

Following code results in compiler crash:

```Mojo
fn main():
    var loop = True
    var i = 0
    while loop:
        if i > 10:
            loop = False
        else:
            i += 1
```

### System information

```shell
- macOS 14.4.1 (23E224)
- mojo 2024.5.2505 (08130894)
- modular 0.7.1 (28ddab26)
```

**Comment by rd4com** [comment] 2024-05-25 14:36
Hello, here is a minimal example:
```mojo
fn main():
    var loop = True
    while loop:
        loop=False
```

#### Works fine with:
```mojo
fn main():
    var loop = True
    if loop:
        loop=False
```
`mojo 2024.5.2505`

**Comment by jdiggins** [comment] 2024-05-26 04:29
This is a duplicate of https://github.com/modularml/mojo/issues/2696

**Comment by ematejska** [comment] 2024-05-28 21:48
Closing as duplicate.

**Closed** 2024-05-28 21:48 UTC
Labels: bug, mojo-repo
