### ISSUE TITLE
[Feature Request] Add `__name__`

### ISSUE THREAD

**Issue by YichengDWu** [modularml/mojo#3324] opened 2024-07-28 06:23 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Second #894. 

The attribute `__name__` is implicitly set when defining a class in Python. Mojo should following the behaviour. 

### What is your motivation for this change?

See #894. Sometimes people want to get the type of an object as a string.

### Any other details?

Or it can be added to the `@value` decorator.

**Comment by ematejska** [comment] 2024-08-06 17:58
Duplicate of [https://github.com/modularml/mojo/issues/187](https://github.com/modularml/mojo/issues/187)

**Closed** 2024-08-06 18:00 UTC
Labels: enhancement, mojo-repo
