### ISSUE TITLE
[Modular CLI] Failure in installing Mojo nightly build

### ISSUE THREAD

**Issue by sampathchanda** [modularml/mojo#2366] opened 2024-04-21 17:58 UTC
### Issue description

While running the mojo nightly build installation command with modular CLI, am seeing the following error:
Am running on Mac OS Sonoma 14.3. 
```
username@hostname % modular install nightly/mojo
# Found release for https://packages.modular.com/nightly/mojo @ 2024.4.1618
# Downloading archive: packages/2024.4.1618/mojo-arm64-apple-darwin22.6.0-2024.4.1618-17-0.tar.zst
Downloaded   [ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%   87.0MiB/87.0MiB             
# Extracting downloaded archives. 
Extracted    [ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%   87.0MiB/87.0MiB             
# Extraction complete, setting configs...
# Configs complete, running post-install hooks...
[mojo][error] Mojo SDK post-install test "`mojo repl`" failed:
CheckError: expected '42' to appear in output:

  File "/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/scripts/post-install/self-test.py", line 306, in test_mojo_repl
    self.assert_contains("42", out)
  File "/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/scripts/post-install/self-test.py", line 156, in assert_contains
    raise CheckError(needle, haystack)
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
modular: error: failed to run script
==========================
Failure Information:
	- Script: `PATH=/opt/homebrew/opt/python@3.11/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin HOME=/Users/sampath PYTHONPATH=/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/venv/lib/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/venv/bin/python /Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/scripts/post-install/self-test.py --modular-home /Users/sampath/.modular --package-path /Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo --mojo-config-section mojo-nightly`
	- Result: 1
	- Stderr:
[mojo][error] Mojo SDK post-install test "`mojo repl`" failed:
CheckError: expected '42' to appear in output:

  File "/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/scripts/post-install/self-test.py", line 306, in test_mojo_repl
    self.assert_contains("42", out)
  File "/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/scripts/post-install/self-test.py", line 156, in assert_contains
    raise CheckError(needle, haystack)
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.


==========================
```

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by sampathchanda** [comment] 2024-04-21 18:04
Interestingly, just re-running the same command ran the installation successfully.
```
# Found release for https://packages.modular.com/nightly/mojo @ 2024.4.1618
# Using cached archive: /Users/sampath/.modular/mojo-arm64-apple-darwin22.6.0-2024.4.1618-17-0.tar.zst
# Extracting downloaded archives. 
Extracted    [ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%   87.0MiB/87.0MiB             
# Extraction complete, setting configs...
# Configs complete, running post-install hooks...

🔥 Mojo installed! 🔥

Mojo's Python virtual environment created at /Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/venv

If you are using ZSH (default on macOS), run the following commands:

echo 'export MODULAR_HOME="/Users/sampath/.modular"' >> ~/.zshrc
echo 'export PATH="/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc

If you are using bash, run the following commands:

BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
echo 'export MODULAR_HOME="/Users/sampath/.modular"' >> "$BASHRC"
echo 'export PATH="/Users/sampath/.modular/pkg/packages.modular.com_nightly_mojo/bin:$PATH"' >> "$BASHRC"
source "$BASHRC"

Then enter 'mojo' to start the Mojo REPL.

For tool help, enter 'mojo --help'.
For more docs, see https://docs.modular.com/mojo.
```
I will keep the issue open for some contributor to take a look and fix the issue of seeing the error in first place.

**Comment by ematejska** [comment] 2024-04-22 19:07
Thank you for filing.  Since it's not reproducing right now, closing but if you see this again reliably please reopen.

**Closed by ematejska** 2024-04-22 19:07 UTC
Labels: modular-cli
