### ISSUE TITLE
[BUG]: cannot load non-register passable type into SSA register?

### ISSUE THREAD

**Issue by sh-shota** [modularml/mojo#1141] opened 2023-10-23 01:03 UTC
### Bug description

I'm sorry for I'm not good at english.

I am learning mojo and writing our netork simulator on mojo. When writing simulator, I want to get pointer of user defined struct and reference this struct from anothter user defined struct. 

When run following code, I get following messages. Messages says "compiler bug, plerse report!". So, I report issue.
```
sh-shota@nono:~/w/f/flnet-mojo> mojo flnet.mojo
/home/sh-shota/work/flnet/flnet-mojo/flnet.mojo:113:38: error: cannot load non-register passable type into SSA register (compiler bug, please report!)
    var pt = __get_address_as_lvalue(sc)
                                     ^
mojo: error: failed to parse the provided Mojo
```

Here is code. Maybe, It is similar to https://github.com/modularml/mojo/issues/912.  Sorry if it's the same bug as in #912 .
```
from math import log10, ceil
from memory.unsafe import Pointer

from python import Python
from python.object import PythonObject


@value
struct Time:
    # 時間関係の値の中で、format させたいものには Time struct を与えている
    var time: Float32
    
    # add later
    fn _format(inout self):
        pass


struct Scheduler:
    var now: Time
    var delta: Float32
    var max_time: Float32
    var nodes: PythonObject # collections の list を使用する
    var count: Int
    var decount: Int
    var ceil_num: Int

    def __init__(inout self, start:Float32=0, delta:Float32=0.1, max_time:Float32=100):
        let co = Python.import_module("collections")
        self.now = Time(start)
        self.delta = delta
        self.max_time = max_time
        self.nodes = co.deque()
        self.count = 0
        self.decount = 0        
        self.ceil_num = (-1 * log10(self.delta)).to_int()
        if self.ceil_num < 0:
            self.ceil_num = 0

    fn __copyinit__(inout self, other:Self):
        self.now = other.now
        self.delta = other.delta
        self.max_time = other.max_time
        self.nodes = other.nodes
        self.count = other.count
        self.decount = other.decount
        self.ceil_num = other.ceil_num

    fn advance(inout self):
        self.now.time += self.delta
        self.count += 1

    fn is_running(inout self) -> Bool:
        return self.now.time <= self.max_time


struct Message:
    var src: Int
    var dst: Int
    var w: Float32
    var p: Float32
    var rate: Float32
    var valid_since: Time
    var tstmp: Time
    var ack: Bool
    
    fn __init__(inout self):
        self.src = 0
        self.dst = 0
        self.rate = 0
        self.w = 0
        self.p = 0
        self.valid_since = Time(0)
        self.tstmp = Time(0)
        self.ack = False
        

var node_ids:Int = 0
struct Node:
    var id_: Int
    var scheduler: Scheduler
    var neigbhors: PythonObject
    var queues: PythonObject
    var is_dst: Bool
    
    def __init__(inout self, sch: Scheduler):
        node_ids += 1
        let collections = Python.import_module("collections")
        self.id_ = node_ids
        self.scheduler = sch
        self.neigbhors = collections.deque()
        self.queues = collections.defaultdict()
        self.is_dst = False        
        
def main():
    # flnet 内で使用する python module の定義
    let collections = Python.import_module("collections")
    let math = Python.import_module("math")

    var msg = Message()
    var sc = Scheduler()    

    var node = Node(sch=sc)

    sc.advance()
    print(node.scheduler.now.time)
    print(sc.now.time)

    node.scheduler.advance()
    print(node.scheduler.now.time)
    print(sc.now.time)
    print()

    var pt = __get_address_as_lvalue(sc) # here

```

### Steps to reproduce

- run code (mojo flnet.mojo)

### System information

```shell
- Debian 11 on WSL2
- mojo cli (mojo 0.4.0 (9e33b013))
- CPU Core i& 11700
- GPU NVIDIA GeForce RTX 3060 Ti
- Linux nono 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux
```

**Comment by lattner** [comment] 2023-10-28 23:15
Thank you for filing this, this is a duplicate of https://github.com/modularml/mojo/issues/912

**Closed by lattner** 2023-10-28 23:15 UTC
Labels: bug, mojo-lang, mojo
