### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nyirobalazs** [modularml/mojo#653] opened 2023-09-08 21:21 UTC
### Issue description

When I try to install Mojo to Ubuntu subsystem the described way on your website, I get the following error message: MODULAR_AUTH=mut_3a595c500f434c5ab4076d771414d7b7: command not found

What can be the problem and the solution?

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
- Include anything that might help us debug the issue.

**Comment by rajsecrets01** [comment] 2023-09-09 13:02
1. Put this code `curl https://get.modular.com | \
  MODULAR_AUTH=mut_0bc3544780644311aaedf1ca86b3a6ae \
  sh -`
2. try to do manual installation :  
![image](https://github.com/modularml/mojo/assets/131753845/c54e02e9-f2c1-4ea7-a5ee-8233ee0bbe7d)
link : https://developer.modular.com/download

**Comment by its-ogawa** [comment] 2023-09-12 04:24
If the command has line breaks in it, as shown on the home page, why don't you run it without them?

**Comment by robert-j-webb** [comment] 2023-09-14 18:21
Can you try running it like this

```
 MODULAR_AUTH=mut_828757d939ac470aaa2e9ade8e635745  curl https://get.modular.com | sh -
```

**Comment by goldiegadde** [comment] 2024-05-02 06:05
Closing this as working  as intended, see message above

**Closed** 2024-05-03 22:05 UTC
Labels: mojo-repo
