### ISSUE TITLE
[BUG]: return type mismatch when using `StaticTuple`

### ISSUE THREAD

**Issue by vguerra** [modularml/mojo#1274] opened 2023-11-11 15:10 UTC
### Bug description

When declaring a function with `StaticTuple[X, ElmType]` as return type, compiler allows me to return a object of `ElmType` type without error.

### Steps to reproduce

Code in question:

```mojo
from utils.index import StaticTuple
from tensor import Tensor

alias Scalar = DType.float64

fn fetch_data() raises -> StaticTuple[4, Tensor[Scalar]]:
    return Tensor[Scalar]()

let data = fetch_data()

print(data.__len__())
```
Output: 4

I would expect the compiler to not allow me to write this code.

### System information

```shell
- What OS did you do install Mojo on ?

Darwin 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64

- Provide version information for Mojo by pasting the output of `mojo -v`

mojo 0.5.0 (6e50a738)

- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.2.2 (95d42445)
```

**Comment by willghatch** [comment] 2023-11-15 17:49
Mojo will implicitly convert types when there is a constructor that takes the given type and returns the expected type.  This happens when storing a value to a variable, when passing an argument to a function, and when returning a value.  The `StaticTuple` type has a variadic constructor that takes the element type that the list is made of.  So you can do this:

```
fn main():
  let data1 = StaticTuple[4, Int](1)
  print(data1.__len__()) # 4
  print(data1[0]) # 1
  print(data1[1]) # 1
  print(data1[2]) # 1
  print(data1[3]) # 1
  let data2 = StaticTuple[4, Int](2,3)
  print(data2.__len__()) # 4
  print(data2[0]) # 2
  print(data2[1]) # 3
  print(data2[2]) # 0
  print(data2[3]) # 0
```

Though the behavior of that constructor is not documented well.

**Comment by willghatch** [comment] 2023-11-21 17:45
@arthurevans This is basically the same issue as https://github.com/modularml/mojo/issues/1310, by the way, showing that this implicit conversion behavior is a common point of confusion in the docs.

**Comment by scottamain** [comment] 2023-12-13 07:21
@willghatch Can we mark this a duplicate of #1310 or is there something different do be done here?

**Comment by willghatch** [comment] 2023-12-14 23:44
Yes, we can mark it as a duplicate.

**Comment by scottamain** [comment] 2024-03-08 02:15
De-duping with https://github.com/modularml/mojo/issues/1310

**Closed by scottamain** 2024-03-08 02:15 UTC
Labels: bug, documentation, mojo
