### ISSUE TITLE
[BUG]:  Can not specify when the function does not return any value.

### ISSUE THREAD

**Issue by erogluegemen** [modularml/mojo#292] opened 2023-05-30 16:51 UTC
### Bug description

```shell
In python, we can specify what our function will return and in this example, im basically specifying that my function is not return anything but it give me an error like this:

error: Expression [32]:30:18: ambiguous call to 'your_function', each candidate requires 0 implicit conversions, disambiguate with an explicit cast
```

### Steps to reproduce

```shell
Python Code:
def your_function() -> None:
    x = 42
    y = 17.0

    if x != 0:
        z = 1.0
    else:
        z = 5.0
    print(z)
    
your_function()

Mojo:
def your_function() -> None:
    let x: Int = 42
    let y: F64 = 17.0

    let z: F32
    if x != 0:
        z = 1.0
    else:
        z = 5.0
    print(z)

your_function()

Error:
error: Expression [32]:30:18: ambiguous call to 'your_function', each candidate requires 0 implicit conversions, disambiguate with an explicit cast

Also you can check here for simplified version:

Python and Mojo Code(same code for both of them):
def test() -> None:
    print('hi')
    
test()

Work fine in python but i encountered with this error in Mojo again:
error: Expression [31]:19:9: ambiguous call to 'test', each candidate requires 0 implicit conversions, disambiguate with an explicit cast
```

### System information

```shell
11:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
10:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
9:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
8:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
7:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
6:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
5:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
4:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
3:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
2:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
0::/
```

**Comment by Mogball** [comment] 2023-06-05 21:30
I'm not able to reproduce this. It was likely fixed in the recent release.

**Closed by Mogball** 2023-06-05 21:30 UTC
Labels: bug
