### ISSUE TITLE
[BUG]: Error importing numpy: you should not try to import numpy from its source directory;

### ISSUE THREAD

**Issue by danny-su** [modularml/mojo#1825] opened 2024-02-28 13:27 UTC
### Bug description

![image](https://uploads.linear.app/2f794fde-0e09-4092-aa52-1ed3e9241f74/4db8f26d-6511-47a0-b2e8-071ebb791d71/4dea5afe-ef24-4e9c-a900-c0d268eec736?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmNzk0ZmRlLTBlMDktNDA5Mi1hYTUyLTFlZDNlOTI0MWY3NC80ZGI4ZjI2ZC02NTExLTQ3YTAtYjJlOC0wNzFlYmI3OTFkNzEvNGRlYTVhZmUtZWYyNC00ZTljLWE5MDAtYzBkMjY4ZWVjNzM2IiwiaWF0IjoxNzE0Njk1OTU4LCJleHAiOjMzMjg1MjU1OTU4fQ.NFF7lg-QIPPFpKiBupI6iwH1sprU-1VBHvTiyP9AwoU "=794x")

### Steps to reproduce

```
$ mojo
Welcome to Mojo! 🔥

Expressions are delimited by a blank line.
Type `:quit` to exit the REPL and `:mojo help` for further assistance.

  1> from python import Python
  2. let np = Python.import_module("numpy")
  3. let array = np.array([1, 2, 3])
  4. print(array)
  5.
Error: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
  5>
```

### System information

```shell
- What OS did you do install Mojo on ?
macOS 14.3.1
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.7.1 (af002202)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.5.0 (47924ae4)
```

**Comment by catalpaaa** [comment] 2024-03-01 05:09
Same issue here on x86_64 ubuntu 23.10 :(

**Comment by danny-su** [comment] 2024-03-01 06:59
@catalpaaa Removing Mojo completely and then reinstalling it will fix this issue.

**Comment by kseuro** [comment] 2024-03-08 01:03
> I have the same issue on a `MacOS Ventura 13.4`. This error persists even after completely removing mojo and modular, and reinstalling everything.
> 
> > Output of `mojo -v`
> > mojo 24.1.0 (55ec12d6)
> 
> > Output of `modular -v`
> > modular 0.5.1 (1b608e3d)
> 
> I created a `conda` environment using
> 
> ```
> conda create -yn mojo python=3.11
> ```
> 
> In my `bash_profile`, the following paths are set:
> 
> ```
> export MODULAR_HOME="$HOME/.modular"
> export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"
> export MOJO_PYTHON_LIBRARY="$HOME/miniconda3/envs/mojo/lib/libpython3.11.dylib"
> ```
> 
> The easiest way for me to reproduce this error is to run the `RayTracing.ipynb` under the examples directory in this repo. Calling the `render` function throws:
> 
> ```
> Error: Error importing numpy: you should not try to import numpy from
>         its source directory; please exit the numpy source tree, and relaunch
>         your python interpreter from there.
> ```

I figured out that I am able to execute the ray tracing code as a stand-alone mojo script using `iterm` but NOT vscode's built-in terminal. This is will be my work around for the time being.

**Comment by rafelafrance** [comment] 2024-03-23 19:26
For my particular case it was caused by a mismatch between the system python v3.10 and the virtual environment v3.11. If I changed my virtual env to 3.10 things worked just fine.

Additionally, if I changed the `python_lib` variable in `~/.modular/modular.cfg` to use python 3.11 it also works. 

1. Look at the contents  `~/.modular/modular.cfg`  to see where it's getting the python library. For me it's `/usr/lib/x86_64-linux-gnu/`
2. Verify the available python libraries with a `ls <location from 1>`
3. Backup and then edit `~/.modular/modular.cfg` to use another compatible python version... 3.8? to 3.11. For me, it was a one character change to: `python_lib = /usr/lib/x86_64-linux-gnu/libpython3.11.so.1.0`

**Comment by rafelafrance** [comment] 2024-03-23 19:58
For me it was caused by a mismatch between the system python v3.10 and my virtual environment python v3.11. If I set  `MOJO_PYTHON_LIBRARY` it worked just fine. In my particular case it was:

```zsh
export MOJO_PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.11.so.1.0 
```

**Comment by andompesta** [comment] 2024-03-26 11:54
> For me it was caused by a mismatch between the system python v3.10 and my virtual environment python v3.11. If I set `MOJO_PYTHON_LIBRARY` it worked just fine. You'll need to hunt down your python libraries for your system. 

Indeed I manage to fix it after updating my conda environment to python 3.12 as it matches the mojo `python_lib` version.

**Comment by jackos** [comment] 2024-06-06 21:53
This error could occur due to libpython version set on install being different to the python version on top of `PATH`. Fixed in next release, now use python on top of `PATH` to resolve path to libpython at runtime. You can try the new functionality now with `modular install nightly/mojo`

**Closed by jackos** 2024-06-06 21:53 UTC
Labels: bug, mojo-python-interop, mojo-repo
