### ISSUE TITLE
[BUG] can not use optional parameters and keyword parameters in a struct

### ISSUE THREAD

**Issue by Chhunneng** [modularml/mojo#1979] opened 2024-03-18 08:57 UTC
### Bug description

This code has been written in [`mojo/manual/parameters`](https://docs.modular.com/mojo/manual/parameters/), but I can not use `name` in the `struct`.

### Steps to reproduce

```mojo
struct KwParamStruct[greeting: String = "Hello", name: String = "🔥mojo🔥"]:
    fn __init__(inout self):
        print(greeting, name)

fn use_kw_params():
    var a = KwParamStruct[]()                 # expect prints 'Hello 🔥mojo🔥'
    var b = KwParamStruct[name="World"]()     # expect prints 'Hello World'
    var c = KwParamStruct[greeting="Hola"]()  # expect prints 'Hola 🔥mojo🔥'

fn main() raises:
    use_kw_params()
```

### System information

```shell
- macOS M1
- mojo 24.1.0 (55ec12d6)
- modular 0.5.2 (6b3a04fd)
```

**Comment by ematejska** [comment] 2024-03-18 19:18
Is this another dup of global variables?

**Comment by arthurevans** [comment] 2024-03-19 01:48
I don't know about global variables, but this is a regression, since this doc sample used to work.

It seems to be something about the variadic overload for `print()`, because replacing this line:

```mojo
print(greeting, name)
```

With two lines:

```mojo
print(greeting)
print(mojo)
``` 

Avoids the issue.

**Comment by Chhunneng** [comment] 2024-03-19 04:59
@arthurevans you are correct, for this issue do we need to update document? I'm happy contribute with this issue.

**Comment by Brian-M-J** [comment] 2024-07-05 14:25
Does not reproduce on the Mojo playground as of 5th July 2024. If you guys can confirm that this really isn't an issue anymore, maybe we can close it?

**Comment by ematejska** [comment] 2024-07-11 18:27
I see it working as well in the nightly build so closing this issue out now.  Thanks.

**Closed** 2024-07-11 18:27 UTC
Labels: bug, mojo-repo
