### ISSUE TITLE
[BUG]: Scope differences between Mojo and Python

### ISSUE THREAD

**Issue by jjbankert** [modularml/mojo#363] opened 2023-06-12 15:11 UTC
### Bug description
The scope of variables in Python is broader than in Mojo. This means that Mojo is not a strict superset, and code will fail now.

### Steps to reproduce
Running the code beneath will succeed as Python, but fail as Mojo. Comment/Uncomment the first line to see the difference.

```shell
%%python # comment to make the code fail
def your_function(a, b):
    if a != b:
        new_variable = 'function scoped variable'
    
    # fails in mojo, but in python the value exists outside the if scope
    # this is of course a silly example because python will also fail if a == b
    print(new_variable)

your_function(2, 3)
```

### System information

```shell
11:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
10:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
9:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
8:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
7:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
6:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
5:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
4:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
3:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
2:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podebc92afa_a9a0_4ee3_b4e9_afa89de16f6b.slice/cri-containerd-ee9b022f7c42ee8781372488ff27933dc06d3b73a90ef6ab05fa12e9b9a5b4c6.scope
0::/
```

**Comment by Mogball** [comment] 2023-06-12 23:51
Thanks for reporting this! That the scoping rules between Python and Mojo are not exactly the same is something we are actively working on. For now, I'm closing this as a duplicate of other issues.

**Closed by Mogball** 2023-06-12 23:51 UTC
Labels: bug
