### ISSUE TITLE
[BUG]: modular: error: unable to bootstrap the TUF repository, missing bootstrap.json

### ISSUE THREAD

**Issue by soccin** [modularml/mojo#1084] opened 2023-10-19 16:36 UTC
### Bug description

When running:
```
modular install mojo
```
get the following error
```
modular: error: unable to bootstrap the TUF repository, missing bootstrap.json
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?

macOS Ventura 13.5.2

- Provide version information for Mojo by pasting the output of `mojo -v`

Cannot provide, mojo did not install

- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.2.1 (5144fffe)
```

**Comment by bzcheeseman** [comment] 2023-10-19 22:52
Duplicate of https://github.com/modularml/mojo/issues/1090

**Closed by bzcheeseman** 2023-10-19 22:52 UTC
Labels: bug, modular-cli
