### ISSUE TITLE
[BUG]: runtime crash with `malloc(): unaligned tcache chunk detected`

### ISSUE THREAD

**Issue by HJLebbink** [modularml/mojo#1514] opened 2023-12-18 19:42 UTC
### Bug description

The program below crashes on line with `sort[T](data_vec)`. If, however, a copy of data_vec is made, and the `sort` is called on that copy, everything works fine. Thus I suspect that somehow DynamicVector data_vec is not created with proper alignment. This happens with DynamicVector of type:
* uint32 (and 32 elements)
* int8 (and 8 elements)
* int32 (and 32 elements)

Observed error: `malloc(): unaligned tcache chunk detected`

### Steps to reproduce

```python
from algorithm.sort import sort
from random import random_ui64
from time import time_function
from benchmark import keep


fn crash2[T: DType](samples: Int, size: Int) -> Int:
    var best = -1
    for sample in range(samples):
        var data_vec = DynamicVector[SIMD[T, 1]]()
        for i in range(size):
            data_vec.push_back(random_ui64(0, 100).cast[T]())

        @parameter
        fn runner():
            sort[T](data_vec)
            keep(data_vec)

        let ns = time_function[runner]()
        if best < 0 or ns < best:
            best = ns

    return best

fn main():
    print(crash2[DType.uint8](1_000_000, 32))
```
 

### System information

```shell
$ wsl --version
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2715

$ mojo --version
mojo 0.6.0 (d55c0025)

$ modular --version
modular 0.2.2 (95d42445)
```

**Comment by akirchhoff-modular** [comment] 2023-12-19 00:37
This is a known sharp edge, included in the "sharp edges" documentation ([section link](https://docs.modular.com/mojo/roadmap.html#parameter-closure-captures-are-unsafe-references)):

> ## Parameter closure captures are unsafe references
>
> You may have seen nested functions, or “closures”, annotated with the `@parameter` decorator. This creates a “parameter closure”, which behaves differently than a normal “stateful” closure. […]
>
> However, note that parameter closures are always capture by _unsafe_ reference. Mojo’s lifetime tracking is not yet sophisticated enough to form safe references to objects (see above section). This means that variable lifetimes need to be manually extended according to the lifetime of the parametric closure: […]
>
> The lifetime of the variable can be manually extended by discarding it explicitly.

To fix your code, you need to extend the lifetime of `data_vec` from _outside_ `runner`, like so:

```mojo
var data_vec = DynamicVector[SIMD[T, 1]]()
for i in range(size):
    data_vec.push_back(random_ui64(0, 100).cast[T]())

@parameter
fn runner():
    sort[T](data_vec)
    keep(data_vec)

let ns = time_function[runner]()
_ = data_vec
if best < 0 or ns < best:
    best = ns
```

While this is a bug, we are tracking the missing feature required to fix this more generally as part of our roadmap, and the current behavior is documented, so I am closing this as intended behavior for now.

**Closed by akirchhoff-modular** 2023-12-19 00:37 UTC
Labels: bug, mojo
