### ISSUE TITLE
[BUG]: `'kgen.global.address' op result type does not match global type` when using Dict

### ISSUE THREAD

**Issue by toiletsandpaper** [modularml/mojo#1813] opened 2024-02-26 10:20 UTC
### Bug description

When I'm trying to use Dict with `IntKey` (code will be provided below) - I am getting error:
<details>
<summary>Error Traceback</summary>

```
/Users/toiletsandpaper/Documents/mojo_test/fibonacci.mojo:19:5: error: 'kgen.global.address' op result type does not match global type '!kgen.struct<(index, index, index, struct<(pointer<scalar<invalid>>) memoryOnly>, struct<(pointer<struct<(struct<(array<apply(:() -> index @"$stdlib::$utils::$variant::_UnionSize::compute()"<:variadic<type> [[struct<() memoryOnly>, {"__moveinit__" : (!kgen.pointer<struct<() memoryOnly>> init_self, !kgen.pointer<struct<() memoryOnly>> owned_in_mem) -> !kgen.none = @"$stdlib::$collections::$optional::_NoneType::__moveinit__($stdlib::$collections::$optional::_NoneType=&,$stdlib::$collections::$optional::_NoneType)", "__del__" : (!kgen.pointer<struct<() memoryOnly>> owned_in_mem) -> !kgen.none = @"$stdlib::$collections::$optional::_NoneType::__del__($stdlib::$collections::$optional::_NoneType)", "__copyinit__" : (!kgen.pointer<struct<() memoryOnly>> init_self, !kgen.pointer<struct<() memoryOnly>> borrow_in_mem) -> !kgen.none = @"$stdlib::$collections::$optional::_NoneType::__copyinit__($stdlib::$collections::$optional::_NoneType=&,$stdlib::$collections::$optional::_NoneType)"}], [struct<(index, struct<(index) memoryOnly>, index) memoryOnly>, {"__moveinit__" : (!kgen.pointer<struct<(index, struct<(index) memoryOnly>, index) memoryOnly>> init_self, !kgen.pointer<struct<(index, struct<(index) memoryOnly>, index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$stdlib::$collections::$dict::DictEntry::__moveinit__($stdlib::$collections::$dict::DictEntry[K, V]=&,$stdlib::$collections::$dict::DictEntry[K, V])"<:type [struct<(index) memoryOnly>, {"__moveinit__" : (!kgen.pointer<struct<(index) memoryOnly>> init_self, !kgen.pointer<struct<(index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$key::IntKey::__moveinit__($key::IntKey=&,$key::IntKey)", "__del__" : (!kgen.pointer<struct<(index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$key::IntKey::__del__($key::IntKey)", "__copyinit__" : (!kgen.pointer<struct<(index) memoryOnly>> init_self, !kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> !kgen.none = @"$key::IntKey::__copyinit__($key::IntKey=&,$key::IntKey)", "__hash__" : (!kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> index = @"$key::IntKey::__hash__($key::IntKey)", "__eq__" : (!kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem, !kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> !pop.scalar<bool> = @"$key::IntKey::__eq__($key::IntKey,$key::IntKey)"}], :type [index, {"__moveinit__" : (!kgen.pointer<index> init_self, !kgen.pointer<index> owned_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___moveinit__($stdlib::$builtin::$int::Int=&,$stdlib::$builtin::$int::Int)", "__del__" : (!kgen.pointer<index> owned_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___del__($stdlib::$builtin::$int::Int)", "__copyinit__" : (!kgen.pointer<index> init_self, !kgen.pointer<index> borrow_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___copyinit__($stdlib::$builtin::$int::Int=&,$stdlib::$builtin::$int::Int)"}]>, "__del__" : (!kgen.pointer<struct<(index, struct<(index) memoryOnly>, index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$stdlib::$collections::$dict::DictEntry::__del__($stdlib::$collections::$dict::DictEntry[K, V])"<:type [struct<(index) memoryOnly>, {"__moveinit__" : (!kgen.pointer<struct<(index) memoryOnly>> init_self, !kgen.pointer<struct<(index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$key::IntKey::__moveinit__($key::IntKey=&,$key::IntKey)", "__del__" : (!kgen.pointer<struct<(index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$key::IntKey::__del__($key::IntKey)", "__copyinit__" : (!kgen.pointer<struct<(index) memoryOnly>> init_self, !kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> !kgen.none = @"$key::IntKey::__copyinit__($key::IntKey=&,$key::IntKey)", "__hash__" : (!kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> index = @"$key::IntKey::__hash__($key::IntKey)", "__eq__" : (!kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem, !kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> !pop.scalar<bool> = @"$key::IntKey::__eq__($key::IntKey,$key::IntKey)"}], :type [index, {"__moveinit__" : (!kgen.pointer<index> init_self, !kgen.pointer<index> owned_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___moveinit__($stdlib::$builtin::$int::Int=&,$stdlib::$builtin::$int::Int)", "__del__" : (!kgen.pointer<index> owned_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___del__($stdlib::$builtin::$int::Int)", "__copyinit__" : (!kgen.pointer<index> init_self, !kgen.pointer<index> borrow_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___copyinit__($stdlib::$builtin::$int::Int=&,$stdlib::$builtin::$int::Int)"}]>, "__copyinit__" : (!kgen.pointer<struct<(index, struct<(index) memoryOnly>, index) memoryOnly>> init_self, !kgen.pointer<struct<(index, struct<(index) memoryOnly>, index) memoryOnly>> borrow_in_mem) -> !kgen.none = @"$stdlib::$collections::$dict::DictEntry::__copyinit__($stdlib::$collections::$dict::DictEntry[K, V]=&,$stdlib::$collections::$dict::DictEntry[K, V])"<:type [struct<(index) memoryOnly>, {"__moveinit__" : (!kgen.pointer<struct<(index) memoryOnly>> init_self, !kgen.pointer<struct<(index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$key::IntKey::__moveinit__($key::IntKey=&,$key::IntKey)", "__del__" : (!kgen.pointer<struct<(index) memoryOnly>> owned_in_mem) -> !kgen.none = @"$key::IntKey::__del__($key::IntKey)", "__copyinit__" : (!kgen.pointer<struct<(index) memoryOnly>> init_self, !kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> !kgen.none = @"$key::IntKey::__copyinit__($key::IntKey=&,$key::IntKey)", "__hash__" : (!kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> index = @"$key::IntKey::__hash__($key::IntKey)", "__eq__" : (!kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem, !kgen.pointer<struct<(index) memoryOnly>> borrow_in_mem) -> !pop.scalar<bool> = @"$key::IntKey::__eq__($key::IntKey,$key::IntKey)"}], :type [index, {"__moveinit__" : (!kgen.pointer<index> init_self, !kgen.pointer<index> owned_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___moveinit__($stdlib::$builtin::$int::Int=&,$stdlib::$builtin::$int::Int)", "__del__" : (!kgen.pointer<index> owned_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___del__($stdlib::$builtin::$int::Int)", "__copyinit__" : (!kgen.pointer<index> init_self, !kgen.pointer<index> borrow_in_mem) -> !kgen.none = @"$stdlib::$builtin::$int::Int::`thunk___copyinit__($stdlib::$builtin::$int::Int=&,$stdlib::$builtin::$int::Int)"}]>}]]>), scalar<si8>>, scalar<si16>) memoryOnly>) memoryOnly>>, index, index) memoryOnly>) memoryOnly>'
    cache[0] = 0
    ^
/Users/toiletsandpaper/Documents/mojo_test/fibonacci.mojo:19:5: note: see current operation: %4 = "kgen.global.address"() {global = @"$fibonacci::cache"} : () -> !kgen.pointer<struct<(index, index, index, struct<(pointer<scalar<invalid>>) memoryOnly>, struct<(pointer<struct<(struct<(array<24, scalar<si8>>, scalar<si16>) memoryOnly>) memoryOnly>>, index, index) memoryOnly>) memoryOnly>>
mojo: error: failed to run the pass manager
```

</details>

### Steps to reproduce

Here is hashable `IntKey` implementations
<details>
<summary>key.mojo</summary>

```mojo
from collections import KeyElement

@value
struct StringKey(KeyElement):
    var s: String

    fn __init__(inout self, owned s: String):
        self.s = s ^

    fn __init__(inout self, s: StringLiteral):
        self.s = String(s)

    fn __hash__(self) -> Int:
        let ptr = self.s._buffer.data.value
        return hash(DTypePointer[DType.int8](ptr), len(self.s))

    fn __eq__(self, other: Self) -> Bool:
        return self.s == other.s

@value
struct IntKey(KeyElement):
    var i: Int

    fn __init__(inout self, owned i: Int):
        self.i = i
        
    fn __hash__(self) -> Int:
        return hash(self.i)

    fn __eq__(self, other: Self) -> Bool:
        return self.i == other.i
```

</details>

</hr>

And here is main file:

<details>
<summary>`fibonacci.mojo`</summary>

```mojo
from collections import Dict, Optional
from key import IntKey

var cache = Dict[IntKey, Int]()

fn fib_cached(i: Int) raises -> Int:
    if cache.find(i):
        return cache[i]
    cache[i] = fib_cached(i - 1) + fib_cached(i - 2)
    return cache[i]


fn fib(i: Int) -> Int:
    if i < 2:
        return 1
    return fib(i - 1) + fib(i - 2)

fn main() raises:
    cache[0] = 0
    cache[1] = 1
    print(fib_cached(40))
```

</details>

### System information

```shell
- What OS did you do install Mojo on? 
  - `MacOS 14.3, M1`
- Provide version information for Mojo by pasting the output of `mojo -v` 
  - `mojo 0.7.0 (af002202)`
- Provide Modular CLI version by pasting the output of `modular -v`
  - `modular 0.4.1 (2d8afe15)`
```

**Comment by toiletsandpaper** [comment] 2024-02-26 12:06
So, problem is that Dict was in file-scope level and referencing it in `main()` causing this error. For me this is still bug and I will not close this as solved.

Code below is fully working: (alias is cosmetic)

```mojo
from collections import Dict, Optional
from key import IntKey

alias IntDict = Dict[IntKey, Int]


fn fib_cached(i: Int, inout cache: IntDict) raises -> Int:
    if cache.find(i):
        return cache[i]
    cache[i] = fib_cached(i - 1, cache) + fib_cached(i - 2, cache)
    return cache[i]


fn fib(i: Int) -> Int:
    if i < 2:
        return 1
    return fib(i - 1) + fib(i - 2)

fn main() raises:
    var cache = IntDict()
    cache[0] = 0
    cache[1] = 1
    print(fib_cached(40, cache))
```

**Comment by ematejska** [comment] 2024-02-27 17:37
Is this a dup of global variables?

**Comment by toiletsandpaper** [comment] 2024-02-28 11:45
> Is this a dup of global variables?

Looks like yes. Different traceback error, but same origin like in https://github.com/modularml/mojo/issues/1573
That explains why it is working in last example

I will not complain if it will be closed as duplicate

**Comment by laszlokindrat** [comment] 2024-03-04 17:44
Closing as duplicate of https://github.com/modularml/mojo/issues/1573

**Closed by laszlokindrat** 2024-03-04 17:44 UTC
Labels: bug, mojo-lang, mojo
