### ISSUE TITLE
[BUG]: Failed to evaluate `math.abs` and `math.exp` at compile-time

### ISSUE THREAD

**Issue by leandrolcampos** [modularml/mojo#1244] opened 2023-11-06 21:51 UTC
### Bug description

Failed to evaluate `math.abs` and `math.exp` at compile-time.

### Steps to reproduce

When I try to execute this following code...

```
>>> import math
>>> alias y = math.abs[DType.float64, 1](-1.0)
>>> print(y)
```

... I get this error message:

> error: wrapped Expression [2]:6:1: no viable expansions found
> fn __lldb_expr__2(inout __mojo_repl_arg: __mojo_repl_context__):
> ^
> 
> wrapped Expression [2]:8:28:   call expansion failed - no concrete specializations
>     __mojo_repl_expr_impl__(__mojo_repl_arg, __get_address_as_lvalue(__mojo_repl_arg.`__mojo_repl_expr_failed`.load().address))
>                            ^
> 
> wrapped Expression [2]:12:1:     no viable expansions found
> def __mojo_repl_expr_impl__(inout __mojo_repl_arg: __mojo_repl_context__, inout `__mojo_repl_expr_failed`: __mlir_type.`!kgen.declref<@"$builtin"::@"$bool"::@Bool, !lit.metatype<@"$builtin"::@"$bool"::@Bool>>`) -> None:
> ^
> 
> wrapped Expression [2]:18:26:       call expansion failed - no concrete specializations
>   __mojo_repl_expr_body__()
>                          ^
> 
> wrapped Expression [2]:14:3:         no viable expansions found
>   def __mojo_repl_expr_body__() -> None:
>   ^
> 
> Expression [2]:2:7:           failed to evaluate 'apply'
> print(y)
>       ^
> 
> expression failed to parse (no further compiler diagnostics)

I get a similar error with `math.exp`.

### System information

```shell
- What OS did you do install Mojo on ? `Ubuntu 22.04.2 LTS (WSL2)`
- Provide version information for Mojo by pasting the output of `mojo -v`: `0.5.0 (6e50a738)`
- Provide Modular CLI version by pasting the output of `modular -v``: `0.2.0 (355ea9c0)`
```

**Comment by ematejska** [comment] 2023-11-07 21:39
Fails not in REPL too.

**Comment by Mogball** [comment] 2023-11-08 02:22
Closing as not reproducible

**Comment by Sharktheone** [comment] 2023-11-08 07:22
I can also reproduce this with mojo 0.5.0

<details>

![image](https://github.com/modularml/mojo/assets/105171995/05cc2bb1-03cf-426c-8833-3d5dd0f21c0c)

</details>

**Comment by Mogball** [comment] 2023-11-08 07:23
@soraros with your file I can reproduce the error. Not sure why neither I nor Ewa were getting it in the REPL/Jupyter notebook.

**Comment by leandrolcampos** [comment] 2023-11-08 16:18
@Mogball Reproducing the error in Jupyter notebook.

![image](https://github.com/modularml/mojo/assets/15185896/aadb91bf-080a-4cf6-9a55-1573ae7e3c03)

**Comment by leandrolcampos** [comment] 2023-11-10 22:19
I encounter the same problem with `math.exp`.

**Comment by JoeLoser** [comment] 2024-02-06 15:49
Still reproduces with latest `mojo`.

**Comment by soraros** [comment] 2024-05-27 05:07
Duplicate of #933.

**Closed** 2024-06-05 23:22 UTC
Labels: bug, mojo-stdlib, mojo, mojo-repo
