### ISSUE TITLE
[BUG] Custom data types cannot include pointers to themselves, can they?

### ISSUE THREAD

**Issue by wanbaocheng** [modularml/mojo#1100] opened 2023-10-19 23:18 UTC
### Bug description

As stated in the title

### Steps to reproduce

code as follows：

`list.mojo`
```
@register_passable("trivial")
struct Node[T: AnyType]:
    var data: T
    var prev: Pointer[Node[T]]
    var next: Pointer[Node[T]]

    fn __init__(data: T) -> Self:
        return Self {
            data: data,
            prev: Pointer[Node[T]](),
            next: Pointer[Node[T]](),
        }
```
Execute the following command:
```
mojo build list.mojo
```
 then generate the following error infomation:
```
mojo: /__w/modular/modular/third-party/llvm-project/llvm/include/llvm/Support/Casting.h:656: decltype(auto) llvm::dyn_cast(From &) [To = M::KGEN::ParamRefType, From = mlir::Type]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo build list.mojo
[938054:938055:20231020,071559.904589:ERROR directory_reader_posix.cc:42] opendir ~/.modular/crashdb/attachments/25b92ece-2d46-4330-9310-94633c257b52: No such file or directory (2)
 #0 0x0000564fd4e55fd7 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b7fd7)
 #1 0x0000564fd4e53bae (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b5bae)
 #2 0x0000564fd4e566af (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b86af)
 #3 0x00007fe759136420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007fe758b2400b raise /build/glibc-BHL3KM/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007fe758b03859 abort /build/glibc-BHL3KM/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007fe758b03729 get_sysdep_segment_value /build/glibc-BHL3KM/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007fe758b03729 _nl_load_domain /build/glibc-BHL3KM/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007fe758b14fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #9 0x0000564fd6e258e1 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x25878e1)
#10 0x0000564fd65702d9 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1cd22d9)
#11 0x0000564fd6405e45 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b67e45)
#12 0x0000564fd64053b9 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b673b9)
#13 0x0000564fd640728f (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b6928f)
#14 0x0000564fd53cfc56 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xb31c56)
#15 0x0000564fd6405c02 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b67c02)
#16 0x0000564fd64057ef (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b677ef)
#17 0x0000564fd6406fcf (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b68fcf)
#18 0x0000564fd6ecd7e1 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x262f7e1)
#19 0x0000564fd64057d9 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b677d9)
#20 0x0000564fd6406f1f (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b68f1f)
#21 0x0000564fd53b142e (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xb1342e)
#22 0x0000564fd6406dc2 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b68dc2)
#23 0x0000564fd64069a3 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b689a3)
#24 0x0000564fd6406e6f (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b68e6f)
#25 0x0000564fd53a0569 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xb02569)
#26 0x0000564fd6406dc2 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b68dc2)
#27 0x0000564fd64069a3 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b689a3)
#28 0x0000564fd640b042 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b6d042)
#29 0x0000564fd640b47e (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b6d47e)
#30 0x0000564fd640324c (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1b6524c)
#31 0x0000564fd768e336 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2df0336)
#32 0x0000564fd768e9c1 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2df09c1)
#33 0x0000564fd7690f12 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2df2f12)
#34 0x0000564fd637b058 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1add058)
#35 0x0000564fd534cdf9 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xaaedf9)
#36 0x0000564fd637aabd (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1adcabd)
#37 0x0000564fd6f5b92a (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x26bd92a)
#38 0x0000564fd6f6272c (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x26c472c)
#39 0x0000564fd6feb159 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x274d159)
#40 0x0000564fd6feb3c9 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x274d3c9)
#41 0x0000564fd6fe8134 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x274a134)
#42 0x0000564fd6f60aa4 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x26c2aa4)
#43 0x0000564fd5315ee9 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa77ee9)
#44 0x0000564fd4e043b1 (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5663b1)
#45 0x0000564fd4e02b5e (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x564b5e)
#46 0x00007fe758b05083 __libc_start_main /build/glibc-BHL3KM/glibc-2.31/csu/../csu/libc-start.c:342:3
#47 0x0000564fd4e0235e (~/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x56435e)
[1]    938052 abort (core dumped)  mojo build list.mojo
```

### System information

```shell
Ubunt20.04, mojo 0.4.0 (9e33b013), modular 0.2.1 (5144fffe),x86_64
```

**Comment by Mogball** [comment] 2023-10-25 05:56
Seems like a bug. @weiweichen where did we leave off on this?

**Comment by weiweichen** [comment] 2023-10-25 13:30
Oh, it's the same issue as https://github.com/modularml/mojo/issues/435 where the self type has parameter in it which a good solution is still work in progress :-(

**Comment by Mogball** [comment] 2023-11-09 01:35
Closing as dupe of [#435](https://github.com/modularml/mojo/issues/435)

**Closed by Mogball** 2023-11-09 01:35 UTC
Labels: bug, mojo-lang, mojo
