### ISSUE TITLE
[Mojo]: modular: error: failed to run python:

### ISSUE THREAD

**Issue by BeeCodeB** [modularml/mojo#929] opened 2023-09-26 16:14 UTC
### Issue description

My installation of mojo-sdk in modular-cli in terminal emulation (bash) fails due to some library_path environment variable not set properly:

_Could not find libpython. Check your Python installation and ensure that $LD_LIBRARY_PATH includes the location to the installed Python library (e.g. /usr/lib/x86_64-linux-gnu)._

### Steps to reproduce

```
~$ modular clean
~$ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.3.0, installing to /home/verwalter/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: find_libpython==0.3.0 in /home/verwalter/.local/lib/python3.10/site-packages (from -r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /home/verwalter/.local/lib/python3.10/site-packages (from -r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/verwalter/.local/lib/python3.10/site-packages (from -r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: ansiwrap in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: click in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.1.7)
Requirement already satisfied: pyyaml in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: nbformat>=5.1.2 in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: nbclient>=0.2.0 in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.32.2 in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: requests in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: entrypoints in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.4)
Requirement already satisfied: tenacity in /home/verwalter/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/verwalter/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/verwalter/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in /home/verwalter/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: tornado>=6.2 in /home/verwalter/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: traitlets>=5.3 in /home/verwalter/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.10.0)
Requirement already satisfied: platformdirs>=2.5 in /home/verwalter/.local/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: fastjsonschema in /home/verwalter/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /home/verwalter/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.1)
Requirement already satisfied: six>=1.5 in /home/verwalter/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /home/verwalter/.local/lib/python3.10/site-packages (from ansiwrap->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/verwalter/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /home/verwalter/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/verwalter/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in /home/verwalter/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.22)
Requirement already satisfied: attrs>=22.2.0 in /home/verwalter/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/verwalter/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/verwalter/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/verwalter/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.10.3)
Traceback (most recent call last):
  File "/home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 67, in <module>
    main()
  File "/home/verwalter/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 50, in main
    raise Exception(
Exception: Could not find libpython. Check your Python installation and ensure that $LD_LIBRARY_PATH includes the location to the installed Python library (e.g. /usr/lib/x86_64-linux-gnu).
modular: error: failed to run python:
~$ 
```

### Version Info

```shell
Modular CLI version: modular 0.1.4 (6b54d308)
    
Environment: **computer system** [AMD Ryzen 5 PRO 2400G with Radeon Vega Graphics × 8, 15,0 GiB RAM] 

Operating System: Ubuntu Version 23.04 (Lunar Lobster) 64-bit Kernel Linux 6.2.0-32-generic x86_64 MATE 1.26.0

Python: 3.11.4
gcc: (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0
clang: Ubuntu clang version 15.0.7
```

**Comment by SimplyYummy** [comment] 2023-09-26 22:40
I believe duplicate of https://github.com/modularml/mojo/issues/551. It's also recommended to install in a virtual environment. 

The error you're encountering is related to the inability to find the `libpython` library. The error message suggests that the `$LD_LIBRARY_PATH` environment variable may not be correctly set or doesn't include the directory where `libpython` resides.

Here's what you can do to resolve the issue:

1. **Find the location of libpython**:
   Use the `find` command to locate the `libpython` file on your system:
   ```bash
   sudo find / -name "libpython*.so*"
   ```
   This should return the path(s) to the `libpython` shared object file(s). For instance, you might see something like `/usr/lib/x86_64-linux-gnu/libpython3.10.so`.

2. **Update the `$LD_LIBRARY_PATH`**:
   Once you've found the location, you can add it to the `$LD_LIBRARY_PATH` environment variable. If, for example, `libpython` is located in `/usr/lib/x86_64-linux-gnu/`, you can update the `$LD_LIBRARY_PATH` as follows:
   ```bash
   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/
   ```

3. **Make the change permanent** (optional):
   If you want to make this change permanent (so you don't have to set it every time you open a terminal), you can add the `export` line from step 2 to your `~/.bashrc` or `~/.profile` file:
   ```bash
   echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/' >> ~/.bashrc
   source ~/.bashrc
   ```

4. **Retry the installation**:
   After setting the `$LD_LIBRARY_PATH`, try running the `modular install mojo` command again.

5. **Check if `find_libpython` can find the library**:
   Since `find_libpython` is being used in the post-install script, you can also manually run it to ensure it's able to find `libpython`. This is just an additional step to double-check:
   ```bash
   python3 -m find_libpython
   ```

If everything is set up correctly, the installation should proceed without any issues related to `libpython`.

See the links below for steps by the devs and for more information: 
https://github.com/modularml/mojo/issues/551#issuecomment-1734088284
https://github.com/modularml/mojo/issues/590#issuecomment-1734050196
https://docs.modular.com/mojo/roadmap.html#mojo-sdk-known-issues
https://www.modular.com/newsletters/modverse-weekly-2

**Comment by jackos** [comment] 2023-09-29 01:43
Hi @BeeCodeB please report back if the above suggestions don't work for you.

If you can't find any libpython you can use conda to install it:

_If you don't have conda you can [install miniconda here](https://docs.conda.io/projects/miniconda/en/latest/)_
```bash
conda create -yn py311 python=3.11
conda activate py311

export MOJO_PYTHON_LIBRARY="$(conda info --base)/envs/py311/lib/libpython3.11.so"
export LD_LIBRARY_PATH="$(conda info --base)/envs/py311/lib"
```
Then try installing again

**Closed by jackos** 2023-09-29 01:43 UTC
Labels: mojo-tooling, mojo

**Comment by Hassaan149** [comment] 2024-01-17 08:21
Hey guys, I am getting something like this, I guess it's similar to the one described above.
modular: error: failed to run python: Executable "$_self.package_path/venv/bin/python" doesn't exist!
