### ISSUE TITLE
[BUG]: Compiler crashes when passing pointer instance at compile time to a struct

### ISSUE THREAD

**Issue by ivellapillil** [modularml/mojo#1269] opened 2023-11-10 15:56 UTC
### Bug description

The following code crashes the compiler (may be this code should be prevented from compiling with a proper error message?).

```
struct A[p: Pointer[Int]]:
    fn __init__(inout self): pass

fn fun(x: fn(A) -> Int) -> Int:
    alias p: Pointer[Int] = Pointer[Int].alloc(32)
    return x(A[p]())

fn main():
    pass

```

The error:

```
Assertion failed: (bindOperands.front() && "binding a dynamic callee?"), function emitIndirectCall, file CallEmission.cpp, line 1312.
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo tree.mojo
1.      Crash resolving decl body at loc("/Users/indukumar/Projects/Mojo/tree.mojo":4:1)
    >> fn fun(x: fn(A) -> Int) -> Int:
       ^..............................
    >>     alias p: Pointer[Int] = Pointer[Int].alloc(32)
    >>     return x(A[p]())
       ....................<
2.      Crash parsing statement at loc("/Users/indukumar/Projects/Mojo/tree.mojo":6:5)
    >>     return x(A[p]())
           ^...............<
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo                     0x0000000102ac6fc0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  mojo                     0x0000000102ac5120 llvm::sys::RunSignalHandlers() + 112
2  mojo                     0x0000000102ac765c SignalHandler(int) + 344
3  libsystem_platform.dylib 0x000000018772fa24 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000187700cc0 pthread_kill + 288
5  libsystem_c.dylib        0x0000000187610a40 abort + 180
6  libsystem_c.dylib        0x000000018760fd30 err + 0
7  mojo                     0x00000001051279d0 M::KGEN::LIT::ExprEmitter::emitIndirectCall(M::KGEN::LIT::CValue, M::KGEN::LIT::CallOperands const&, M::KGEN::LIT::ValueDest&, M::KGEN::LIT::ExprNode const*) (.cold.3) + 0
8  mojo                     0x0000000102dbe638 M::KGEN::LIT::ExprEmitter::emitIndirectCall(M::KGEN::LIT::CValue, M::KGEN::LIT::CallOperands const&, M::KGEN::LIT::ValueDest&, M::KGEN::LIT::ExprNode const*) + 2408
9  mojo                     0x0000000102e06ad8 M::KGEN::LIT::CallNode::emitIR(M::KGEN::LIT::ValueDest&, M::KGEN::LIT::ExprEmitter&) const + 3232
10 mojo                     0x0000000102dfa0a4 M::KGEN::LIT::ExprEmitter::emitExprSRValue(M::KGEN::LIT::ExprNode const*, M::KGEN::LIT::ExprContext, M::KGEN::LIT::ASTType) + 108
11 mojo                     0x0000000102e2afe0 (anonymous namespace)::StmtParser::parseSuite(long)::$_6::operator()(bool, unsigned long) const + 10688
12 mojo                     0x0000000102e284c4 (anonymous namespace)::StmtParser::parseSuite(long) + 84
13 mojo                     0x0000000102e28394 M::KGEN::LIT::ParserBase::parseSuite(M::KGEN::LIT::ASTDecl&) + 60
14 mojo                     0x0000000102dd8d28 M::KGEN::LIT::DeclResolver::resolveBody(M::KGEN::LIT::FuncOp, M::KGEN::LIT::Lexer&, M::KGEN::LIT::ASTDecl&) + 1508
15 mojo                     0x0000000102dd1a44 M::KGEN::LIT::DeclResolver::resolve(M::KGEN::LIT::ASTDecl&, M::KGEN::LIT::DeclResolvedness, llvm::SMLoc) + 1552
16 mojo                     0x0000000102dd03a4 M::KGEN::LIT::DeclResolver::resolveAllReferencedFrom(M::KGEN::LIT::ASTDecl&) + 284
17 mojo                     0x0000000102debb20 importMojoImpl(llvm::StringRef, llvm::SourceMgr&, M::KGEN::LIT::SharedState&, mlir::TimingScope&, llvm::SmallVectorImpl<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>*, llvm::function_ref<M::KGEN::LIT::ASTDecl& (mlir::ModuleOp)>) + 296
18 mojo                     0x0000000102dec350 M::KGEN::LIT::importMojoFile(llvm::SourceMgr&, M::KGEN::LIT::ParserConfig&, mlir::TimingScope&, llvm::SmallVectorImpl<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>*) + 204
19 mojo                     0x0000000102a1096c M::invokeMojoParser(M::State const&, llvm::opt::InputArgList const&, M::KGEN::CompilationOptions&, mlir::MLIRContext*, M::LLCL::Runtime&, llvm::opt::OptSpecifier, llvm::opt::OptSpecifier, llvm::opt::OptSpecifier, llvm::opt::OptSpecifier, llvm::function_ref<mlir::OwningOpRef<mlir::ModuleOp> (M::KGEN::LIT::ParserConfig&, mlir::TimingScope&)>) + 392
20 mojo                     0x0000000102a20884 run(M::State const&) + 1608
21 mojo                     0x0000000102a0ae78 main + 1672
22 dyld                     0x00000001873850e0 start + 2360
[43722:1618115:20231110,165251.823886:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)
zsh: abort      mojo tree.mojo
```

### Steps to reproduce

See above

### System information

```shell
System Version: macOS 14.1 (23B74)
Kernel Version: Darwin 23.1.0
Model Name: MacBook Pro
Model Identifier: MacBookPro18,3
Model Number: MKGP3SM/A
Chip: Apple M1 Pro
Total Number of Cores: 8 (6 performance and 2 efficiency)
Memory: 16 GB

mojo 0.5.0 (6e50a738)
modular 0.2.1 (5144fffe)
```

**Comment by laszlokindrat** [comment] 2023-12-13 18:11
Thanks for opening the ticket! This seems like a duplicate of https://github.com/modularml/mojo/issues/1223, so I'll close it in favor of that.

**Closed by laszlokindrat** 2023-12-13 18:11 UTC
Labels: bug, mojo-lang, mojo
