### ISSUE TITLE
[BUG]: Behaviour changes with seemingly unrelated code change

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#937] opened 2023-09-27 04:25 UTC
### Bug description

Behaviour of code regrading integer literal changes with seemingly unrelated code change.

### Steps to reproduce

```mojo
def main():
  let a = 10 # (*)
  let n: IntLiteral = 10
  print(n)
```

If line `(*)` is commented out or the value is change to something other than 10, the code errors out.

### System information

```shell
- OS: Docker on Intel macOS
- mojo -v: mojo 0.3.0 (f64f9601)
- modular -v: modular 0.1.4 (6b54d308)
```

**Comment by cheburakshu** [comment] 2023-09-27 04:42
yes, interesting

this compiles:

```
def a():
    let a = 10
    let n: IntLiteral = 10
    print(n)

def b():
    # let a = 10
    let n: IntLiteral = 10
    print(n)

# def main():
#     # let a = 10
#     let n: IntLiteral = 10
#     print(n)
    

```

this doesn't

```
def a():
    let a = 10
    let n: IntLiteral = 10
    print(n)

def b():
    # let a = 10
    let n: IntLiteral = 10
    print(n)

def main():
    # let a = 10
    let n: IntLiteral = 10
    print(n)
    
```

```
error: Expression [14]:13:25: failed to legalize operation 'kgen.param.constant' that was explicitly marked illegal
    let n: IntLiteral = 10
                        ^

expression failed to parse (no further compiler diagnostics)

```

**Comment by ematejska** [comment] 2023-09-27 19:14
There is a problem with the comments on lines that are not separate lines.  That will be fixed in the next release. Separately, you get the legalization error message.
This is the code that is causing the error:

def main():
    # let a = 10
    let n: IntLiteral = 10
    print(n)

**Comment by cheburakshu** [comment] 2023-09-27 23:06
any idea why it only happens when the comment is in `main` not in function `b`? It is the same code.

**Comment by jackos** [comment] 2023-09-29 01:31
@cheburakshu was a problem with the parser and inline comments, can confirm this is working as expected as of `0.3.1`

**Closed by jackos** 2023-09-29 01:30 UTC
Labels: bug, mojo-lang, mojo

**Comment by jackos** [comment] 2023-09-29 15:47
@soraros I'm not sure what the problem is, both of those code blocks run without any problem, and they should run as there's nothing wrong with them

**Comment by ksandvik** [comment] 2023-09-29 16:28
I could actually see the same issue with mojo 0.3.1.
