### ISSUE TITLE
mojo slower that python

### ISSUE THREAD

**Issue by Sergeiprogrammer** [modularml/mojo#3383] opened 2024-08-15 15:04 UTC
### Bug description

Mojo in a for loop of 1 million iterations is 2 times slower than Python. I performed all actions on one PC that only has Mojo, Python, and VS Code installed. They were all installed on the same day, using the newest versions available. I used a timer and got the following results: Python: 10 seconds, Mojo: 18 seconds. How does this work?

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by soraros** [comment] 2024-08-15 17:50
Do you mind providing the script you used?

**Comment by Raghucharan16** [comment] 2024-08-21 14:16
Came here to say the same, i have 2 files, sample.py and sample.mojo in which it has print() statement in a loop 
sample.py
```
for i in range(100):
    print(i)
```
sample.mojo
```
fn main():
    for i in range(100):
        print(i)
```
python took 86ms and mojo took 386ms which is a huge difference. and also i really want to improve my existing face recognition pipeline but as mojo is new, i think it doesn't have libraries support.

**Comment by soraros** [comment] 2024-08-21 17:06
Possible duplicate of #975.

**Closed** 2024-09-30 17:24 UTC
Labels: bug, mojo-repo
