### ISSUE TITLE
[BUG]: Mojo fails to install (Debian OS)

### ISSUE THREAD

**Issue by dubyabondz** [modularml/mojo#980] opened 2023-10-02 21:32 UTC
### Bug description

Mojo is not installing using the modular command provided on https://developer.modular.com/download

### Steps to reproduce

Copied command line directly:
bill@bill-debian:~$ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.3.1
# Installing to /home/bill/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0
  Downloading find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting papermill==2.4.0
  Downloading papermill-2.4.0-py3-none-any.whl (38 kB)
Collecting jupyter_client>=8.3.0
  Downloading jupyter_client-8.3.1-py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 866.5 kB/s eta 0:00:00
Collecting ipykernel>=6.25.0
  Downloading ipykernel-6.25.2-py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.2/154.2 kB 3.9 MB/s eta 0:00:00
Collecting ansiwrap
  Downloading ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting click
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 617.8 kB/s eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.7/757.7 kB 1.6 MB/s eta 0:00:00
Collecting nbformat>=5.1.2
  Downloading nbformat-5.9.2-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.6/77.6 kB 954.6 kB/s eta 0:00:00
Collecting nbclient>=0.2.0
  Using cached nbclient-0.8.0-py3-none-any.whl (73 kB)
Collecting tqdm>=4.32.2
  Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 4.9 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 547.1 kB/s eta 0:00:00
Collecting entrypoints
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting tenacity
  Downloading tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting jupyter-core!=5.0.*,>=4.12
  Downloading jupyter_core-5.3.2-py3-none-any.whl (28 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyzmq>=23.0
  Downloading pyzmq-25.1.1-cp311-cp311-manylinux_2_28_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.1 MB/s eta 0:00:00
Collecting tornado>=6.2
  Downloading tornado-6.3.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.7/427.7 kB 1.5 MB/s eta 0:00:00
Collecting traitlets>=5.3
  Downloading traitlets-5.10.1-py3-none-any.whl (122 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.1/122.1 kB 668.0 kB/s eta 0:00:00
Collecting comm>=0.1.1
  Downloading comm-0.1.4-py3-none-any.whl (6.6 kB)
Collecting debugpy>=1.6.5
  Downloading debugpy-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 1.9 MB/s eta 0:00:00
Collecting ipython>=7.23.1
  Downloading ipython-8.16.1-py3-none-any.whl (806 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.0/807.0 kB 1.1 MB/s eta 0:00:00
Collecting matplotlib-inline>=0.1
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
Collecting packaging
  Downloading packaging-23.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 475.5 kB/s eta 0:00:00
Collecting psutil
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.8 MB/s eta 0:00:00
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30
  Downloading prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.2/385.2 kB 1.5 MB/s eta 0:00:00
Collecting pygments>=2.4.0
  Downloading Pygments-2.16.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.1 MB/s eta 0:00:00
Collecting stack-data
  Downloading stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting platformdirs>=2.5
  Downloading platformdirs-3.11.0-py3-none-any.whl (17 kB)
Collecting fastjsonschema
  Downloading fastjsonschema-2.18.1-py3-none-any.whl (23 kB)
Collecting jsonschema>=2.6
  Downloading jsonschema-4.19.1-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.3/83.3 kB 1.5 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting textwrap3>=0.9.2
  Downloading textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.1/137.1 kB 1.7 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 518.6 kB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.6-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.8/123.8 kB 1.5 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 1.3 MB/s eta 0:00:00
Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting attrs>=22.2.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2023.7.1-py3-none-any.whl (17 kB)
Collecting referencing>=0.28.4
  Downloading referencing-0.30.2-py3-none-any.whl (25 kB)
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.10.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.5 MB/s eta 0:00:00
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.8-py2.py3-none-any.whl (31 kB)
Collecting executing>=1.2.0
  Downloading executing-2.0.0-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Downloading asttokens-2.4.0-py2.py3-none-any.whl (27 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Installing collected packages: wcwidth, textwrap3, pure-eval, ptyprocess, pickleshare, find_libpython, fastjsonschema, executing, backcall, urllib3, traitlets, tqdm, tornado, tenacity, six, rpds-py, pyzmq, pyyaml, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, packaging, nest-asyncio, idna, entrypoints, decorator, debugpy, click, charset-normalizer, certifi, attrs, ansiwrap, requests, referencing, python-dateutil, matplotlib-inline, jupyter-core, jedi, comm, asttokens, stack-data, jupyter_client, jsonschema-specifications, jsonschema, ipython, nbformat, ipykernel, nbclient, papermill
Successfully installed ansiwrap-0.8.4 asttokens-2.4.0 attrs-23.1.0 backcall-0.2.0 certifi-2023.7.22 charset-normalizer-3.3.0 click-8.1.7 comm-0.1.4 debugpy-1.8.0 decorator-5.1.1 entrypoints-0.4 executing-2.0.0 fastjsonschema-2.18.1 find_libpython-0.3.0 idna-3.4 ipykernel-6.25.2 ipython-8.16.1 jedi-0.19.1 jsonschema-4.19.1 jsonschema-specifications-2023.7.1 jupyter-core-5.3.2 jupyter_client-8.3.1 matplotlib-inline-0.1.6 nbclient-0.8.0 nbformat-5.9.2 nest-asyncio-1.5.8 packaging-23.2 papermill-2.4.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 platformdirs-3.11.0 prompt-toolkit-3.0.39 psutil-5.9.5 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.30.2 requests-2.31.0 rpds-py-0.10.3 six-1.16.0 stack-data-0.6.3 tenacity-8.2.3 textwrap3-0.9.2 tornado-6.3.3 tqdm-4.66.1 traitlets-5.10.1 urllib3-2.0.6 wcwidth-0.2.8
[mojo] Testing: `mojo --help` [FAIL]
[mojo] Testing: `mojo run --help` [FAIL]
[mojo] Testing: `mojo build test_mandelbrot.mojo` [FAIL]
[mojo] Testing: `mojo build test_python.mojo` [FAIL]
[mojo] Testing: `mojo demangle` [FAIL]
[mojo] Testing: `mojo format` [FAIL]
[mojo] Testing: `mojo package` [FAIL]
[mojo] Testing: `mojo test_mandelbrot.mojo` [FAIL]
[mojo] Testing: `mojo test_python.mojo` [FAIL]
[mojo] Testing: `mojo repl` [FAIL]
[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.

🔥 Mojo installed! 🔥

Mojo's Python virtual environment created at /home/bill/.modular/pkg/packages.modular.com_mojo/venv

Now run the following commands if you are using bash:

echo 'export MODULAR_HOME="/home/bill/.modular"' >> ~/.bashrc
echo 'export PATH="/home/bill/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc

If you are using ZSH, run the following commands:

echo 'export MODULAR_HOME="/home/bill/.modular"' >> ~/.zshrc
echo 'export PATH="/home/bill/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc

Then enter 'mojo' to start the Mojo REPL.

For tool help, enter 'mojo --help'.
For more docs, see https://docs.modular.com/mojo.

bill@bill-debian:~$ echo 'export MODULAR_HOME="/home/bill/.modular"' >> ~/.bashrc
bill@bill-debian:~$ echo 'export PATH="/home/bill/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc
bill@bill-debian:~$ source ~/.bashrc
bill@bill-debian:~$ mojo
Illegal instruction

### System information

```shell
Debian 12
```

**Comment by ematejska** [comment] 2023-10-03 17:35
Debian is not officially supported yet.  Duplicate of: https://github.com/modularml/mojo/issues/637

**Closed by ematejska** 2023-10-03 17:35 UTC
Labels: bug, mojo

**Comment by dubyabondz** [comment] 2023-10-03 18:41
I would not write this off as an unsupported platform.  The Debian platform is what Ubuntu is based off of.  As far as support and functionality, if you work on Ubuntu, it doesn't make sense that you don't work on Debian.  Debian is also consistently more stable.  Please consider and I'll only reactivate once.

**Comment by Vasco10** [comment] 2023-10-04 14:47
I installed it manually - it works perfectly on Debian 12 (Virtual Machine). But you have to make sure that the conditions are fulfilled:

1. install Python3
2. install g++ (if not already installed)
3. curl https://get.modular.com | \
  MODULAR_AUTH=mut_73fed8baa98c4751908bb851b57b71f6 \
  sh -
4. ... (follow the instructions)

I'm following the documentation for the examples - using the REPL (it works fine).

**Comment by dubyabondz** [comment] 2023-10-05 19:43
Well, not sure what's happening.  I've tried a couple more times with the same results.  I've definitely followed the instructions and confirmed that the necessary packages are installed.  
One thing I will say for me was that I did have to perform the auth as the straight install failed when I didn't.  I also had to run the command with "sudo" for it to make any progress.
Error was the same each time on different VM instances.

Installing collected packages: wcwidth, textwrap3, pure-eval, ptyprocess, pickleshare, find_libpython, fastjsonschema, executing, backcall, urllib3, traitlets, tqdm, tornado, tenacity, six, rpds-py, pyzmq, pyyaml, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, packaging, nest-asyncio, idna, entrypoints, decorator, debugpy, click, charset-normalizer, certifi, attrs, ansiwrap, requests, referencing, python-dateutil, matplotlib-inline, jupyter-core, jedi, comm, asttokens, stack-data, jupyter_client, jsonschema-specifications, jsonschema, ipython, nbformat, ipykernel, nbclient, papermill
Successfully installed ansiwrap-0.8.4 asttokens-2.4.0 attrs-23.1.0 backcall-0.2.0 certifi-2023.7.22 charset-normalizer-3.3.0 click-8.1.7 comm-0.1.4 debugpy-1.8.0 decorator-5.1.1 entrypoints-0.4 executing-2.0.0 fastjsonschema-2.18.1 find_libpython-0.3.0 idna-3.4 ipykernel-6.25.2 ipython-8.16.1 jedi-0.19.1 jsonschema-4.19.1 jsonschema-specifications-2023.7.1 jupyter-core-5.3.2 jupyter_client-8.3.1 matplotlib-inline-0.1.6 nbclient-0.8.0 nbformat-5.9.2 nest-asyncio-1.5.8 packaging-23.2 papermill-2.4.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 platformdirs-3.11.0 prompt-toolkit-3.0.39 psutil-5.9.5 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.30.2 requests-2.31.0 rpds-py-0.10.4 six-1.16.0 stack-data-0.6.3 tenacity-8.2.3 textwrap3-0.9.2 tornado-6.3.3 tqdm-4.66.1 traitlets-5.11.2 urllib3-2.0.6 wcwidth-0.2.8
[mojo] Testing: `mojo --help` [FAIL]
[mojo] Testing: `mojo run --help` [FAIL]
[mojo] Testing: `mojo build test_mandelbrot.mojo` [FAIL]
[mojo] Testing: `mojo build test_python.mojo` [FAIL]
[mojo] Testing: `mojo demangle` [FAIL]
[mojo] Testing: `mojo format` [FAIL]
[mojo] Testing: `mojo package` [FAIL]
[mojo] Testing: `mojo test_mandelbrot.mojo` [FAIL]
[mojo] Testing: `mojo test_python.mojo` [FAIL]
[mojo] Testing: `mojo repl` [FAIL]
[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.

**Comment by Vasco10** [comment] 2023-10-07 11:14
After installing a new VM, here are the steps I used (DO some SNAPSHOTS in between, it save you a lot if time – many forget it):

`sudo apt update && sudo apt upgrade -y

sudo apt install python3-pip -y

sudo apt install g++

sudo apt install curl

sudo apt install apt-transport-https

curl https://get.modular.com | \
  MODULAR_AUTH=mut_73fed8baa98c4751908bb851b57b71f6 \
  sh -

modular install mojo



# test it, you get the REPL (to quit REPL use CTRL+D, to clear the REPL use CTRL+L
mojo


# paste these 2 lines (one after another) into the terminal to add them the bashrc, for configuring the Bash shell
echo 'export MODULAR_HOME="/home/user_name/.modular"' >> ~/.bashrc
echo 'export PATH="/home/user_name/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc


# you may restart your computer or type in the terminal this line
source ~/.bashrc`


Now it should work. At least it worked for me.

**Comment by Vasco10** [comment] 2023-10-07 11:16
- sudo apt update && sudo apt upgrade -y

- sudo apt install python3-pip -y

- sudo apt install g++

- sudo apt install curl

- sudo apt install apt-transport-https

- curl https://get.modular.com | \
  MODULAR_AUTH=mut_73fed8baa98c4751908bb851b57b71f6 \
  sh -

-  modular install mojo



# test it, you get the REPL (to quit REPL use CTRL+D, to clear the REPL use CTRL+L

- mojo


# paste these 2 lines (one after another) into the terminal to add them the bashrc, for configuring the Bash shell

- echo 'export MODULAR_HOME="/home/user_name/.modular"' >> ~/.bashrc

- echo 'export PATH="/home/user_name/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc


# you may restart your computer or type in the terminal this line

- source ~/.bashrc

**Comment by Vasco10** [comment] 2023-10-07 11:18
After installing a new VM, here are the steps I used (DO some SNAPSHOTS in between, it save you a lot if time – many forget it):

- sudo apt update && sudo apt upgrade -y

- sudo apt install python3-pip -y

- sudo apt install g++

- sudo apt install curl

- sudo apt install apt-transport-https

- curl https://get.modular.com | \
  MODULAR_AUTH=mut_73fed8baa98c4751908bb851b57b71f6 \
  sh -

-  modular install mojo



( test it, you get the REPL (to quit REPL use CTRL+D, to clear the REPL use CTRL+L )

- mojo


( paste these 2 lines (one after another) into the terminal to add them the bashrc, for configuring the Bash shell )

- echo 'export MODULAR_HOME="/home/user_name/.modular"' >> ~/.bashrc

- echo 'export PATH="/home/user_name/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc


( you may restart your computer or type in the terminal this line )

- source ~/.bashrc


Now it should work. At least it worked for me.
