### ISSUE TITLE
[BUG] SIMD[type,size].MAX_FINITE

### ISSUE THREAD

**Issue by rd4com** [modularml/mojo#3220] opened 2024-07-11 19:45 UTC
### Bug description

Hello, 
we were working on a PR (#3179 ) and had a small bug.
(ping to @laszlokindrat, as suggested)

```mojo
fn main():
    alias type = DType.uint16
    alias size = 8
    
    # Expected: True , Returned: False
    print(
        size <= SIMD[DType.uint8, 1].MAX_FINITE.__int__()
    )

    # Use-case: a constrained in SIMD.count:
    # constrained[
    #     size <= SIMD[type, 1].MAX_FINITE.__int__(),
    #     "size is above maximum finite value of uint16"
    # ]()
```
```mojo
    print(SIMD[DType.uint8, 1].MAX_FINITE.__int__()) #-1
```

### Steps to reproduce

Nothing special, the steps are in the description :+1: 

### System information

```shell
- Ubuntu 23.10
- mojo 2024.7.1105 (211527ca)
- modular 0.7.2 (d0adc668)
```

**Comment by martinvuyk** [comment] 2024-07-12 01:17
I think this is the same bug as in  #3065

**Comment by laszlokindrat** [comment] 2024-07-12 14:08
Indeed. Closing this as duplicate of #3065
> I think this is the same bug as in #3065

**Closed by laszlokindrat** 2024-07-12 14:08 UTC
Labels: bug, mojo-repo
