### ISSUE TITLE
[Feature Request] Format Strings

### ISSUE THREAD

**Issue by erogluegemen** [modularml/mojo#293] opened 2023-05-30 17:11 UTC
### Bug description

```
I have tried both ways but it does not work either way. I am also getting different types of errors on both.

Error 1:
error: Expression [68]:22:12: expected ')' in call argument list

Error 2:
error: Expression [69]:22:15: 'StringLiteral' value has no attribute
```

### Steps to reproduce

```python
let a: F32; let b: Int
a = 5.5
b = 5

print(f'{b}')  # error: Expression [68]:22:12: expected ')' in call argument list
print('{}'.format(b))  # error: Expression [69]:22:15: 'StringLiteral' value has no attribute 'format'
```

### System information

```shell
11:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
10:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
9:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
8:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
7:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
6:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
5:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
4:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
3:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
2:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podafcfda92_690f_452f_8a43_038e8cc0f0be.slice/cri-containerd-21cdde79fa16c1c1eb1eb291658758ed6540d8829bd413dd7be566e7aaaed0b2.scope
0::/
```

**Comment by Kratosix** [comment] 2023-06-01 18:56
This was requested and I think the team is working on it.
https://github.com/modularml/mojo/issues/86

**Comment by Mogball** [comment] 2023-09-29 22:08
Closing as dupe of https://github.com/modularml/mojo/issues/398

**Closed by Mogball** 2023-09-29 22:08 UTC
Labels: enhancement, mojo-lang, mojo
