### ISSUE TITLE
Input function[Feature Request]

### ISSUE THREAD

**Issue by srujanshenoy** [modularml/mojo#518] opened 2023-08-25 07:27 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

The `input()` function of python does not work in Mojo

### What is your motivation for this change?

The value to the user is that it makes Mojo more user-friendly for someone who has worked with python for any amount of time (like myself) and wants to switch to Mojo.

### Any other details?

Anything that is _commonly_ used in python.

**Comment by gryznar** [comment] 2023-08-25 07:39
I think that very useful fo Mojo developers will be stacktrace / compiler error :)

**Comment by gijswobben** [comment] 2023-09-07 20:01
Duplicate of #167

**Comment by Moosems** [comment] 2024-04-20 18:27
Not a duplicate, one is a request for a mojo implementation, one is a bug report

**Comment by ematejska** [comment] 2024-05-01 17:15
Agreed duplicate of Duplicate of [#167](https://github.com/modularml/mojo/issues/167)

**Closed by ematejska** 2024-05-01 17:15 UTC
Labels: enhancement, mojo, mojo-repo
