### ISSUE TITLE
[BUG]: Segfault when running python code from a parallelized 'fn'

### ISSUE THREAD

**Issue by suahelen** [modularml/mojo#1318] opened 2023-11-21 07:59 UTC
### Bug description

When running python code from a parallelized 'fn' a segmentation fault occurs

### Steps to reproduce

Minimal code to reproduce:
`main.mojo:`
```
from python.python import Python
from algorithm import parallelize

fn runParallel():
    try:
        let py= Python.import_module("runpystuff")
        _ = py.print_stuff()  # here the call runs fine 

        @parameter
        fn run(i: Int):
            try:
                    _ = py.print_stuff()
            except e:
                print(e)

        parallelize[run](2, 2)
    except e:
        print("error", e)


fn main():
    try:
        Python.add_to_path(".")
        runParallel()
    except e:
        print(e)
```
`runpystuff.py`:

```
def print_stuff():
    print("Hello")
```

This is the error message after the `parrallelize[run](2,2)`
```
[210602:210602:20231121,085613.808402:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808530:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808570:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808610:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808650:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808688:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808730:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808774:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808835:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808874:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808915:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.808955:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809017:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809058:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809099:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809139:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809179:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809218:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809276:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809316:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809354:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809394:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809433:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809473:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809513:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809554:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809595:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809638:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.809678:ERROR elf_dynamic_array_reader.h:64] tag not found
[210602:210602:20231121,085613.815110:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[210602:210602:20231121,085613.815141:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
#0 0x0000556bb9b7b997 (mojo+0x5c7997)
#1 0x0000556bb9b7956e (mojo+0x5c556e)
#2 0x0000556bb9b7c06f (mojo+0x5c806f)
#3 0x00007fc8bfea1520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
#4 0x00007fc8a059ebdd PyObject_GetAttrString /usr/local/src/conda/python-3.10.13/Objects/object.c:810:19
#5 0x00007fc7d400d804 
Segmentation fault
```

### System information

```shell
Ubuntu (WSL Windows 10)
mojo 0.5.0 (6e50a738)
modular 0.2.2 (95d42445)
```

**Comment by JoeLoser** [comment] 2024-09-13 19:10
Closing as a duplicate of another issue internally which indicates the Python interop is unsafe for anything other than thread 0 at the moment, so it will fail for parallel, async, etc.  It also doesn't respect the GIL at the moment which is a separate issue.

**Closed** 2024-10-02 23:26 UTC
Labels: bug, mojo, mojo-python-interop, crash, mojo-repo
