### ISSUE TITLE
[BUG]: Seg Fault sometimes when struct has Pointer[Self] parameter

### ISSUE THREAD

**Issue by KyleHassold** [modularml/mojo#1250] opened 2023-11-08 04:19 UTC
### Bug description

I am attempting to make a tensor class with backpropagation which requires pointers to 'parent' tensors. Unfortunately, I ran into a seg fault error when the class was compiled. The code runs fine if the parents variable is removed. Below is the code that fails:

```
from memory import memset_zero
@register_passable("trivial")
struct Tensor[T: DType = DType.float32]:
    var rank: Int
    var num_elements: Int
    var shape: Pointer[Int]
    var strides: Pointer[Int]
    var data: DTypePointer[T]
    var grad: DTypePointer[T]
    var parents: Pointer[Self]

    fn __init__(_rank: Int, _shape: Pointer[Int], _strides: Pointer[Int], _num_elements: Int) raises -> Self:
        let data = DTypePointer[T].alloc(_num_elements)
        memset_zero[T](data, _num_elements)

        let grad = DTypePointer[T].alloc(_num_elements)
        memset_zero[T](grad, _num_elements)

        return Tensor[T] {
            rank: _rank,
            num_elements: _num_elements,
            shape: _shape,
            strides: _strides,
            data: data,
            grad: grad,
            parents: Pointer[Self].get_null(),
        }
```

When I attempt to run a file with this struct in it, I get the following seg fault error:

[1508028:1508028:20231107,230917.962003:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1508028:1508028:20231107,230917.962075:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: /home/kyleh/.modular/pkg/packages.modular.com_mojo/bin/mojo /home/kyleh/Mojo/MojoTorch/MojoTorch/graph/Tensor.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo      0x0000556c44aefb97
1  mojo      0x0000556c44aed76e
2  mojo      0x0000556c44af026f
3  libc.so.6 0x00007ff0a834c520
4  mojo      0x0000556c45115754
5  mojo      0x0000556c44f27cda
6  mojo      0x0000556c46c157da
7  mojo      0x0000556c4611e405
8  mojo      0x0000556c4611d9b9
9  mojo      0x0000556c4611f53f
10 mojo      0x0000556c46b7be3b
11 mojo      0x0000556c4611f3e2
12 mojo      0x0000556c4611efc3
13 mojo      0x0000556c4611f7ff
14 mojo      0x0000556c462826bc
15 mojo      0x0000556c4611e202
16 mojo      0x0000556c4611ddef
17 mojo      0x0000556c4611f8af
18 mojo      0x0000556c450d9476
19 mojo      0x0000556c4611e202
20 mojo      0x0000556c4611ddef
21 mojo      0x0000556c4611f5ef
22 mojo      0x0000556c46c1cb71
23 mojo      0x0000556c4611ddd9
24 mojo      0x0000556c4611f53f
25 mojo      0x0000556c450ba56e
26 mojo      0x0000556c4611f3e2
27 mojo      0x0000556c4611efc3
28 mojo      0x0000556c4611f48f
29 mojo      0x0000556c450a94a9
30 mojo      0x0000556c4611f3e2
31 mojo      0x0000556c4611efc3
32 mojo      0x0000556c461238f2
33 mojo      0x0000556c46123d2e
34 mojo      0x0000556c4611beee
35 mojo      0x0000556c473f2b96
36 mojo      0x0000556c473f3221
37 mojo      0x0000556c473f5772
38 mojo      0x0000556c46098778
39 mojo      0x0000556c45020969
40 mojo      0x0000556c460981dd
41 mojo      0x0000556c46caf21a
42 mojo      0x0000556c46cb607c
43 mojo      0x0000556c46d40729
44 mojo      0x0000556c46d40999
45 mojo      0x0000556c46d3d704
46 mojo      0x0000556c46cb43f4
47 mojo      0x0000556c450194c4
48 mojo      0x0000556c44ab8496
49 mojo      0x0000556c44a9f48d
50 libc.so.6 0x00007ff0a8333d90
51 libc.so.6 0x00007ff0a8333e40 __libc_start_main + 128
52 mojo      0x0000556c44a9ea1e
Segmentation fault

Also, the reason I titled this as "Seg Fault sometimes" is because when I tested the follow code, it worked:

```
@register_passable("trivial")
struct Val:
    var val: Int
    var point: Pointer[Self]

    fn __init__(_val: Int, *_parents: Self) -> Self:
        return Self {
            val: _val,
            point: Pointer[Self].get_null()
        }
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
Windows Linux Subsystem on Windows 10 Pro with Ubuntu 22.04.2
I can provide more detail if needed
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.5.0 (6e50a738)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
```

**Comment by Mogball** [comment] 2023-11-09 01:34
thanks for the report! closing as dupe of [#435](https://github.com/modularml/mojo/issues/435)

**Closed by Mogball** 2023-11-09 01:34 UTC
Labels: bug, mojo-lang, mojo
