### ISSUE TITLE
[QoI] Terrible error message trying to convert a type to itself

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#209] opened 2023-05-20 04:45 UTC
Simple reproduction:

```mojo
struct ErrorReproducer:
    var data: UI32
    
    fn __init__(inout self):
        self.data = 0
        
    fn set_data(inout self, data: Int):
        self.data = UI32(data)
    
    fn __moveinit__(inout self, owned other: Self):
        self.data = other.data
        
    fn __copyinit__(inout self, other: Self):
        self.data = other.data

fn make_err[a: Int]() -> ErrorReproducer:
    var e = ErrorReproducer()
    e.set_data(a)
    return e

let a = make_err[Int(5)]()
print(a.data)
```
outputs
```
error: Expression [1]:36:25: no matching function in call to '__init__': 
    let a = make_err[Int(5)]()
                     ~~~^~~

/.modular/Kernels/mojo/Builtin/Int.mojo:17:5: candidate not viable: callee expects 0 arguments, but 1 was specified
    fn __init__() -> Int:
    ^

/.modular/Kernels/mojo/Builtin/Int.mojo:31:5: candidate not viable: argument #0 cannot be converted from 'Int' to 'scalar<si16>'
    fn __init__(value: __mlir_type.`!pop.scalar<si16>`) -> Int:
    ^

/.modular/Kernels/mojo/Builtin/Int.mojo:45:5: candidate not viable: argument #0 cannot be converted from 'Int' to 'scalar<si32>'
    fn __init__(value: __mlir_type.`!pop.scalar<si32>`) -> Int:
    ^

/.modular/Kernels/mojo/Builtin/Int.mojo:59:5: candidate not viable: argument #0 cannot be converted from 'Int' to 'scalar<si64>'
    fn __init__(value: __mlir_type.`!pop.scalar<si64>`) -> Int:
    ^

/.modular/Kernels/mojo/Builtin/Int.mojo:73:5: candidate not viable: argument #0 cannot be converted from 'Int' to 'index'
    fn __init__(value: __mlir_type.index) -> Int:
    ^

/.modular/Kernels/mojo/Builtin/Int.mojo:9:2: candidate not viable: argument #0 cannot be converted from 'Int' to 'scalar<index>'
@value
 ^
```

Note that sometimes I was able to make this work by restarting the kernel, but re-running a cell after calling it once would cause this issue to resurface.

**Comment by DayDun** [comment] 2023-05-20 04:57
`5` already has type `Int`, you don't need the `Int()` around it.

**Comment by lsh** [comment] 2023-05-20 04:59
Without the constructor it fails as well. It was just to be explicit for the example.

**Comment by lsh** [comment] 2023-05-20 05:00
Changing it to
```
let a = make_err[5]()
```
outputs
```
error: Expression [2]:36:24: ambiguous call to 'make_err', each candidate requires 0 implicit conversions, disambiguate with an explicit cast
    let a = make_err[5]()
            ~~~~~~~~~~~^~

Expression [2]:20:1: candidate declared here
fn make_err[a: Int]() -> ErrorReproducer:
^

Expression [1]:20:1: candidate declared here
fn make_err[a: Int]() -> ErrorReproducer:
^
```

**Comment by DayDun** [comment] 2023-05-20 05:06
Yeah `Int` has nothing to do with the underlying issue.

Smaller reproduction:
```py
struct Struct:
    fn __init__(inout self):
        pass

fn f() -> Struct:
    return Struct()

let a = f()
```
Running the above code in a blank notebook once works fine. But re-running the same block again yields the following error
```py
error: Expression [2]:23:14: ambiguous call to 'f', each candidate requires 0 implicit conversions, disambiguate with an explicit cast
    let a = f()
            ~^~

Expression [2]:9:1: candidate declared here
fn f() -> Struct:
^

Expression [1]:9:1: candidate declared here
fn f() -> Struct:
^
```

The issue is that the notebook remembers all previously defined functions and overloads them, which is often undesirable.

Here the functions also have exactly identical signatures, yet are treated as separate, which probably also shouldn't be the case.

**Comment by DayDun** [comment] 2023-05-20 05:10
Actually they do have different signatures. `Struct` is redefined when rerunning the cell, so the different signatures refer to different structs, just with the same name. That's why the issue only occurs when having a struct in the function signature.

**Comment by lattner** [comment] 2023-05-20 18:43
Well wait, there are two different things going on.  One is the redefinition issue in the notebook.  The original issue is simpler though, here's a reduction:

```
fn bad():
   _ = Int(5)
```

The issue is that 5 already has type Int, and Int has no conversion from Int.  I think this is desirable, but the error message is terrible.  I'll improve the QoI on the error message.

**Comment by lattner** [comment] 2023-05-20 18:45
The solution btw is to just use 5 instead of Int(5).  This will be a common mistake, I'll add a specific error with a fixit to remove the conversion this afternoon.

**Comment by DayDun** [comment] 2023-05-20 19:03
The reason I dismissed the `Int` issue was because I believe I spoke briefly with Lukas on Discord where he mentioned the "underlying issue" I highlighted, so I assumed that's what he intended to report. But I created a separate issue to avoid confusion now that this is an error message issue 🙂.

https://github.com/modularml/mojo/issues/219

**Comment by lattner** [comment] 2023-05-20 20:20
Cool, thanks @DayDun!  I'll fix the QoI (Quality of implementation) issue in the error message now

**Comment by lattner** [comment] 2023-05-20 21:58
fixed in the next update, we now produce an error `error: cannot construct 'Int' with itself, you can remove the constructor call`, and a bunch of the other conversion errors are also improved.  Thanks!

**Closed by lattner** 2023-05-20 21:58 UTC
Labels: bug
