### ISSUE TITLE
[mojo-stdlib] Implicit conversions between SIMD values can lose data

### ISSUE THREAD

**Issue by lattner** [modularml/mojo#3149] opened 2024-06-29 20:57 UTC
### Bug description

[Santiago](https://x.com/svpino) (@svpino) points out [on twitter](https://x.com/svpino/status/1807141992222363897)  that Mojo accepts code like this: `var b : Int64 = 1.67` even though we don't like implicit conversions that lose data.

I assume this is because we haven't adopted conditional conformances for the right initializers, is this possible to do now?

**Comment by msaelices** [comment] 2024-06-30 08:22
Could I work on this?

**Comment by soraros** [comment] 2024-07-14 15:36
Duplicate of #3065?

**Closed** 2024-07-17 22:40 UTC
Labels: bug, mojo-repo
