### ISSUE TITLE
[Modular CLI]: modular install mojo on ubu-20.04.6 failed

### ISSUE THREAD

**Issue by huide9** [modularml/mojo#877] opened 2023-09-21 21:58 UTC
### Issue description

By following instruction: https://developer.modular.com/download
after installed modular issue command `modular install mojo`, console returns below error message, any suggestions?  

P.S. same procedure on ubu-22.04 has no issues. 

```
root@stub-330:~# modular install mojo
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: modular install mojo
 #0 0x0000559789984567 (/usr/bin/modular+0x4ee567)
 #1 0x000055978998221e (/usr/bin/modular+0x4ec21e)
 #2 0x0000559789984c2f (/usr/bin/modular+0x4eec2f)
 #3 0x00007fda1faf9420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x000055978a9964a7 (/usr/bin/modular+0x15004a7)
 #5 0x000055978a995f85 (/usr/bin/modular+0x14fff85)
 #6 0x000055978a9971d5 (/usr/bin/modular+0x15011d5)
 #7 0x0000559789d6758d (/usr/bin/modular+0x8d158d)
 #8 0x0000559789d5df90 (/usr/bin/modular+0x8c7f90)
 #9 0x00005597899407b4 (/usr/bin/modular+0x4aa7b4)
#10 0x000055978993efe0 (/usr/bin/modular+0x4a8fe0)
#11 0x00007fda1f56d083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#12 0x000055978993e68e (/usr/bin/modular+0x4a868e)
Illegal instruction (core dumped)
root@stub-330:~# logout
(base) huide@stub-330:~$ uname -a
Linux stub-330 5.4.0-162-generic #179-Ubuntu SMP Mon Aug 14 08:51:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
(base) huide@stub-330:~$

```

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

follow the step describes in https://developer.modular.com/download: 

```
apt-get install -y apt-transport-https &&
  keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list &&
  apt-get update &&
  apt-get install -y modular

modular auth mut_48fd5d4151cd44779bcdb556c4ce436c &&
modular install mojo   (failed at here)
```

![image](https://github.com/modularml/mojo/assets/39502251/49fa1bec-875c-405e-9cd2-96d0db73cfa7)

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

(base) huide@stub-330:~$ modular -v
modular 0.1.4 (6b54d308)
```
- What OS did you install modular CLI on ?
`ubuntu 20.04.6`
```
(base) huide@stub-330:~$ uname -a
Linux stub-330 5.4.0-162-generic #179-Ubuntu SMP Mon Aug 14 08:51:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```

**Comment by smuniraj2018** [comment] 2023-09-22 05:11
Closing this as it is a duplicate of [iss677](https://github.com/modularml/mojo/issues/677)

**Closed by smuniraj2018** 2023-09-22 05:11 UTC
Labels: modular-cli
