### ISSUE TITLE
[Modular CLI]: Please follow the XDG base directory standard on Linux

### ISSUE THREAD

**Issue by gdonval** [modularml/mojo#1156] opened 2023-10-25 09:43 UTC
### Issue description

At the moment `modular` writes things in `$HOME/.modular` on Linux and does not follow the [XDG basedir specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

The problem is that it does not play well at all with Linux, preventing standard collective relocation of state through setting environment variables. `$HOME/.modular` **is** an arbitrary choice, XDG is a standard providing many advantages detailing how to do it properly.

Please add this to your roadmap. 

### Steps to reproduce

- Case 1 (default):
  
  Use the `modular` CLI tool and see `$HOME/.modular` being used and populated (the XDG specs mandates the use of different subfolders, `$HOME/.config` being the most appropriate "by default", if no specific env variable is set).

- Case 2 (OS-/user-wide config change):
  
  Set `$XDG_CONFIG_HOME` to any directory `$HOME/any/dir` and see `$HOME/.modular` being used and populated, disregarding collective configuration provided by the spec.

### Version Info

```shell
- v0.2.1
- Ubuntu 22.04
```

**Comment by rivy** [comment] 2023-10-27 15:23
Please follow the XDG standard on *all platforms* (not just Linux).

**Comment by lattner** [comment] 2023-10-28 05:41
@zbowling fyi

**Comment by zbowling** [comment] 2023-10-30 15:52
Duplicate of https://github.com/modularml/mojo/issues/739 

We will likely follow XDG standard at some point (only about half the Linux ecosystem of packages really does today), but we have to implement a way to migrate existing installs when we do. Some of our dependencies (eg parts of LLVM) also don't respect XDG and upstream still hasn't made it priority with some downstream distros maintaining their own patches. When we officially support more linux distros other than Debian based distros (mostly of which are still slowly migrating official packages to XDG specs) to support distros that are further down the path of full XDG spec adoption (like Arch linux), we will likely make it default.

There is a work around for now. You can set the MODULAR_HOME env to your XDG_STATE_HOME path, re-auth, and install there. 

```
export MODULAR_HOME="$XDG_STATE_HOME/modular"
modular auth ...
modular install ...
```

**Comment by gdonval** [comment] 2023-10-30 16:40
> only about half the Linux ecosystem of packages really does today

This is not a good excuse. Each one of them is a pain to work with, let's not make `modular` an extra one.

---

> There is a work around for now...

Not it is not. The standard mandates that `$XDG_STATE_HOME` (and co.) should inform the program about where to put things. A way to move things for this specific application is not what has been asked for.

---

> We will likely follow XDG standard at some point

Please add it to your roadmap so that it is not forgotten.

**Comment by zbowling** [comment] 2023-10-30 20:21
Unfortunately it's the only solution I can share today. It's a workaround that is similar to workarounds one can employ for a lot of packages that don't respect Free Desktop's XDG base dir and user dir specs today:
https://wiki.archlinux.org/title/XDG_Base_Directory#Partial

Right now, given this primarily affects Arch linux users where the home directory is by default is not writable and that Arch is not officially supported right now for us (only Ubuntu and Debian at the moment), and given there is a workaround for users on unsupported platforms, we likely won't prioritize full support of XDG until we later expand our Linux distro support given the engineering time to get there.

Freedesktop XDG base dir and user dir spec supporters have been fighting a bit of a 13 year long uphill battle to gain widespread adoption in the Linux ecosystem and Arch linux making it inconvenient to run software that doesn't implement it has been the only recent forcing function to gain more adoption of the spec in recent years. Right now there a lot dependencies, especially common ones in the compiler world, that still don't support it. Including a lot of LLVM based compiler tools and many other compiler suites (like Rust and Go) that still do not support XDG base dir spec at the moment.  

We hear you though and will get there. I can't give a timeline yet though.

**Comment by ematejska** [comment] 2024-10-14 19:03
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.

**Closed by ematejska** 2024-10-14 19:03 UTC
Labels: modular-cli, mojo-repo
