### ISSUE TITLE
[BETA]: `external_call` results in `error: existing function with conflicting signature`

### ISSUE THREAD

**Issue by modocache** [modularml/mojo#534] opened 2023-08-28 15:26 UTC
The following (reduced) program produces error messages that confused one of our Mojo users in the Discord, see messages [here](https://discord.com/channels/1087530497313357884/1116464685735223396/1145125922345844886) and [here](https://discord.com/channels/1087530497313357884/1145124809404072006/1145181844715872315):

```python
# stl.mojo
from memory.unsafe import Pointer

@value
@register_passable("trivial")
struct FILE:
    pass

fn fclose(arg: Pointer[FILE]) -> Int32:
    return external_call["fclose", Int32](arg)

fn main() raises:
    let res = fclose(Pointer[FILE]())
```

```
$ mojo run stl.mojo
stl.mojo:17:42: error: existing function with conflicting signature
    return external_call["fclose", Int32](arg)
                                         ^
/__w/modular/modular/Kernels/mojo/builtin/io.mojo:66:43: note: see function declaration here
stl.mojo:17:42: error: failed to legalize operation 'pop.external_call' that was explicitly marked illegal
    return external_call["fclose", Int32](arg)
                                         ^
stl.mojo:17:42: note: see current operation: %3 = "pop.external_call"(%0) {func = "fclose" : !kgen.string} : (!pop.pointer<struct<>>) -> !pop.scalar<si32>
```

FWIW, there is an instance of an external call to `fclose` in `builtin/io.mojo`. However, the error message complains of an existing function with a conflicting signature, and I don't think that makes sense here.

---

This occurs when using the documented instructions for running the Mojo SDK beta on GitHub Codespaces. `mojo --version` reports `mojo 0.2.0 (4c0ef274)`, `modular --version` reports `modular 0.1.2`.

**Comment by Mogball** [comment] 2023-08-28 15:59
Closing this as "intended behaviour". `external_call` will be replaced in the future with external function declarations.

**Closed by Mogball** 2023-08-28 15:59 UTC
