### ISSUE TITLE
[Modular CLI]: Fail to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by mccrow2018** [modularml/mojo#612] opened 2023-09-08 05:52 UTC
### Issue description

Following the website instruction, the installation stops in Ubuntu terminal after downloading the Modular CLI:
![1694152076985](https://github.com/modularml/mojo/assets/35625194/470d9a85-3079-499b-bb85-e744d8dd36ab)

Tried manual installation also failed:
![image](https://github.com/modularml/mojo/assets/35625194/944346c9-a4b0-411e-9f8c-661da2bfd4f2)

Pretty much the same scenario to https://github.com/modularml/mojo/issues/606.

Moreover, Dockerfile did not work neither.

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by slijirqqq** [comment] 2023-09-08 06:08
same problem on ubuntu `5.15.0-83-generic #92~20.04.1-Ubuntu x86_64 GNU/Linux`

**Comment by smuniraj2018** [comment] 2023-09-08 06:19
Thanks for reporting it. We will get back to you shortly.

**Comment by codingfun2022** [comment] 2023-09-08 06:25
Did you enable proxy for ``.modular.com``? In my case #606 , network proxy is the problem.

**Comment by slijirqqq** [comment] 2023-09-08 06:33
For me, the problem is solved when connecting to a VPN

**Comment by hotwa** [comment] 2023-09-08 06:37
Fail to install on Ubuntu 22.04 （wsl2） too

**Comment by MaKeSter333** [comment] 2023-09-08 06:41
too Ubuntu 22.04 WSL2

**Comment by hotwa** [comment] 2023-09-08 07:00
(base) root@PC-202308081033:~# curl -v https://get.modular.com | MODULAR_AUTH=mut_yourtoken sh -x -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 185.199.111.153:443...
* Connected to get.modular.com (185.199.111.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS header, Certificate Status (22):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.2 (IN), TLS header, Finished (20):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3972 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.2 (OUT), TLS header, Finished (20):
} [5 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=get.modular.com
*  start date: Aug 10 22:18:57 2023 GMT
*  expire date: Nov  8 22:18:56 2023 GMT
*  subjectAltName: host "get.modular.com" matched cert's "get.modular.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x556f895fe560)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
> GET / HTTP/2
> Host: get.modular.com
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [281 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [281 bytes data]
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
< HTTP/2 200
< server: GitHub.com
< content-type: text/html; charset=utf-8
< last-modified: Fri, 25 Aug 2023 14:55:16 GMT
< access-control-allow-origin: *
< etag: "64e8c0d4-c68"
< expires: Thu, 07 Sep 2023 16:28:15 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: BA6A:3F7F:6FB752:7D6261:64F9F7C7
< accept-ranges: bytes
< date: Fri, 08 Sep 2023 06:58:54 GMT
< via: 1.1 varnish
< age: 0
< x-served-by: cache-bur-kbur8200048-BUR
< x-cache: HIT
< x-cache-hits: 1
< x-timer: S1694156335.571507,VS0,VE95
< vary: Accept-Encoding
< x-fastly-request-id: 909ed72c2ad537240fea51c86c299dc93f37e5a2
< content-length: 3176
<
{ [841 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
100  3176  100  3176    0     0   3579      0 --:--:-- --:--:-- --:--:--  3584
* Connection #0 to host get.modular.com left intact
+ set -eu
+ [ 0 -ne 0 ]
+ [ xmut_1c95bb39be614674b33e31eea43ab7f9 = x ]
+ uname
+ [ Linux = Linux ]
+ [ -f /etc/debian_version ]
+ remote_script https://dl.modular.com/public/installer/setup.deb.sh
+ type curl
+ curl -1sLf https://dl.modular.com/public/installer/setup.deb.sh
+ maybe_sudo bash
+ whoami
+ [ root = root ]
+ bash
+ echo exit 1
(base) root@PC-202308081033:~# curl -1Lf https://dl.modular.com/public/installer/setup.deb.sh
curl: (22) The requested URL returned error: 403

**Comment by hotwa** [comment] 2023-09-08 07:01
download https://dl.modular.com/public/installer/setup.deb.sh fail

**Comment by hotwa** [comment] 2023-09-08 07:10
it's network problem.

**Comment by MaKeSter333** [comment] 2023-09-08 07:12
> it's network problem.
Need to use a VPN?

**Comment by hotwa** [comment] 2023-09-08 07:14
> > it's network problem.
> 
> Need to use a VPN?

maybe, I install sucessfully in my VPS .

**Comment by hotwa** [comment] 2023-09-08 07:15
![image](https://github.com/modularml/mojo/assets/49749136/2c3d5c94-2e9b-4947-b660-ab66933bf30e)

**Comment by hotwa** [comment] 2023-09-08 07:15
local failed in macos(M1, may not support) and windows 10(wsl2 ubuntu 22.04)

**Comment by LiuYuan-SHU** [comment] 2023-09-08 08:04
@hotwa I have succeeded installation on Mac M1. Could you describe your problem with more detail?

**Comment by hotwa** [comment] 2023-09-08 08:48
> @hotwa I have succeeded installation on Mac M1. Could you describe your problem with more detail?
curl https://get.modular.com | \
  MODULAR_AUTH=mut_\
  sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0   7970      0 --:--:-- --:--:-- --:--:--  8081
Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.

**Comment by LiuYuan-SHU** [comment] 2023-09-08 08:53
@hotwa  Directly install mojo on Mac M1 is not supported yet. You need to install it in a VSCode codespace and connect it to code mojo. Check [this](https://developer.modular.com/download) with option *set up on Mac*

**Comment by hotwa** [comment] 2023-09-08 08:54
codespace not runing on local machine？

**Comment by LiuYuan-SHU** [comment] 2023-09-08 08:55
No, it is running on cloud. Check [this](https://docs.github.com/en/codespaces/overview#what-is-a-codespace)

**Comment by hotwa** [comment] 2023-09-08 08:57
After having problems installing mojo on wsl2 on top of windows, I ported the script I downloaded from my VPS server.
![image](https://github.com/modularml/mojo/assets/49749136/f752f183-674e-4d9d-8081-eebedc8738d6)

**Comment by LiuYuan-SHU** [comment] 2023-09-08 09:03
I did not quite catch your point

**Comment by hotwa** [comment] 2023-09-08 09:05
![image](https://github.com/modularml/mojo/assets/49749136/ce429dce-334a-4001-9987-d9c189cdfe03)
it‘s running on cloud.

**Comment by hotwa** [comment] 2023-09-08 09:07
I want running on local machine, so I try install mojo on ubuntu 22.04(windows subsystem wsl2)

**Comment by LiuYuan-SHU** [comment] 2023-09-08 09:07
So you mean you installed it successfully on your cloud server?

**Comment by hotwa** [comment] 2023-09-08 09:08
yes, I install successfully on my VPS sever, I am not test it. it looks like install successfully.

**Comment by LiuYuan-SHU** [comment] 2023-09-08 09:10
That's strange. All colleagues around me who install mojo on local machines failed. It seems the best choice currently is to use a container

**Comment by hotwa** [comment] 2023-09-08 09:11
![image](https://github.com/modularml/mojo/assets/49749136/09027c40-0eac-402c-8748-fe64284fe7e6)

**Comment by hotwa** [comment] 2023-09-08 09:19
![image](https://github.com/modularml/mojo/assets/49749136/18dd7143-57a3-4251-9364-ffc514a61215)
It looks like the installation was successful, but it seems that mojo doesn't pass the hello-world test

**Comment by LiuYuan-SHU** [comment] 2023-09-08 09:25
@hotwa Which example code are you using?

**Comment by hotwa** [comment] 2023-09-08 09:46
> @hotwa Which example code are you using?
[here](https://docs.modular.com/mojo/manual/get-started/hello-world.html)

**Comment by LiuYuan-SHU** [comment] 2023-09-08 10:19
@hotwa Maybe you can open a new issue for that. It works on my platform

**Comment by mccrow2018** [comment] 2023-09-08 11:27
> Did you enable proxy for `.modular.com`? In my case #606 , network proxy is the problem.

Thanks, I have tried this method, still not working.

**Comment by mccrow2018** [comment] 2023-09-08 11:29
> Thanks for reporting it. We will get back to you shortly.

Thanks for your effort, keep me posted if you guys have any solution.

**Comment by tysonlind** [comment] 2023-09-08 21:41
trying to install modular so I can use it to install mojo, but I'm getting this error that the modular package is unable to be located after a successful installation following this command (running ubuntu 22.04.2 LTS on WSL2) :

  `curl https://get.modular.com | \
  MODULAR_AUTH=mut_2b79b8ed479f4e4b9132aebb06942a72 \
  sh -
  `
![image](https://github.com/modularml/mojo/assets/23481564/cc3fb00e-83aa-423a-989b-948bb7a99da3)

**Comment by mikeyinn** [comment] 2023-09-09 03:36
@mccrow2018

**Comment by mikeyinn** [comment] 2023-09-09 03:42
I tried yesterday and the same thing happened to me, and I fail many times. But today, all of sudden, it worked. i have no idea about what happened.

![56d180dcf4cdd2be4a15f18add3a85a](https://github.com/modularml/mojo/assets/9290955/abb91baf-370d-43a4-a49c-c2ec3e39590a)

![8249446ad91dd7e0961383e43426dcb](https://github.com/modularml/mojo/assets/9290955/9b77294e-7a3b-4e6c-8b18-bee47de770ef)
You may try again. Good luck!

**Comment by MaKeSter333** [comment] 2023-09-09 09:24
+ Problem fixed. Modular fixed the network

**Comment by bzcheeseman** [comment] 2023-09-19 16:58
Closing as it seems this is no longer an issue.

**Closed by bzcheeseman** 2023-09-19 16:58 UTC
Labels: modular-cli
