### ISSUE TITLE
[Modular CLI] Compatibility issue: Error reporting when installing Mojo in Rye-managed Python

### ISSUE THREAD

**Issue by hhstore** [modularml/mojo#1991] opened 2024-03-22 16:57 UTC
## Related: ([Rye](https://github.com/astral-sh/rye) Project)

- https://github.com/astral-sh/rye/issues/920

## Desc

- When I use [Rye](https://github.com/astral-sh/rye) to manage Python versions, I get an error when installing mojo.
- Switch to [Pyenv](https://github.com/pyenv/pyenv)` to manage the Python version, and install mojo without errors.

@zbowling 

## Could it be because mojo doesn't support rye? 

- not works for me. 
- This may be caused by me using [Rye](https://github.com/astral-sh/rye) (Python package management tool) to manage Python version numbers.   
- I seem to have encountered similar errors before.   
- Last time I switched to `Pyenv` (not `Rye`) to switch the `Python` version number, and then fixed the problem.   
- However, I think mojo needs to fix this error in order to support `rye`, which is also a popular Python package management tool lately.

## Env:

- `M1 Mac + macOS 12.4`
- [python rye](https://github.com/astral-sh/rye)

```ruby


❯ which python
/Users/dev/.rye/shims/python


❯ python -V
Python 3.12.2

```

## Error logs:

```ruby

modular clean && modular install mojo --force-cas

# Found release for https://packages.modular.com/mojo @ 24.1.1-0ab415f7-release
# Collecting necessary files...
[files    124/124][bytes    118MiB/118MiB @  10.5MiB/s][██████████████████████████████] 💯%
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Traceback (most recent call last):
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 67, in <module>
    main()
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 50, in main
    raise Exception(
Exception: Could not find libpython. Check your Python installation and ensure that $LD_LIBRARY_PATH includes the location to the installed Python library (e.g. /usr/lib/x86_64-linux-gnu).
modular: error: failed to run script
==========================
Failure Information:
	- Script: `PATH=/Users/dev/.pyenv/bin:/opt/homebrew/opt/llvm/bin:/Users/dev/.rye/shims:/Users/dev/google-cloud-sdk/bin:/Users/dev/Library/pnpm:/Users/dev/.cargo/bin:/Users/dev/Library/Caches/fnm_multishells/70445_1710899384616/bin:/Users/dev/.pyenv/shims:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/llvm/bin:/usr/local/bin:/Library/Apple/usr/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/Users/dev/bin:/Users/dev/.local/bin:/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin:/Applications/Little Snitch.app/Contents/Components:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:~/.fig/bin:~/.fnm:~/.cargo/bin:~/.local/bin:~/.yarn/bin:~/.pulumi/bin:/Users/dev/go/bin:~/sdk/android/emulator:~/sdk/android/tools:~/sdk/android/tools/bin:~/sdk/android/platform-tools:/Users/dev/Library/Android/sdk/emulator:/Users/dev/Library/Android/sdk/tools:/Users/dev/Library/Android/sdk/tools/bin:/Users/dev/Library/Android/sdk/platform-tools:/Users/dev/.gem/bin:/Users/dev/.modular/pkg/packages.modular.com_mojo/bin:~/.pyenv/bin:~/.pyenv/shims:~/.pyenv/plugins/pyenv-virtualenv/shims:/usr/local/share/dotnet/:/usr/local/share/dotnet//tools:/Users/dev/.pub-cache/bin:/Users/dev/.fvm/default/bin:/Users/dev/.fvm/default/bin/cache/dart-sdk/bin HOME=/Users/dev MODULAR_HOME=/Users/dev/.modular PYTHONPATH=/Users/dev/.modular/pkg/packages.modular.com_mojo/venv/lib/Users/dev/.modular/pkg/packages.modular.com_mojo/venv/bin/python /Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py -installer-outfile /var/folders/pc/78th99qs10zfzdx_r683t23w0000gn/T/modular-tool-script-redirect-7e8791.tmp`
	- Result: 1
	- Stderr:
Traceback (most recent call last):
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 67, in <module>
    main()
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 50, in main
    raise Exception(
Exception: Could not find libpython. Check your Python installation and ensure that $LD_LIBRARY_PATH includes the location to the installed Python library (e.g. /usr/lib/x86_64-linux-gnu).


==========================

```

## Related: 

- https://github.com/modularml/mojo/issues/706
- I looked at the `path` of the Python installed by `rye`, and found that it is here, and it is indeed different from the path of `pyenv`. (Mojo and pyenv work fine)

```ruby

$HOME/.rye/py/cpython@3.12.2

```

- I tried setting the following environment variables, but it didn't work.

```ruby
export LD_LIBRARY_PATH="/Users/dev/.rye/py/cpython@3.12.2/install/lib/"
export LD_LIBRARY_PATH="/Users/dev/.rye/py/cpython@3.12.2/lib/libpython3.12.dylib"
```

- `Python dir` diff: `pyenv` vs `rye`

<img width="500" alt="image" src="https://github.com/modularml/mojo/assets/3252130/07f522cf-3329-418c-bfcb-adbd69728820">

## Temporary Solution:  

- Use `pyenv` instead of `rye` to manage Python versions.

```ruby

❯ which python
/Users/dev/.pyenv/shims/python

~ on ☁️
❯ python --version | awk '{print $2}'
3.10.6

~ on ☁️
❯ modular clean && modular install mojo --force-cas
# Found release for https://packages.modular.com/mojo @ 24.1.1-0ab415f7-release
# Collecting necessary files...
[files    124/124][bytes    118MiB/118MiB @    21KiB/s][██████████████████████████████] 💯%
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...

🔥 Mojo installed! 🔥

Mojo's Python virtual environment created at /Users/dev/.modular/pkg/packages.modular.com_mojo/venv

If you are using ZSH (default on macOS), run the following commands:

echo 'export MODULAR_HOME="/Users/dev/.modular"' >> ~/.zshrc
echo 'export PATH="/Users/dev/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc

If you are using bash, run the following commands:

BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
echo 'export MODULAR_HOME="/Users/dev/.modular"' >> "$BASHRC"
echo 'export PATH="/Users/dev/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> "$BASHRC"
source "$BASHRC"

Then enter 'mojo' to start the Mojo REPL.

For tool help, enter 'mojo --help'.
For more docs, see https://docs.modular.com/mojo.


```

<img width="500" alt="image" src="https://github.com/modularml/mojo/assets/3252130/cebd96c8-e857-4d80-ba42-9bc8a49ec627">

### Steps to reproduce

- Under `rye` + `python3.12`, install `mojo`.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?



❯ modular --version
modular 0.5.2 (6b3a04fd)
```

**Comment by jackos** [comment] 2024-04-10 21:00
Hi @hhstore I've tried a bunch of ways to install Mojo with Rye nothing was working for me though, you need to use your system Python to install Mojo. You can use Rye for Mojo -> Python interop by setting PYTHONHOME to the location of the interpreter you're using e.g. `export PYTHONHOME=~/.rye/py/python...` and `export MOJO_PYTHON_LIBARY="$HOME"/.rye/py/python.../lib/libpython...so` replacing the 3 dots with your Python version.

**Comment by jackos** [comment] 2024-06-06 22:04
Hi @hhstore the above fix also works on installation with a rye managed python now for a future release (can test now with `modular install nightly/mojo` with:
```
export PYTHONHOME="/Users/jack/.rye/py/cpython@3.12.3"
export MOJO_PYTHON_LIBRARY="/Users/jack/.rye/py/cpython@3.12.3/lib/libpython3.12.dylib"
```
Closing this ticket as a duplicate of https://github.com/modularml/mojo/issues/1131, leaving that one open as I would like to support `rye` in the future without having to set these env vars.

**Closed by jackos** 2024-06-06 22:04 UTC
Labels: modular-cli, mojo-repo

**Comment by ezirayw** [comment] 2024-09-02 17:44
currently also using pyenv to manage python versions on my machine but I've been having issues installing mojo. I get the following error when installing mojo:
`modular: error: unable to bootstrap the TUF repository, missing bootstrap.json
`

Python information: `which python` shows the following path `/Users/ezirayimerwolle/.pyenv/shims/python` and currently using `Python 3.11.9`, which was set using the following command `pyenv global 3.11.9`

tried using `modular clean && modular install mojo --force-cas` to follow the above steps but it looks like modular no longer supports the command so im guessing there's some sort of issue of modular not finding my python path, not really sure. Any guidance would be appreciated since I want to continue using pyenv rather than re-installing a version of python outside of pyenv. If it helps, also using M1 MacBook Pro.
