### ISSUE TITLE
[BUG]: Accessing variable in uninitialized state does not produce in compile error

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#332] opened 2023-06-06 00:53 UTC
### Bug description

I don't know if it is intentional, or not, but code:

```python
let i: Int
print(i)
```
compiles fine and as a results gives: `22938856605`. I don't know if it is intentional, but it could result in very strange bugs. Much better will be just to raise error about trying to access not initialized variable. On Python 3.11 it gives:
`NameError: name 'i' is not defined. Did you mean: 'id'?`

**Comment by lattner** [comment] 2023-06-06 01:52
River, can you dupe this out?

**Comment by River707** [comment] 2023-06-12 17:44
Thanks for filing this. This is essentially a duplicate of #15, in that right now top-level variables are treated a bit specially by the notebook environment. Ensuring that these variables get persisted messes a bit with how analyses for initialization/mutability/etc is done.

**Closed** 2023-06-12 23:45 UTC
Labels: bug, notebook
