### ISSUE TITLE
[BUG] Parser crash on cache hit when importing from module with same name as stdlib module

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1065] opened 2023-10-17 17:13 UTC
### Bug description

I have a bug being triggered only when I'm in a specific directory.

By copying the source code somewhere else, the bug disapear. Coming back to my old directory and the bug comes back. It seems the mojo compilation step is not deterministic.

### Steps to reproduce
```
git clone -b trigger_expected_region_bug https://github.com/gabrieldemarmiesse/mojo-stdlib-extensions.git
cd mojo-stdlib-extensions
mojo run_all_tests.mojo
```

```
 ✘ ⚡  /projects/open_source/mojo-stdlib   trigger_expected_region_bug  mojo run_all_tests.mojo
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
[146820:146820:20231017,170438.671899:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[146820:146820:20231017,170438.671957:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      [1]    146818 IOT instruction (core dumped)  mojo run_all_tests.mojo
 ✘ ⚡  /projects/open_source/mojo-stdlib   trigger_expected_region_bug  cd ..
 ⚡  /projects/open_source  cp -r ./mojo-stdlib  ./mojo-stdlib2
 ⚡  /projects/open_source  cd mojo-stdlib2
 ⚡  /projects/open_source/mojo-stdlib2   trigger_expected_region_bug  mojo run_all_tests.mojo
Included from /projects/open_source/mojo-stdlib2/stdlib_extensions/pathlib/__init__.mojo:1:
/projects/open_source/mojo-stdlib2/stdlib_extensions/pathlib/_path.mojo:85:9: warning: unreachable code after return statement
        with self.open("r") as f:
        ^
/projects/open_source/mojo-stdlib2/stdlib_extensions/syscalls/filesystem.mojo:60:5: warning: unreachable code after if statement with then/else that do not fall through
    with c.Str(pathname) as pathname_as_c_str:
    ^
All tests passed! 🔥🎉🔥
 ⚡  /projects/open_source/mojo-stdlib2   trigger_expected_region_bug  cd ../mojo-stdlib
 ⚡  /projects/open_source/mojo-stdlib   trigger_expected_region_bug  mojo run_all_tests.mojo
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
[147015:147015:20231017,170635.112145:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[147015:147015:20231017,170635.112231:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      1.      2.      3.      4.      [1]    147013 IOT instruction (core dumped)  mojo run_all_tests.mojo
```

### System information

```shell
- What OS did you do install Mojo on ?
ubuntu 22.04 in docker under wsl2
- Provide version information for Mojo by pasting the output of `mojo -v`
0.4.0
- Provide Modular CLI version by pasting the output of `modular -v`
0.2.0
```

**Comment by gabrieldemarmiesse** [comment] 2023-10-17 18:24
I managed to investigate more and I found something really interesting! It crashes on the second run and the ones afterwards. Not on the first one. I managed to reproduce deterministally! :) 🎉 🔥 🎉 

Here is the code, it should crash every time!

```
$ git clone -b trigger_expected_region_bug https://github.com/gabrieldemarmiesse/mojo-stdlib-extensions.git
$ cd mojo-stdlib-extensions
$ mojo build run_all_tests.mojo

Included from /tmp/something/something/mojo-stdlib-extensions/stdlib_extensions/pathlib/__init__.mojo:1:
/tmp/something/something/mojo-stdlib-extensions/stdlib_extensions/pathlib/_path.mojo:85:9: warning: unreachable code after return statement
        with self.open("r") as f:
        ^
/tmp/something/something/mojo-stdlib-extensions/stdlib_extensions/syscalls/filesystem.mojo:60:5: warning: unreachable code after if statement with then/else that do not fall through
    with c.Str(pathname) as pathname_as_c_str:
    ^

$ mojo build run_all_tests.mojo
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
mojo: /__w/modular/modular/third-party/llvm-project/mlir/lib/IR/SymbolTable.cpp:137: mlir::SymbolTable::SymbolTable(mlir::Operation *): Assertion `inserted.second && "expected region to contain uniquely named symbol operations"' failed.
[149030:149030:20231017,182126.227707:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[149030:149030:20231017,182126.227788:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      1.      2.      [1]    149028 IOT instruction (core dumped)  mojo build run_all_tests.mojo
```

**Comment by Mogball** [comment] 2023-10-19 16:05
Are you able to provide a smaller repro, a standalone file perhaps?

**Comment by gabrieldemarmiesse** [comment] 2023-10-19 16:10
I'll try to do this sure :)

**Comment by gabrieldemarmiesse** [comment] 2023-10-19 16:57
It's difficult to get a smaller repro because as I remove files, the error message starts to change and is not deterministic (running the `mojo build` multiple times does not yield the same error message). 

After removing enough files, it's alternating between the error message mentionned here and the error message in this issue: https://github.com/modularml/mojo/issues/1052 . So maybe we should tackle https://github.com/modularml/mojo/issues/1052 first since it have a smaller repro? Afterwards I can try to give a smaller repro for this issue.

I'm sorry I can't help more, it's hard with error messages that are "flaky"

**Comment by Mogball** [comment] 2023-10-19 16:58
Okay, that information has actually been super helpful. I think I know what the issue is now, and it explains why the error messages are non-deterministic. Thanks for your help!

**Comment by Mogball** [comment] 2023-10-19 16:59
This is related to https://github.com/modularml/mojo/issues/972 which I was just looking at.

**Comment by gabrieldemarmiesse** [comment] 2023-10-19 17:00
I'm glad it helped! Godspeed!

**Comment by Mogball** [comment] 2023-11-08 02:26
Closing in favour of #1248

**Closed by Mogball** 2023-11-08 02:26 UTC
Labels: bug, mojo-lang, mojo
