### ISSUE TITLE
[Mojo] Installation problem

### ISSUE THREAD

**Issue by Zeffar** [modularml/mojo#2000] opened 2024-03-25 11:10 UTC
### Issue description

Error installing Mojo, pasting the full output below:

### Steps to reproduce

```
geo@pinkshroom:~$ modular install max
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
# Found release for https://packages.modular.com/max @ 24.1.1
# Downloading archive: packages/24.1.1/max-x86_64-unknown-linux-gnu-24.1.1.tar.gz
Done         [ ███████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%   1.36GiB/1.36GiB @  10.2MiB/s
# Extracting downloaded archives. 
# Extraction complete, setting configs...
# Configs complete, running post-install hooks...
[mojo][error] Mojo SDK post-install test "`mojo build test_mandelbrot.mojo`" failed:
SubprocessError: Command '/home/geo/.modular/pkg/packages.modular.com_max/bin/mojo build /home/geo/.modular/pkg/packages.modular.com_max/test/test_mandelbrot.mojo -o /tmp/tmpfhc6elt2/test_mandelbrot' returned non-zero exit status 1.
  stderr:
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 204, in test_mojo_build
    self.run_mojo(
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 192, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 180, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo build test_python.mojo`" failed:
SubprocessError: Command '/home/geo/.modular/pkg/packages.modular.com_max/bin/mojo build /home/geo/.modular/pkg/packages.modular.com_max/test/test_python.mojo -o /tmp/tmpfhc6elt2/test_python' returned non-zero exit status 1.
  stderr:
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 214, in test_mojo_build
    self.run_mojo(
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 192, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 180, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo repl`" failed:
SubprocessError: Command '/home/geo/.modular/pkg/packages.modular.com_max/bin/mojo repl --one-line-before-file settings set target.load-cwd-lldbinit false --one-line-before-file settings set plugin.process.gdb-remote.packet-timeout 60' returned non-zero exit status 127.
  stderr:
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo)
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 303, in test_mojo_repl
    raise SubprocessError(repl.returncode, " ".join(args), out, err)
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
modular: error: failed to run script
==========================
Failure Information:
        - Script: `PATH=/usr/local/cuda/bin:/home/geo/.local/bin:/home/geo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin HOME=/home/geo PYTHONPATH=/home/geo/.modular/pkg/packages.modular.com_max/venv/lib/home/geo/.modular/pkg/packages.modular.com_max/venv/bin/python /home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py --modular-home /home/geo/.modular --package-path /home/geo/.modular/pkg/packages.modular.com_max --mojo-config-section mojo-max`
        - Result: 1
        - Stderr:
[mojo][error] Mojo SDK post-install test "`mojo build test_mandelbrot.mojo`" failed:
SubprocessError: Command '/home/geo/.modular/pkg/packages.modular.com_max/bin/mojo build /home/geo/.modular/pkg/packages.modular.com_max/test/test_mandelbrot.mojo -o /tmp/tmpfhc6elt2/test_mandelbrot' returned non-zero exit status 1.
  stderr:
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 204, in test_mojo_build
    self.run_mojo(
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 192, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 180, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo build test_python.mojo`" failed:
SubprocessError: Command '/home/geo/.modular/pkg/packages.modular.com_max/bin/mojo build /home/geo/.modular/pkg/packages.modular.com_max/test/test_python.mojo -o /tmp/tmpfhc6elt2/test_python' returned non-zero exit status 1.
  stderr:
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 214, in test_mojo_build
    self.run_mojo(
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 192, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 180, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo repl`" failed:
SubprocessError: Command '/home/geo/.modular/pkg/packages.modular.com_max/bin/mojo repl --one-line-before-file settings set target.load-cwd-lldbinit false --one-line-before-file settings set plugin.process.gdb-remote.packet-timeout 60' returned non-zero exit status 127.
  stderr:
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo)
    /home/geo/.modular/pkg/packages.modular.com_max/bin/mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
  File "/home/geo/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 303, in test_mojo_repl
    raise SubprocessError(repl.returncode, " ".join(args), out, err)
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
```

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

modular -v
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular 0.5.2 (6b3a04fd)
```

- What OS did you install modular CLI on ?
```
OS: Fedora Linux 39 (KDE Plasma) x86_64 
Kernel: 6.7.6-200.fc39.x86_64
```
```

**Comment by jackos** [comment] 2024-06-06 22:08
Thanks very much for that @makism, will leave this open for people who want fedora support. The problem is missing required dynamic libraries

**Comment by jackos** [comment] 2024-06-06 23:04
Sorry there is a feature request to upvote for fedora support here: https://github.com/modularml/mojo/issues/2267

Closing this one but leaving link to workaround here: https://github.com/makism/mojo-on-fedora40

**Closed by jackos** 2024-06-06 23:04 UTC
Labels: mojo, mojo-repo, Initiative: Release Workflows
