### ISSUE TITLE
[BUG] Segfault when using FFI

### ISSUE THREAD

**Issue by fbreuer** [modularml/mojo#2812] opened 2024-05-24 09:51 UTC
### Bug description

Trying out the FFI interface, I get a segfault when calling a simple function.

Error is this. (Code below)

```
'/root/.modular/pkg/packages.modular.com_mojo/bin/mojo' '/home/project_02_ffi/demo.mojo'
about to call C...
[32899:32899:20240524,094759.370977:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[32899:32899:20240524,094759.371105:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: /root/.modular/pkg/packages.modular.com_mojo/bin/mojo /home/project_02_ffi/demo.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo            0x0000555dacaa5407
1  mojo            0x0000555dacaa325e
2  mojo            0x0000555dacaa5a9f
3  libpthread.so.0 0x00007fc58a5b2420
mojo crashed!
Please file a bug report.
Segmentation fault
```

I can confirm that `/sys/devices/system/cpu/cpu0/cpufreq` does not exist.

### Steps to reproduce

Code in `demo.c`

```c
double three_arg_max(double a, double b, double c) {
  if(a > b) {
    if (c > a) {
      return c;
    } else {
      return a;
    }
  } else {
    if (c > b) {
      return c;
    } else {
      return b;
    }
  }
}
```

Compile with

```bash
gcc -c demo.c -o demo.o
gcc demo.o -shared -o libdemo.so
```

Mojo code:

```
from sys import ffi

fn main():
    var lib = ffi.DLHandle("./libdemo.so")
    var func =  lib.get_function[fn(Float64,Float64,Float64)->Float64]("three_arg_max")

    print("about to call C...")

    var res = func(3.1,3.05,3.14159)

    print("finished calling C")

    print("result of call", res)
```

### System information

```shell
This is running inside a Ubuntu Docker container on an Intel Mac.
```

**Comment by ematejska** [comment] 2024-05-28 22:55
What version of the mojo compiler did you install (mojo -v)?  This doesn't reproduce with mojo 24.3.0 (9882e19d) or the latest nightly build (mojo 2024.5.2805 (87564503))

**Comment by ematejska** [comment] 2024-06-21 17:27
Closing this out due to a lack of additional information but please-reopen if this still reproduces for you.

**Closed by ematejska** 2024-06-21 17:28 UTC
Labels: bug, mojo-repo
