### ISSUE TITLE
[BUG] Mojo crashes when function loading on parameters in traits

### ISSUE THREAD

**Issue by YichengDWu** [modularml/mojo#3186] opened 2024-07-07 02:42 UTC
### Bug description

When there is function loading on parameters in a trait, defining a struct for that trait crashes mojo.

### Steps to reproduce

```mojo
trait Foo:
    fn get(self) -> Int:
        pass 
    fn get[idx:Int](self) -> Int:
        pass

@value
struct Bar(Foo):
    fn get(self) -> Int:
        return 0
        
    fn get[idx:Int](self) -> Int:
        return idx

```

### System information

```shell
The playground.
```

**Comment by ematejska** [comment] 2024-07-09 20:01
Crash I see with the latest nightly compiler:

```
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo bla.mojo
1.	Crash resolving decl body at loc("/Users/ewa/tmp/bla.mojo":8:8)
    >> struct Bar(Foo):
              ^........
    >>     fn get(self) -> Int:
    >>         return 0
    >>          
    >>     fn get[idx:Int](self) -> Int:
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo                     0x0000000104173bc4 llvm_strlcpy + 55076
1  mojo                     0x0000000104171f6c llvm_strlcpy + 47820
2  mojo                     0x0000000104174264 llvm_strlcpy + 56772
3  libsystem_platform.dylib 0x000000019ce1f584 _sigtramp + 56
4  mojo                     0x0000000104428fa8 __jit_debug_register_code + 77044
5  mojo                     0x00000001044cb1b8 __jit_debug_register_code + 741124
6  mojo                     0x000000010443ee40 __jit_debug_register_code + 166796
7  mojo                     0x000000010444b610 __jit_debug_register_code + 217948
8  mojo                     0x000000010444badc __jit_debug_register_code + 219176
9  mojo                     0x0000000104455258 __jit_debug_register_code + 257956
10 mojo                     0x0000000104455490 __jit_debug_register_code + 258524
11 mojo                     0x00000001040c0234
12 mojo                     0x00000001040d2080
13 mojo                     0x00000001040bae18
14 dyld                     0x000000019ca660e0 start + 2360
mojo crashed!
Please file a bug report.
[80864:1532532:20240709,155652.873002:WARNING in_range_cast.h:38] value -634136515 out of range
[80864:1532532:20240709,155652.887664:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)
zsh: segmentation fault  mojo bla.mojo
```

**Comment by ematejska** [comment] 2024-07-09 20:02
This is with nightly compiler: mojo 2024.7.905 (e860c551)

**Comment by ematejska** [comment] 2024-07-11 18:21
This is a duplicate of [https://github.com/modularml/mojo/issues/3097](https://github.com/modularml/mojo/issues/3097)

**Closed** 2024-07-11 18:21 UTC
Labels: bug, mojo-repo
