### ISSUE TITLE
[BUG]: Crash resolving decl body at loc ...

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1424] opened 2023-12-06 19:26 UTC
### Bug description

Some specific piece of code make the command `mojo build` crash. Even if the code is wrong, I would expect the compiler not to crash and to give an helpful error message instead.

### Steps to reproduce

Try to `mojo build` the following code snippet:

```python
@value
struct KeyValuePair[K: AnyType, V: AnyType](CollectionElement):
    var key: K
    var value: V
```
I get the following error message:

```
mojo: /__w/modular/modular/KGEN/lib/MojoParser/ASTType.cpp:218: bool M::KGEN::LIT::ASTType::isMovable(llvm::SMLoc, M::KGEN::LIT::SharedState &) const: Assertion `typeDecl && "expected a user type"' failed.
[225105:225105:20231206,182148.209875:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[225105:225105:20231206,182148.210143:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo build trying_stuff.mojo
1.      Crash resolving decl body at loc("/projects/open_source/mojo-stdlib-extensions/trying_stuff.mojo":2:1)
    >> struct KeyValuePair[K: AnyType, V: AnyType](CollectionElement):
       ^..............................................................
    >>     var key: K
    >>     var value: V
       ................<
 #0 0x000055c0defbfe17 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x605e17)
 #1 0x000055c0defbd9ee (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x6039ee)
 #2 0x000055c0defc04ef (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x6064ef)
 #3 0x00007f5e53116520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f5e5316a9fc pthread_kill (/usr/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f5e53116476 gsignal (/usr/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f5e530fc7f3 abort (/usr/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f5e530fc71b (/usr/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f5e5310de96 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000055c0df413a79 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa59a79)
#10 0x000055c0df433cd6 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa79cd6)
#11 0x000055c0df445b13 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa8bb13)
#12 0x000055c0df430769 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa76769)
#13 0x000055c0df434735 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa7a735)
#14 0x000055c0df449429 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa8f429)
#15 0x000055c0df449c26 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa8fc26)
#16 0x000055c0df3edae9 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa33ae9)
#17 0x000055c0df3ede5b (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xa33e5b)
#18 0x000055c0def7372f (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b972f)
#19 0x000055c0def75cfb (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5bbcfb)
#20 0x000055c0def707b9 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b67b9)
#21 0x000055c0def6f172 (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b5172)
#22 0x00007f5e530fdd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#23 0x00007f5e530fde40 __libc_start_main (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#24 0x000055c0def6e97e (/root/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b497e)
[1]    225103 IOT instruction (core dumped)  mojo build trying_stuff.mojo
```

### System information

```shell
- What OS did you do install Mojo on ?
Ubuntu 22.04
mojo -v
mojo 0.6.0 (d55c0025)
modular -v
modular 0.2.0 (355ea9c0)
```

**Comment by laszlokindrat** [comment] 2023-12-12 19:06
Thanks for opening the ticket! Looks like this is a duplicate of https://github.com/modularml/mojo/issues/1465, so I'm closing this in favor of that.

**Closed by laszlokindrat** 2023-12-12 19:06 UTC
Labels: bug, mojo-lang, mojo
