### ISSUE TITLE
[Request] Implement `__mod__` in `Int` when rhs is SIMD type

### ISSUE THREAD

**Issue by p88h** [modularml/mojo#1482] opened 2023-12-14 13:06 UTC
### Bug description

This code snippet:

```
fn main():
    let array = DTypePointer[DType.int32].alloc(1000000)
    let bug = 1000 % (array[0] | 1)
```

produces the following error

```
/__w/modular/modular/Kernels/mojo/builtin/simd.mojo:890:5: error: function has recursive call to 'always_inline' function
/__w/modular/modular/Kernels/mojo/builtin/simd.mojo:899:22: note: call here recurses
/__w/modular/modular/Kernels/mojo/builtin/simd.mojo:890:5: note: back to function here
mojo: error: failed to run the pass manager
pooh@RAPTOR:~/aoc2023$ 
```

### Steps to reproduce

- minimal repro case included in the description

### System information

```shell
- What OS did you do install Mojo on ?
Win11 / WSL2 / Ubuntu 23.04
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.0 (d55c0025)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by JoeLoser** [comment] 2023-12-15 22:52
I discussed this with @laszlokindrat offline and it's a stdlib issue (thanks for relabeling it).  The problem is that in the `Int` struct, we only have this overload defined:

```
fn __mod__(self, rhs: Int) -> Int
```

Note the `rhs` operand is of type `Int`.  In your case, `(array[0] | 1)` produces a `SIMD` type and I get the error:

```
invalid call to '__mod__': right side cannot be converted from 'SIMD[si32, 1]' to 'Int'
```

A workaround is to explicitly convert your right hand operand to an `Int` type for now like so:

```
let bug = 1000 % int(array[0] | 1)
```

This successfully compiles with the latest Mojo (and should work fine on v0.6.1 for example) that is scheduled to be released shortly.

**Comment by p88h** [comment] 2023-12-16 12:06
Thanks, yeah, i got a workaround by doing the conversion by hand, but that also required some additional workarounds, specifically, the original code used 64-bit unsigned int table; and the conversion to int messed that up since int, even if it's 64-bit, is signed, and `x%10 != x.to_int()%10` in such case. 

I replaced the types first, and simplified down to the basic 32-bit integer to ensure that's not caused by anything else. 
The errror was only gone after adding the int conversion.

**Comment by JoeLoser** [comment] 2023-12-19 17:43
Thanks for the follow-up.  I've reworded the GH issue since I'm not so sure it's a "bug" (since there just isn't an overload), but perhaps it would be nice to implement `%` operator on the `Int` type when the rhs side is a `SIMD` type.  WDYT @abduld @ConnorGray?

**Comment by JoeLoser** [comment] 2024-04-11 17:22
Fixed with https://github.com/modularml/mojo/commit/a78e5213294d2cd595cf0db0da10113dcbdc22cf

**Closed by JoeLoser** 2024-04-11 17:22 UTC
Labels: enhancement, mojo-stdlib, mojo
