### ISSUE TITLE
[BUG] Cannot access global variables?

### ISSUE THREAD

**Issue by abhinav-upadhyay** [modularml/mojo#94] opened 2023-05-11 06:37 UTC
## Bug Description
In the playground notebook, if I create a global variable (i.e. outside any function body) and try to access it within a function, it results in an `unknown declaration` error.

For Python compatibility, we should be able to read variables which are declared globally.

### Steps to Reproduce

Python example which doesn't work in notebook:
```python
x = 10
def foo():
    builtins = Python.import_module("builtins")
    builtins.print(x)
```

Gets an error:
```
error: Expression [1]:7:20: use of unknown declaration 'x'
    builtins.print(x)
```

### Context

```
11:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
10:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
9:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
8:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
7:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
6:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
5:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
4:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
3:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
2:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0e4b2ab8_1639_4d0f_a8f6_84aaa2d3ff95.slice/cri-containerd-77a567f8cbaa1f6febfd7ed4bfe2b2785b332b727b695e181156e6f7a4b00290.scope
0::/
```

**Comment by sa-** [comment] 2023-05-11 06:39
According to https://docs.modular.com/mojo/get-started.html#caveats

> You can’t use global variables inside functions - they’re only visible to other global variables

**Comment by abhinav-upadhyay** [comment] 2023-05-11 06:42
Looks like I missed that. I will close this then.

**Comment by nevdelap** [comment] 2023-05-11 06:45
The not working fn is by design, but the not working def is still a bug, no?

Le jeu. 11 mai 2023, 4:42 PM, Abhinav Upadhyay ***@***.***> a
écrit :

**Comment by sa-** [comment] 2023-05-11 06:50
That's a good point! Maybe worth reopening @abhinav-upadhyay :)

**Comment by abhinav-upadhyay** [comment] 2023-05-11 06:55
Reopened, I removed the part about not working inside mojo `fn` functions.

**Comment by Mogball** [comment] 2023-05-11 13:11
This is a caveat for both `def` and `fn` because Mojo as a language doesn't actually have proper global variables (yet). This is a known missing feature. I will close this for now. Thanks for filing though!

**Closed by Mogball** 2023-05-11 13:11 UTC
Labels: bug
