### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by faddy19** [modularml/mojo#1097] opened 2023-10-19 21:45 UTC
### Bug description

I tried installing Mojo on my MacOS M1 Max and it failed. 
I am following exactly the installation guide. 
I included a screenshot from Terminal.

Error says 

modular: The arm64 architecture is required for this software.
Error: modular: An unsatisfied requirement failed this build.

I could not install it for MACOS. Please fix it. 

### Steps to reproduce
<img width="526" alt="Bildschirmfoto 2023-10-19 um 23 47 00" src="https://github.com/modularml/mojo/assets/51141314/0c08d1d2-751c-4923-97ad-832d89c670c3">

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
Mac Sonoma 14.1
- Provide version information for Mojo by pasting the output of `mojo -v`
I could not install it. It fails
- Provide Modular CLI version by pasting the output of `modular -v`
I am getting the following error:
modular: The arm64 architecture is required for this software.
Error: modular: An unsatisfied requirement failed this build.
```

**Comment by jackos** [comment] 2023-10-19 21:51
Duplicate of https://github.com/modularml/mojo/issues/1089

**Closed by jackos** 2023-10-19 21:51 UTC
Labels: bug, mojo
