### ISSUE TITLE
Archlinux support

### ISSUE THREAD

**Issue by amirhossein-fzl** [modularml/mojo#624] opened 2023-09-08 09:07 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Please add support for Arch Linux. Thanks 🙏❤️

### What is your motivation for this change?

The larger the community, the more users

**Comment by nmrtv** [comment] 2023-09-08 09:23
Duplicate of #572

**Closed** 2023-09-08 19:52 UTC
Labels: enhancement, mojo-tooling, mojo
