### ISSUE TITLE
[BUG] Values get set to 1 when passing one Scalar into another Scalar's constructor

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3058] opened 2024-06-15 20:07 UTC
### Bug description

```mojo
fn main():
    var n64 = UInt64(100)
    var n32 = UInt32(100)
    var n16 = UInt16(100)
    var n8 = UInt8(100)
 
    print(UInt64(n64))
    print(UInt64(n32))
    print(UInt64(n16))
    print(UInt64(n8))
 
    print(UInt32(n64))
    print(UInt32(n32))
    print(UInt32(n16))
    print(UInt32(n8))
 
    print(UInt16(n64))
    print(UInt16(n32))
    print(UInt16(n16))
    print(UInt16(n8))
 
    print(UInt8(n64))
    print(UInt8(n32))
    print(UInt8(n16))
    print(UInt8(n8))
 
    print(Int64(n64))
    print(Int64(n32))
    print(Int64(n16))
    print(Int64(n8))
 
    print(Int32(n64))
    print(Int32(n32))
    print(Int32(n16))
    print(Int32(n8))
 
    print(Int16(n64))
    print(Int16(n32))
    print(Int16(n16))
    print(Int16(n8))
 
    print(Int8(n64))
    print(Int8(n32))
    print(Int8(n16))
    print(Int8(n8))
```

### Steps to reproduce

* Include relevant code snippet or link to code that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
* Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
`2024.6.1305`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by soraros** [comment] 2024-06-15 20:10
Duplicate of #2860.

**Comment by JoeLoser** [comment] 2024-06-15 20:16
FYI @laszlokindrat @ConnorGray @bethebunny

**Comment by soraros** [comment] 2024-06-17 23:37
This is not just confusing but actively harmful.

Much code in `math` uses the following pattern:

```mojo
fn f(a: SIMD, ...) -> SIMD[res_type, ...]:
  ...
  fn _float32_dispatch(): ...
  fn _float64_dispatch(): ...

  if type is DType.float32:
    return _simd_apply[_float32_dispatch](a, ...).cast[res_type]()
  ...
```

With the implicit conversion to `Bool`, the compiler no longer able to warn us if the final `cast` is missing, which is dangerous and not at all obvious to see (it's no longer a matter of avoiding direct constructors call like `Int64(n)`).

**Comment by ematejska** [comment] 2024-06-20 23:38
@joe Do you want to keep this around for for the math module issue or dup out to [https://github.com/modularml/mojo/issues/3045](https://github.com/modularml/mojo/issues/3045)?

**Comment by JoeLoser** [comment] 2024-06-20 23:42
Closing as duplicate of [https://github.com/modularml/mojo/issues/3045](https://github.com/modularml/mojo/issues/3045) is fine by me.

**Closed** 2024-06-20 23:42 UTC
Labels: bug, mojo-repo
