### ISSUE TITLE
[BUG]: unexpected behaviors on pressing arrow keys (left, right, up, down) in mojo REPL environment. 

### ISSUE THREAD

**Issue by Suman196pokhrel** [modularml/mojo#662] opened 2023-09-09 06:06 UTC
### Bug description

Inside mojo REPL, I tried using arrow keys to move the cursor, but instead of moving the cursor, characters like `^[[D^[[A^[[C^[[B` came up.

pressing left = ^[[D
up = ^[[A
right = [[C^
down = [[B

I then exited Mojo and checked my CLI using other commands, it was working fine . But Mojo gave me weird characters.

https://github.com/modularml/mojo/assets/50728029/d61f7d92-9311-4735-9aee-61093e8dc310

### Steps to reproduce

- Run `mojo` in the command line
- Just use left and right arrows or type any word and try to navigate using the arrow keys

### System information

```shell
- I am running mojo inside Ubuntu, using wsl2 on Windows 11
- mojo 0.2.1 (64d14e85)
- modular 0.1.4 (6b54d308)
```

**Comment by SimplyYummy** [comment] 2023-09-09 08:44
Yep I have the same issue to on ubuntu through ssh. Its looks due to an issue with the REPL (Read-Eval-Print Loop) for Mojo as it doesn't handle ANSI escape sequences sent by the arrow keys properly at the moment. These escape sequences are what your terminal sends when you press special keys like the arrow keys. 

I tried using tmux terminal emulator instead of the default but still the same for me. So I believe its a mojo repl issue but I cant confirm with my limited setup

**Comment by ematejska** [comment] 2023-09-11 16:07
Maybe a duplicate of https://github.com/modularml/mojo/issues/575?

**Comment by River707** [comment] 2023-09-12 17:33
Yep, closing this one in favor of tracking via #575.

Thanks for filing this!

**Closed by River707** 2023-09-12 17:33 UTC
Labels: bug, mojo-tooling, mojo
