### ISSUE TITLE
[BUG]: Variable declarations don't work outside "with open" block

### ISSUE THREAD

**Issue by 0element1** [modularml/mojo#1049] opened 2023-10-13 02:22 UTC
### Bug description

...

### Steps to reproduce

# Use of unknown declaration 'content', 'fn' declarations require explicit variable declarations

<img width="700" alt="image" src="https://github.com/modularml/mojo/assets/114811938/66d89a63-11fb-40cb-b912-67d3ee80b005">

The following code should be able to find `content` declaration inside "with open" block.

### System information

```shell
OS: Windows 11, 
Subsystem: Ubuntu 22.04.2 LTS
Tools: VScode server
Mojo version: mojo 0.4.0 (9e33b013)
Modular CLI version: modular 0.1.4 (6b54d308)
```

**Comment by Mogball** [comment] 2023-10-16 18:48
Closing this as intended behaviour

**Closed by Mogball** 2023-10-16 18:48 UTC
Labels: bug, mojo-lang, mojo
