### ISSUE TITLE
[BUG]: bfloat16 cast fails

### ISSUE THREAD

**Issue by jon-chuang** [modularml/mojo#1297] opened 2023-11-15 17:58 UTC
### Bug description

```
[User] error: Couldn't lookup symbols:
  __truncsfbf2
```

### Steps to reproduce

Repro

```python
from random import rand
let image = rand[DType.float32](10)
a = image.data().simd_load[1]().cast[DType.bfloat16]()
```

### System information

```shell
- What OS did you do install Mojo on ? Ubuntu 22.04
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 0.5.0 (6e50a738)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.2.1 (5144fffe)
```

**Comment by willghatch** [comment] 2023-11-21 17:54
I failed to reproduce this on MacOS. I'll try again later on Ubuntu.

**Comment by jon-chuang** [comment] 2023-11-21 17:58
`__truncsfbf2` is an x86 symbol. Are you using ARM Mac?

**Comment by jon-chuang** [comment] 2023-11-21 18:06
Possibly related: https://github.com/JuliaLang/julia/issues/52067

**Comment by Sharktheone** [comment] 2023-11-21 19:32
I also can't reproduce this. In the repl I get this:

<details>
(SIMD[bf16, 1]) a = {
  (scalar<bf16>) value = {
    (bf16) [0] = 1.5068
  }
}
(Tensor[f32]) image = {
  (TensorSpec) _spec = {
    (TensorShape) shape = {
      (_TensorShapeStorage) _rep = {
        (DTypePointer[invalid]) ptr = {
          (pointer<scalar<invalid>>) address = 0x000000000000000a
        }
        (SIMD[si64, 1]) idx = {
          (scalar<si64>) value = {
            (si64) [0] = 4756083780991582208
          }
        }
      }
    }
  }
  (DTypePointer[f32]) _ptr = {
    (pointer<scalar<f32>>) address = 0x000055c49a85f830
  }
}

</details>

and when i run it in a file, i also doesn't give me an error.
Note, that i've added `let` before `a`

**Comment by jon-chuang** [comment] 2023-11-21 19:38
I get the error regardless of let

```
Expressions are delimited by a blank line.
Type `:quit` to exit the REPL and `:mojo help` for further assistance.

  1> from random import rand 
  2. let image = rand[DType.float32](10) 
  3. let a = image.data().simd_load[1]().cast[DType.bfloat16]()
[User] error: Couldn't lookup symbols:
  __truncsfbf2
```

**Comment by jon-chuang** [comment] 2023-11-21 19:39
Maybe it's the clang/LLVM version on my machine?

**Comment by Sharktheone** [comment] 2023-11-21 19:44
Hmm, it seems like, you don't have the newest version of modular installed. Can you update it and reinstall mojo? I don't really think that is fixing that, but it was at leased tried then.

**Comment by willghatch** [comment] 2023-11-21 20:17
OK, I spun up an Intel Ubuntu VM and was able to reproduce this in the repl but not in a file.  We'll look into this.

**Comment by Sharktheone** [comment] 2023-11-21 20:21
Interesting though I couldn't reproduce this. This might be for the same reason it also doesn't fail on MacOS. Might be depending on some CPU features

**Comment by jon-chuang** [comment] 2023-11-21 20:23
> was able to reproduce this in the repl but not in a file. 

FWIW, I also got the error on file.

**Comment by jon-chuang** [comment] 2023-11-21 20:27
Hmm, weird, when I run on file, it prints nothing.

```python
def main():
    from random import rand
    let image = rand[DType.float32](10)
    let a = image.data().simd_load[1]().cast[DType.bfloat16]()
    print(a, "something")  # prints ' something'
```

**Comment by HJLebbink** [comment] 2024-01-28 18:40
On mojo 0.7.0 (af002202) I get the same error: 

```python
from random import rand

fn main():
    let image = rand[DType.float32](10)
    let a = image.data().simd_load[1]().cast[DType.bfloat16]()
    let b = a.cast[DType.float32]()
    print(str(b))
```
gives: 

``` 
JIT session error: Symbols not found: [ __truncsfbf2 ]
mojo: error: Failed to materialize symbols: { (exec, { main }) }
```

**Comment by River707** [comment] 2024-03-28 01:14
This should be fixed in the next release!

**Closed by River707** 2024-03-28 01:14 UTC
Labels: bug, mojo-tooling, mojo
