### ISSUE TITLE
[BUG]: Unexpected keyword argument in pandas

### ISSUE THREAD

**Issue by ThirstB1ood** [modularml/mojo#1014] opened 2023-10-08 13:50 UTC
### Bug description

error: Expression [19]:1:15: invalid call to '__call__': unexpected keyword argument: 'columns'
X, y = df.drop(columns=['price']), df.price
       ~~~~~~~^~~~~~~~~~~~~~~~~~~

Expression [0]:1:1: function declared here
var __lldb_repl_python__ = __mojo_repl_Python()
^

expression failed to parse (no further compiler diagnostics)

### Steps to reproduce

from python import Python

let pd = Python.import_module("pandas")

var df = pd.read_csv('data.csv')
X, y = df.drop(columns=['price']), df.price

### System information

```shell
- What OS did you do install Mojo on ? MacOS
- Provide version information for Mojo by pasting the output of `mojo -v` 0.4.0
- Provide Modular CLI version by pasting the output of `modular -v` 0.2.0
```

**Comment by gryznar** [comment] 2023-10-08 18:31
Please add relevant title ater "[BUG]:"

**Comment by gryznar** [comment] 2023-10-09 14:33
Have you managed to do that in global scope? I would suggest to try:
```mojo
from python import Python

fn main() raises:
    let pd = Python.import_module("pandas")
    var df = pd.read_csv('data.csv')
    X, y = df.drop(columns=['price']), df.price
```

**Comment by jackos** [comment] 2023-10-19 21:50
Duplicate of https://github.com/modularml/mojo/issues/964

**Closed by jackos** 2023-10-19 21:50 UTC
Labels: bug, mojo, mojo-python-interop
