### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by ivyy** [modularml/mojo#745] opened 2023-09-12 09:33 UTC
### Issue description

hello, I've got a issue when intalling mojo.  my environment is wsl2 (ubuntu 22.0.4).  when I run "modular install mojo", everything goes well except that it gets stuck at this step:

* `/home/bigfish/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK

^C
bigfish:~$ TEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/home/bigfish/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/bigfish/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/bigfish/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 275, in test
    self.test_mojo_repl()
  File "/home/bigfish/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 185, in test_mojo_repl
    out_data, err_data = repl.communicate(
  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2021, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
^C

Please help.

### Steps to reproduce

just run "modular install mojo" and the issue occurs.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?

I'm using modular 0.1.4, windows 10 wsl2 with ubuntu 22.0.4
```

**Comment by drunkwcodes** [comment] 2023-09-12 11:04
Duplicate of #538.

**Comment by ivyy** [comment] 2023-09-13 02:11
thanks, it solves my issue. I thought my wls vesion 2 but actually version 1. By reinstalling the ubuntu 22.0.4 with wsl2, everything goes well!

**Comment by jackos** [comment] 2023-09-13 04:05
Thanks @drunkwcodes!

**Closed by jackos** 2023-09-13 04:05 UTC
Labels: modular-cli
