### ISSUE TITLE
[BUG]: the DType UI32 (unsigned integer) is returning signed value of negative integer

### ISSUE THREAD

**Issue by Alex19578** [modularml/mojo#281] opened 2023-05-29 01:36 UTC
### Bug description

```shell
var x:UI32 = -5
print("the unsigned value of x is : " ,x)

#output

the unsigned value of x is :  -5

the code returned the negative integer value but it should return an unsigned (positive value)
```

### Steps to reproduce

```shell
ui32 = ui32 Represents an unsigned integer type whose bitwidth is 32. is not returning the unsigned integer value 

var x:UI32 = -5
print("the unsigned value of x is : " ,x)

#output

the unsigned value of x is :  -5
```

### System information

```shell
11:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
10:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
9:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
8:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
7:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
6:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
5:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
4:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
3:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
2:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd782b7f_54df_4a67_b334_c19d602e62a9.slice/cri-containerd-708e01e4911801c714306f8336958bea6b4bcac36bf741b60e7507bb6f46d53c.scope
0::/
```

**Comment by abhinav-upadhyay** [comment] 2023-05-29 05:05
`UI32` is an alias for SIMD[ui32, 1]. So it is not really an unsigned int but a simd vector of size 1. 

When you print it as it is, I am not sure how is it being interpreted (maybe the `__str__` impl of this type is always reading the bits as a 2's complement signed int).

However, if you do this
```python
var x: UI8 = -1
print(x.to_int())
``` 

You will see the output as `255`. Which suggests that UI8 is indeed an unsigned integer and when you go below 0, it overflows.

**Comment by Mogball** [comment] 2023-06-05 20:38
Duplicate of https://github.com/modularml/mojo/issues/318

**Closed by Mogball** 2023-06-05 20:38 UTC
Labels: bug
