### ISSUE TITLE
[BUG]: Can't debug inside vscode

### ISSUE THREAD

**Issue by felixf4xu** [modularml/mojo#1570] opened 2023-12-28 00:49 UTC
### Issue description

I can't start debugging inside vscode using mojo extention

### Steps to reproduce

when I start debugging inside vscode, I got this:
>Running initCommands:
(lldb) settings set target.show-hex-variable-values-with-leading-zeroes false
(lldb) settings set target.process.optimization-warnings false
(lldb) plugin load '/home/cc/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git'
(lldb) command script import /home/cc/.modular/pkg/packages.modular.com_mojo/lib/lldb-visualizers/lldbDataFormatters.py
error: module importing failed: This script interpreter does not support importing modules.
(lldb) command script import /home/cc/.modular/pkg/packages.modular.com_mojo/lib/lldb-visualizers/mlirDataFormatters.py
error: module importing failed: This script interpreter does not support importing modules.

### Version Info

```shell
modular 0.3.1 (589ce200)

mojo 0.6.1 (876ded2e)

Ubuntu 22, with Python 3.10.12

which mojo
/home/cc/.modular/pkg/packages.modular.com_mojo/bin/mojo

which lldb
/home/cc/.modular/pkg/packages.modular.com_mojo/bin/lldb
```

**Comment by samufi** [comment] 2024-01-03 15:09
Potential duplicate of #1466.

**Comment by River707** [comment] 2024-01-11 18:44
Yep, thanks, marking this as a duplicate of #1466 !

**Closed by River707** 2024-01-11 18:44 UTC
Labels: mojo-tooling, mojo
