### ISSUE TITLE
[BUG] Python import not working - Linux|Conda

### ISSUE THREAD

**Issue by Levinin** [modularml/mojo#3259] opened 2024-07-16 20:11 UTC
### Bug description

Trying to import with Python package fails.
I'm running on Linux with Conda, running the python interpreter find script from the website finds the correct environment at the top of the list. The code compiles but segfaults. Running with mojo gives the following. As you can see, I have cut this back to the very minimum that fails. Mojo only code compiles and runs correctly.

### Steps to reproduce

Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo try.mojo
#0 0x000055cd7dd41438 (/home/u/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x12a1438)
#1 0x000055cd7dd3f25e (/home/u/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x129f25e)
#2 0x000055cd7dd41acd (/home/u/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x12a1acd)
#3 0x000071972dc42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
mojo crashed!
Please file a bug report.
Segmentation fault (core dumped)

```
from python import Python
fn main() raises:
    Python.add_to_path(".")
```

Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo try.mojo
#0 0x00005c84e1d93438 (/home/u/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x12a1438)
#1 0x00005c84e1d9125e (/home/u/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x129f25e)
#2 0x00005c84e1d93acd (/home/u/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x12a1acd)
#3 0x00007a8dc8e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
mojo crashed!
Please file a bug report.
Segmentation fault (core dumped)

```
from python import Python
fn main() raises:
    var pd = Python.import_module("pandas")
```

### System information

```shell
Linux Ubuntu 22.04
Conda environment
mojo 24.4.0 (2cb57382)
modular 0.8.0 (39a426b5)
```

**Comment by ematejska** [comment] 2024-07-19 20:11
Hi there, did you follow the instructions here or somewhere else? [https://docs.modular.com/mojo/manual/python/#set-up-a-python-environment-with-conda](https://docs.modular.com/mojo/manual/python/#set-up-a-python-environment-with-conda).  What version of Python are you using?

**Comment by hogepodge** [comment] 2024-08-06 17:04
Since we haven't received any feedback on this issue and can't reproduce it, I'm going to close it. Please feel free to re-open if you're still running in to it. Thanks!

**Closed by hogepodge** 2024-08-06 17:04 UTC
Labels: bug, mojo-python-interop, mojo-repo
