### ISSUE TITLE
[BUG] print with empty string as end

### ISSUE THREAD

**Issue by FredslundMagnus** [modularml/mojo#1976] opened 2024-03-17 20:55 UTC
### Bug description

There is some unexpected behaviour when printing using end="". I found print_no_newline after so can use that instead but think this is not the intended behaviour.

### Steps to reproduce

```mojo
# error.mojo

fn printBits(data: Int) -> None:
    for i in range(0, 64):
        print((data >> (63-i)) & 1, end="")
    print("")

fn printBitsSpace(data: Int) -> None:
    for i in range(0, 64):
        print((data >> (63-i)) & 1, end=" ")
    print("")

fn main():
    printBits(7)

    # printBitsSpace(7) # The output of printBits changes when this is commented in or out
```
I run with command:
```cmd
mojo run error.mojo
```

The output
```cmd
With last line commented out: 
0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime0Runtime1Runtime1Runtime1Runtime

With last line NOT commented out:
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
```

### System information

```shell
Windows WSL: Ubuntu-22.04
mojo -v: mojo 24.1.0 (55ec12d6)
modular -v: modular 0.5.2 (6b3a04fd)
```

**Comment by soraros** [comment] 2024-03-17 21:12
Duplicate of #1838.

**Comment by JoeLoser** [comment] 2024-03-20 03:37
This should be fixed in 24.2 which will be released soon. I'll leave this open until you verify the fixes that landed do indeed fix your issue. Going to mark this issue into a "waiting for response" state so I know to circle back after the release. Thanks for the report!

**Comment by FredslundMagnus** [comment] 2024-03-20 07:43
Perfect! I will update as soon as possible and let you know

**Comment by JoeLoser** [comment] 2024-03-23 03:45
Going to go ahead and close this as I've now replaced all of our internal uses of `print_no_newline` with `print(end="")` and in fact, the next release removes the `print_no_newline` function entirely.

**Closed by JoeLoser** 2024-03-23 03:45 UTC
Labels: bug, mojo-stdlib, mojo

**Comment by FredslundMagnus** [comment] 2024-03-28 19:22
Works, thanks!
