### ISSUE TITLE
[BUG]: Error on special method __del__ call

### ISSUE THREAD

**Issue by AlaDeli7** [modularml/mojo#1460] opened 2023-12-10 10:37 UTC
### Bug description

I am expecting __del__ method to be called and printing some message to the console, but i got the followingh error message 

`mojo: /__w/modular/modular/third-party/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = M::KGEN::PointerType, From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
[9804:9804:20231210,113539.000042:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[9804:9804:20231210,113539.000115:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo issue.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo      0x0000556d6b764e17
1  mojo      0x0000556d6b7629ee
2  mojo      0x0000556d6b7654ef
3  libc.so.6 0x00007ff693f42520
4  libc.so.6 0x00007ff693f969fc pthread_kill + 300
5  libc.so.6 0x00007ff693f42476 raise + 22
6  libc.so.6 0x00007ff693f287f3 abort + 211
7  libc.so.6 0x00007ff693f2871b
8  libc.so.6 0x00007ff693f39e96
9  mojo      0x0000556d6cf156b5
10 mojo      0x0000556d6cef9564
11 mojo      0x0000556d6cdc2ac1
12 mojo      0x0000556d6cdc1e49
13 mojo      0x0000556d6cdbfd6c
14 mojo      0x0000556d6cdbee48
15 mojo      0x0000556d6cdbe67b
16 mojo      0x0000556d6cdb4ff9
17 mojo      0x0000556d6e0f2516
18 mojo      0x0000556d6e0f2ba1
19 mojo      0x0000556d6e0f50f2
20 mojo      0x0000556d6cd450ea
21 mojo      0x0000556d6bcaaf69
22 mojo      0x0000556d6cd446ea
23 mojo      0x0000556d6d9a828a
24 mojo      0x0000556d6d9aef4f
25 mojo      0x0000556d6da3c469
26 mojo      0x0000556d6da3c6d9
27 mojo      0x0000556d6da37fc4
28 mojo      0x0000556d6d9ad364
29 mojo      0x0000556d6bca35af
30 mojo      0x0000556d6b72d175
31 mojo      0x0000556d6b7143b6
32 libc.so.6 0x00007ff693f29d90
33 libc.so.6 0x00007ff693f29e40 __libc_start_main + 128
34 mojo      0x0000556d6b71397e
Aborted`

### Steps to reproduce

Code : 

`

struct Dog:
    var name: String

    fn __init__(inout self, name: String = "Max"):
        print("Calling __init__ on Dog : ", name)
        self.name = name

    fn __del__(owned self):
        print("Calling __del__ on Dog : ", self.name)

def main():
    let max = Dog()
`

### System information

```shell
- What OS did you do install Mojo on ?
wsl on windows 10 pro
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.0 (d55c0025)
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by laszlokindrat** [comment] 2023-12-15 22:34
Seems like a duplicate of https://github.com/modularml/mojo/issues/1386, closing in favor of that.

**Closed by laszlokindrat** 2023-12-15 22:34 UTC
Labels: bug, mojo-lang, mojo
