### ISSUE TITLE
[Modular CLI]: Stuck when try to download mojo

### ISSUE THREAD

**Issue by DungDeta** [modularml/mojo#1218] opened 2023-11-03 02:21 UTC
### Issue description

![image](https://github.com/modularml/mojo/assets/127428218/76e06f9a-5499-4a14-850c-c1cdb838911f)
I used this command to install
sudo apt-get update && \
sudo apt-get install modular && \
modular clean && \
modular install mojo

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by Sharktheone** [comment] 2023-11-03 05:22
Duplicate of #970. 
Short version:
You are probably using WSL1 and not WSL2. Upgrade to WSL2 since WSL1 isn't officially supported.

**Comment by DungDeta** [comment] 2023-11-03 10:31
I fixed it, just use WSL2

**Closed** 2023-11-03 10:31 UTC
Labels: modular-cli
