### ISSUE TITLE
cell execution order bug

### ISSUE THREAD

**Issue by enavar25** [modularml/mojo#423] opened 2023-07-02 22:04 UTC
### Bug description

```shell
I was trying to initialize a ListLiteral of StringLiteral type with the following code: 

var myList : ListLiteral[StringLiteral, StringLiteral, StringLiteral] = ListLiteral.__init__("Hello", "World", "Mojo")

and when I used the print function in a different cell to print out myList I got the following:

['Hello', 'World', '']

I also put in the following line of code in one cell 
var newList : ListLiteral[StringLiteral, StringLiteral, StringLiteral, StringLiteral] = ListLiteral.__init__("Hello", "World", "Mojo", "bug")

and implemented the following code in another cell :

print(newList)

and got the following output:
['H', 'World', 'Mojo', '']
```

### Steps to reproduce

```shell
1. Type in the following line of code in once cell:

var myList : ListLiteral[StringLiteral, StringLiteral, StringLiteral] = ListLiteral.__init__("Hello", "World", "Mojo")

2. Then type in the following code in a different cell below:
print(newList)


this was all run on a Jupyter notebook using the mojo kernel
```

### System information

```shell
%%python
import subprocess
subprocess.Popen(["cat", "/proc/self/cgroup"])
```

**Comment by Mogball** [comment] 2023-07-03 17:42
Thanks for filing this issue! This behaviour is extremely odd and definitely is an issue, but I believe it's a duplicate of https://github.com/modularml/mojo/issues/232. String literals are pointers to a global constant but it's likely those are not being persisted across cells consistently, resulting in the memory corruption you are seeing.

**Closed by Mogball** 2023-07-03 17:42 UTC
Labels: bug
