### ISSUE TITLE
[BUG]: parser crash when declaring variable without type in an fn context

### ISSUE THREAD

**Issue by robertbcalhoun** [modularml/mojo#957] opened 2023-09-29 21:49 UTC
### Bug description

Defining a variable in an `fn` context without a datatype followed by `print_without_newline()` crashes mojo parser.

(New to Mojo, but I believe variables without datatypes are not permitted in an `fn` context).

### Steps to reproduce

*Observed:*
```
fn main():
    var xyzzy:
    print_no_newline("hello, ")
    print("world")
    xyzzy = 2.2222
    print(xyzzy)
```

```
$ mojo crash.mojo
<unknown>:0: error: variadic sequence element #0 has type
'!kgen.declref<@"$builtin"::@"$io"::@_Printable>' 
but expected 
'!kgen.pointer<!kgen.declref<@"$builtin"::@"$io"::@_Printable>>'
```
plus stack trace:
[crash.log](https://github.com/modularml/mojo/files/12772087/crash.log)

*Expected:*
```
fn main():
    var xyzzy:
    print("hello, world")
    xyzzy = 2.2222
    print(xyzzy)
```

```
$ mojo crash.mojo
/mnt/e/git/mojo/crash.mojo:3:10: error: expected a type, not a value
    print("hello, world")
    ~~~~~^~~~~~~~~~~~~~~~
mojo: error: failed to parse the provided Mojo
```

### System information

```shell
- OS WSL2 (`Linux RUBY 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux`)
- mojo 0.3.1 (a3eed7c8)
- modular 0.2.0 (355ea9c0)
```

**Comment by ksandvik** [comment] 2023-09-29 22:22
Yes, the variable should be defined as let or var, but crashing without a proper error code might need a fix.

**Comment by laszlokindrat** [comment] 2023-10-05 15:54
Thanks for opening the ticket! I was able to reproduce the crash; the issue was that the parser was expecting a type, and but find a function call (which results in a value):
fn main():
    var xyzzy:
    print_no_newline("hello, ")  # we expect the type expression here for `xyzzy`
If the function had a signature with a variadic argument of an implicitly convertible type, it would result in a crash. I have a fix for this that will emit a meaningful error message instead.

**Comment by laszlokindrat** [comment] 2023-10-06 00:45
Update: the problem was actually a bit more nuanced. When trying to evaluate a function at compile time (not just in a context where a type is expected), variadic arguments of a memory-only type would cause the parser to crash. For example:
```mojo
alias b = print_no_newline("hello, ")
```
This will be fixed in the next release, and the example in the OP will emit the correct error about expecting a type instead of a value.

**Closed** 2023-10-06 14:30 UTC
Labels: bug, mojo-lang, mojo
