### ISSUE TITLE
[Modular CLI]: cannot install mojo in ubuntu22.04

### ISSUE THREAD

**Issue by Anwenya** [modularml/mojo#755] opened 2023-09-12 15:58 UTC
### Issue description

It got stuck during installation
![image](https://github.com/modularml/mojo/assets/51585911/4a9b801a-3f0f-46d5-ae6c-49dbf59c07df)

### Steps to reproduce

run “modular install mojo”

then stuck here
“”“
Testing `MODULAR_HOME=/root/.modular` * `/root/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
”“”

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
- What OS did you install modular CLI on ?
ubuntuserver 22.04.3
```

**Comment by aguspiza** [comment] 2023-09-12 19:18
There is nothing wrong here, mojo is ready. You should not use root account with pip though.

**Comment by drunkwcodes** [comment] 2023-09-13 02:24
Duplicate of #538 .

**Comment by jackos** [comment] 2023-09-13 04:51
Thanks again @drunkwcodes closing in favor of #538

**Closed by jackos** 2023-09-13 04:51 UTC
Labels: modular-cli

**Comment by Anwenya** [comment] 2023-09-13 14:47
thanks for everyone！
