### ISSUE TITLE
[BUG]: Passing keyword arguments to Python functions  fails

### ISSUE THREAD

**Issue by nickyoung-github** [modularml/mojo#1094] opened 2023-10-19 20:31 UTC
### Bug description

Passing keyword arguments to Python functions fails, complaining about unexpected arguments to \_\_call\_\_
<br/><br/>

 /Users/Nick/Code/mojo/test.mojo:6:16: error: invalid call to '\_\_call\_\_': unexpected keyword argument: 'i'
    print(m.foo(i=321))
          ~~~~~^~~~~~~
/Users/Nick/Code/mojo/test.mojo:1:1: note: function declared here
from python import Python
^
mojo: error: failed to parse the provided Mojo


### Steps to reproduce

**test.mojo:**

```
from python import Python

def main():
    Python.add_to_path(".")
    let m = Python.import_module("test")
    print(m.foo(i=321))
```


**test.py:**

```
def foo(i: int = 123, s: str = "hello") -> str:
    return f"{i} - {s}"
```

### System information

```shell
- MacBook Pro 13" M1. Sonoma 14.0
- mojo 0.4.0 (9e33b013)
- modular 0.2.1 (5144fffe)
```

**Comment by jackos** [comment] 2023-10-19 21:49
Duplicate of https://github.com/modularml/mojo/issues/964 thanks

**Closed by jackos** 2023-10-19 21:49 UTC
Labels: bug, mojo
