### ISSUE TITLE
[Modular CLI]: Failed to install Modular CLI ubuntu 22.04

### ISSUE THREAD

**Issue by ykutaykuta** [modularml/mojo#602] opened 2023-09-08 01:35 UTC
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0  11468      0 --:--:-- --:--:-- --:--:-- 11507
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
          : ... Detected/provided for your OS/distribution, version and architecture:
          :
          : ... distro=ubuntu  version=22.04  codename=jammy  arch=x86_64
          :
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'modular/installer' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'modular/installer' repository via apt ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Get:1 file:/var/cudnn-local-repo-ubuntu2204-8.9.3.28  InRelease [1,572 B]
Get:2 file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  InRelease [1,572 B]
Get:1 file:/var/cudnn-local-repo-ubuntu2204-8.9.3.28  InRelease [1,572 B]
Get:2 file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  InRelease [1,572 B]
Err:1 file:/var/cudnn-local-repo-ubuntu2204-8.9.3.28  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 619ECF317F7A158C
Err:2 file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 357A109272322D7F
Hit:3 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:4 http://vn.archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://vn.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://vn.archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:7 https://pkg.jenkins.io/debian-stable binary/ InRelease
Hit:8 http://vn.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:9 https://pkg.jenkins.io/debian-stable binary/ Release
Get:10 https://dl.modular.com/public/installer/deb/ubuntu jammy InRelease [5,076 B]
Get:11 https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64  InRelease [1,484 B]
Hit:13 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64  InRelease
Hit:14 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:15 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease
Ign:16 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 InRelease
Hit:18 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 Release
Hit:17 https://apache.jfrog.io/artifactory/cassandra-deb 41x InRelease
Reading package lists...
W: GPG error: file:/var/cudnn-local-repo-ubuntu2204-8.9.3.28  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 619ECF317F7A158C
E: The repository 'file:/var/cudnn-local-repo-ubuntu2204-8.9.3.28  InRelease' is not signed.
W: GPG error: file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 357A109272322D7F
E: The repository 'file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  InRelease' is not signed.
W: https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://debian.cassandra.apache.org/dists/41x/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:2
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/cassandra.sources.list:1 and /etc/apt/sources.list.d/cassandra.sources.list:3
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!:
 !!!!: You can contact Modular for further assistance.
 !!!!:

### Version Info
- Ubuntu 22.04 - i5-12400F
- python 3.10.12
- g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by ykutaykuta** [comment] 2023-09-08 01:53
I just removed local package installed and it was installed successfully. But I wonder is there any solution without remove local package?

**Comment by smuniraj2018** [comment] 2023-09-08 04:49
duplicate of [iss606](https://github.com/modularml/mojo/issues/606)

**Closed by smuniraj2018** 2023-09-08 04:49 UTC
Labels: modular-cli
