### ISSUE TITLE
[BUG]: Doesn't reject empty identifier name

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1232] opened 2023-11-05 19:37 UTC
### Bug description

I'm not sure if it's a bug or an unintuitive corner case like Banach-Tarski.

### Steps to reproduce

Consider the following code:

```mojo
fn main():
    let `` = 1
    print(``)
```

### System information

```shell
mojo 0.5.0 on docker, macOS Intel
```

**Comment by Mogball** [comment] 2023-11-08 02:27
I'm tempted to say this is working as intended. @lattner @laszlokindrat thoughts?

**Comment by Mogball** [comment] 2023-11-08 16:01
We should probably reject this. While this is cool, empty identifiers (and symbol names) could cause all sorts of trouble.

**Comment by lattner** [comment] 2023-11-25 00:19
Fixed in next release, you'll now get: `error: empty backtick identifier isn't allowed`.  Thanks for filing this!

**Closed by lattner** 2023-11-25 00:19 UTC
Labels: bug, mojo-lang, mojo
