### ISSUE TITLE
[BUG]: scaling_cur_freq: No such file or directory

### ISSUE THREAD

**Issue by RedhaZid35** [modularml/mojo#791] opened 2023-09-13 23:49 UTC
### Bug description

[3629:3629:20230914,014111.133982:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[3629:3629:20230914,014111.134049:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: /home/redha/.modular/pkg/packages.modular.com_mojo/bin/mojo /home/redha/redha/primes.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo      0x0000563aabd9d957
1  mojo      0x0000563aabd9b52e
2  mojo      0x0000563aabd9e02f
3  libc.so.6 0x00007f05c0ee1520
4  libc.so.6 0x00007f0544002120
Segmentation fault

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? 
windows with wsl 
 
- Provide version information for Mojo by pasting the output of `mojo -v` 
CORE
  Perl        (v5.34.0, linux)
  Mojolicious (9.22, Waffle)

OPTIONAL
  Cpanel::JSON::XS 4.09+   (4.27)
  EV 4.32+                 (4.33)
  IO::Socket::Socks 0.64+  (0.74)
  IO::Socket::SSL 2.009+   (2.074)
  Net::DNS::Native 0.15+   (n/a)
  Role::Tiny 2.000001+     (2.002004)
  Future::AsyncAwait 0.52+ (0.56)

You might want to update your Mojolicious to 9.34!


- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
```

**Comment by ematejska** [comment] 2023-09-14 18:45
Can you share a code snippet that reproduces this?

**Comment by ematejska** [comment] 2023-09-18 19:24
We'll keep this open for another week to see if you have a code snippet and then we'll close if no feedback.

**Comment by ArthurB2077** [comment] 2023-09-22 13:24
Hello ! I'm facing the same issue with my mojo installation. 

I have set $MOJO_PYTHON_LIBRAY and LLVM_SYMBOLIZER_PATH because errors concerning this two env vars occured previously.

You can check my code in the following snippets:

**main.🔥:**

```mojo
from benchmark import Benchmark
from os import env
from complex import ComplexSIMD, ComplexFloat64
from math import iota
from python import Python
from python.object import PythonObject
from runtime.llcl import num_cores, Runtime
from algorithm import parallelize, vectorize
from tensor import Tensor
from utils.index import Index

alias float_type = DType.float64
alias simd_width = simdwidthof[float_type]()

alias width = 960
alias height = 960
alias MAX_ITERS = 200

alias min_x = -2.0
alias max_x = 0.6
alias min_y = -1.5
alias max_y = 1.5

var np: PythonObject = None
var plt: PythonObject = None
var colors: PythonObject = None

fn load():
    try:
        np = Python.import_module("numpy")
        plt = Python.import_module("matplotlib.pyplot")
        colors = Python.import_module("matplotlib.colors")
        print(np.input())
    except:
        pass


def main():
    load()
    show_plot(compute_mandelbrot())

# Compute the number of steps to escape.
def mandelbrot_kernel(c: ComplexFloat64) -> Int:
    z = c
    for i in range(MAX_ITERS):
        z = z * z + c
        if z.squared_norm() > 4:
            return i
    return MAX_ITERS

def compute_mandelbrot() -> Tensor[float_type]:
    # create a matrix. Each element of the matrix corresponds to a pixel
    t = Tensor[float_type](height, width)

    dx = (max_x - min_x) / width
    dy = (max_y - min_y) / height

    y = min_y
    for row in range(height):
        x = min_x
        for col in range(width):
            t[Index(row, col)] = mandelbrot_kernel(ComplexFloat64(x, y))
            x += dx
        y += dy
    return t

def show_plot(tensor: Tensor[float_type]):
    alias scale = 10
    alias dpi = 64

    var numpy_array: PythonObject = None

    try:
        numpy_array = np.zeros((height, width), np.float64)

        for row in range(height):
            for col in range(width):
                numpy_array.itemset((col, row), tensor[col, row])

        fig = plt.figure(1, [scale, scale * height // width], dpi)
        ax = fig.add_axes([0.0, 0.0, 1.0, 1.0], False, 1)
        light = colors.LightSource(315, 10, 0, 1, 1, 0)

        image = light.shade(numpy_array, plt.cm.hot, colors.PowerNorm(0.3), "hsv", 0, 0, 1.5)
        plt.imshow(image)
        plt.axis("off")
        plt.show()
    except:
        pass
```


I set up my .zshrc like this:

**~/.zshrc**
```zsh
export MODULAR_HOME="/home/athernatos/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"
export KEYRING_LOCATION=/usr/share/keyrings/modular-installer-archive-keyring.gpg
export MOJO_PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.10.so
export LLVM_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer
```

I'm using mojo 0.3.0 (f64f9601).

I'm running this in ubuntu jammy 22.04 in WSL (windows 11).

I've done the install like required and have the following modular.cfg:

```cfg
[installed]
packages_modular_com_mojo = /home/athernatos/.modular/pkg/packages.modular.com_mojo

[mojo]
compilerrt_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so.18git
compilerrt_static_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRT-static.a
driver_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/bin/mojo
import_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/mojo
lldb_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/bin/lldb
lldb_plugin_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git
lldb_visualizers_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/lldb-visualizers
lldb_vscode_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/bin/lldb-vscode
lsp_server_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/bin/mojo-lsp-server
mblack_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/mblack/mblack
orcrt_path = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/liborc_rt.a
python_lib = /usr/lib/x86_64-linux-gnu/libpython3.10.so
repl_entry_point = /home/athernatos/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point
system_libs = -lrt,-ldl,-lpthread,-lm,-lz,-ltinfo

[user]
id = /usr/share/keyrings/modular-installer-archive-keyring.gpg
```
I'm not using virtual env and have the following pythonlib installed:

```zsh
Python 3.10.12 library found
You can found the library at:
/usr/lib/x86_64-linux-gnu

The following files where found:
libpython3.10.a
libpython3.10.so
libpython3.10.so.1
libpython3.10.so.1.0

Python library path should be:
libpython3.10.so
```

**Comment by jackos** [comment] 2023-09-26 17:46
@ArthurB2077 that's a separate issue but try installing [miniconda](https://docs.conda.io/projects/miniconda/en/latest/) and doing: 

```bash
conda create -yn py311 python=3.11 numpy matplotlib
conda activate py311

export MOJO_PYTHON_LIBRARY="$(ls $(conda info --base)/envs/py311/lib/libpython*)"
echo "export MOJO_PYTHON_LIBRARY=$MOJO_PYTHON_LIBRARY" >> ~/.bashrc
```

Please report the error if that doesn't work, closing this issue as original issue gives no indication of what code is running

**Closed by jackos** 2023-09-26 17:46 UTC
Labels: bug, mojo, mojo-python-interop
