### ISSUE TITLE
[BUG]: Debugger does not stop at breakpoint in VSC on Github codespace

### ISSUE THREAD

**Issue by diro5t** [modularml/mojo#1924] opened 2024-03-10 03:02 UTC
### Bug description

The debugger does not stop at a breakpoint no matter what - any program just runs through every time and the debugger session ends.

### Steps to reproduce

The effect is reproducible with ANY Mojo program.

### System information

```shell
mojo 24.1.0 (55ec12d6)
modular 0.5.1 (1b608e3d)

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by RyanLeber** [comment] 2024-03-10 19:12
I have the same issue. However, if I add a `breakpoint()` in the code it will break at that point. In the bellow example it will log my print statement in the debug console, but I do not get any info inline or in the side panel. 
```
# this will not log anything no matter there the breakpoint is.
fn loop():
    for i in range(10):  
        print(i) 

fn main():
    loop()
```
```
# this will only log the print statement in the debug console.
fn loop():
    for i in range(10):  
        breakpoint()
        print(i) 

fn main():
    loop()
```
If I build the file with `mojo build -O0 --debug-level=full test.mojo` then debug the binary all of the debugging features work.

Uninstalling the mojo extension and reinstalling it did not fix the issue and I have verified that I can debug files in other languages.

## System information
```
mojo 24.1.0 (55ec12d6)
modular 0.5.1 (1b608e3d)

WSL2
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

**Comment by diro5t** [comment] 2024-03-10 19:58
Yep, breakpoint() stops, but I can't see content of variables etc.

**Comment by andompesta** [comment] 2024-03-15 18:27
Experiencing the same issue.

mojo version = 24.1.0
modular version = 0.5.2
conda version = 23.11.0
macOs = 14.2.1

launch setup
```json
[
    {
            "type": "mojo-lldb",
            "request": "launch",
            "name": "Mojo: Debug current Mojo file",
            "mojoFile": "${file}",
            "args": [],
            "cwd": "${workspaceFolder}",
    }
]
```
`breakpoint()` does work but as mentioned by @diro5t you don't see any variable:
<img width="288" alt="Screenshot 2024-03-15 at 19 26 49" src="https://github.com/modularml/mojo/assets/6725612/81c2f95c-c274-4314-a5f6-15ff9c409e9a">

**Comment by walter-erquinigo** [comment] 2024-03-25 15:02
As mentioned in https://github.com/modularml/max/issues/125, we've identified an issue with the currently shipped SDK where we're accidentally stripping symbols used by the debugger for JIT debugging. We're working on a fix, but it will likely only resolve issues on Linux platforms for the next release, resolving this for Mac will likely make it into the 24.3 release of Mojo/Max (not the next release, but the one after). Terribly sorry for the issues encountered! 🙇

However, I'm going add here some troubleshooting until we get the proper fix out:

Regular non-JIT debugging still working, so if you want to debug the program foo.mojo, you can run the following two commands from a terminal

mojo build -O0 -debug-level=full foo.mojo -o /tmp/bin
mojo debug --rpc /tmp/bin 
That should start the debug session on VSCode, via the --rpc functionality, without having to JIT. I hope this can get you unblocked.

**Comment by diro5t** [comment] 2024-04-05 15:23
Hi all, 

still get a free(): invalid pointer when trying to stop at a breakpoint - Mojo 24.2 on Github codespaces.

Is it solved for anyone else? Thanks

**Comment by walter-erquinigo** [comment] 2024-04-17 16:57
@diro5t , I've just tried debugging in a github codespace using Mojo version 24.2.1 and it worked. Could you share more specifically which specific codespace machine you got (OS, CPU, architecture, etc) and which code you tried to debug? That will help me root cause that `invalid pointer` issue.

**Comment by diro5t** [comment] 2024-04-17 18:00
@walter-erquinigo interestingly enough I don't get the invalid pointer anymore, but when I put a breakpoint in line 3 , it jumps to the print command  in line 5 and stops there, variables not shown either. Maybe I am doing sth. wrong?
![image](https://github.com/modularml/mojo/assets/57329722/19cc2340-bd5f-421b-84ba-93d1dba74cc4)

**Comment by diro5t** [comment] 2024-04-17 18:03
@walter-erquinigo 
![image](https://github.com/modularml/mojo/assets/57329722/9823dce1-f144-4f20-bcce-71e7b130c4f7)

Codespace was created from the Jupyter template on Codespaces.

![image](https://github.com/modularml/mojo/assets/57329722/cd4ef72b-417a-4727-b0f9-7e21fb71f27f)

![image](https://github.com/modularml/mojo/assets/57329722/06eef635-c01d-4148-90f2-7ff59e221c54)

**Comment by walter-erquinigo** [comment] 2024-04-17 19:20
@diro5t , good to know that you were able to launch the debugger.

What you are hitting is a limitation of the current debugging experience.

1. We do perform some optimization passes even for debug builds, which result in the variables `a` and `b` being optimized out because they are simple constants. These optimizations even affect `c`, where its definition is moved to line `5` directly, which results in no breakpoints available in any lines except for `5`.
2. `c` is not printed because the debugger thinks it's dead. This is an issue caused when you are in the last line that uses a variable. The fix is already on its way for the next release. See the screenshot below 

<img width="635" alt="Screenshot 2024-04-17 at 9 19 07 PM" src="https://github.com/modularml/mojo/assets/1613874/fc3d0e07-08c7-4102-ac10-09ba1caafa3d">

In general, the debugger is still in its infancy, and we thank folks like you for submitting issues. It helps us prioritize and catch issues we might not see internally. Having said that, most non-trivial variables should be visible except maybe for its last use.

**Comment by walter-erquinigo** [comment] 2024-04-17 19:21
I'll be closing this issue because breakpoints do work when available. Feel free to reopen this issue if its related to basic debugging support, or create new issues if it's related to specific debugger behaviors.

**Closed by walter-erquinigo** 2024-04-17 19:21 UTC
Labels: bug, mojo-tooling
