### ISSUE TITLE
[Modular CLI]: modular ERROR invalid argument(22)

### ISSUE THREAD

**Issue by Ukulele-Dan** [modularml/mojo#1063] opened 2023-10-15 23:02 UTC
### Issue description

modular clean
[3694:3694:20231016,065651.517808:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[3692:3692:20231016,065651.518450:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler

modular install mojo
[3341:3341:20231016,065535.371215:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[3339:3339:20231016,065535.371708:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/snail/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - Creating symlink for /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so.18git -> /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so failed: File exists
        - Creating symlink for /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so.18git -> /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so failed: File exists
        - Creating symlink for /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so.18git -> /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so failed: File exists
        - Creating symlink for /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so.18git -> /home/snail/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so failed: File exists
==========================

Can someone look at this for me? Thank you

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by smuniraj2018** [comment] 2023-10-17 21:26
Closing as its a duplicate of #984

**Closed** 2024-10-14 19:02 UTC
Labels: modular-cli, mojo-repo
