### ISSUE TITLE
native SDK for Mojo for Apple MAC Intel

### ISSUE THREAD

**Issue by aespeiuk22** [modularml/mojo#1162] opened 2023-10-26 14:53 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

native SDK for Mojo for Apple MAC Intel. I have a very high end MAC waiting for mojo!

### What is your motivation for this change?

I have a very powerful high end MAC Intel unable to squeeze more out of it. Need it to continue working on my evolutionary ai model to bring up some real changes.

### Any other details?

Please Please consider this as Intel MACs will be less in numbers of votes, but it matters a lot what they do seriously!

**Comment by Sharktheone** [comment] 2023-10-26 16:18
duplicate of #1092

**Closed** 2023-10-28 05:38 UTC
Labels: enhancement, mojo
