### ISSUE TITLE
[Feature Request] change transfer operator (  ^ ) To the keyword ( move )

### ISSUE THREAD

**Issue by Eprahim-taha** [modularml/mojo#1469] opened 2023-12-11 11:12 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

change transfer operator ( ^ ) To the keyword ( move ).
And with this approach ( move ) for transferring ownership fits nicely into 4-character convention instead of ( ^ )

let a: String = "Hello"
let b: String = a^   ❌
let b: String = move a   ✅

### What is your motivation for this change?

Make Mojo 🔥 more readable and understandable

**Comment by gryznar** [comment] 2023-12-11 12:09
+1 for this!
`^` may confuse Python users a lot, because in Python this character is for bitwise operation

**Comment by ParadaCarleton** [comment] 2023-12-13 02:04
See #1279 (this might be a duplicate issue).

**Comment by lattner** [comment] 2023-12-13 05:51
Why is this a progression?  I understand the difference between keyword vs punctuation, but this breaks chaining, e.g. `a^.foo()` vs `(move a).foo()`.  Also, `^` isn't a move operation (literally no data is moved), it denotes that the expression's lifetime has ended so it can be consumed directly instead of copied.

**Comment by lattner** [comment] 2023-12-13 05:52
Yep, duplicate of #1279, lets consolidate the discussion there.

**Closed by lattner** 2023-12-13 05:52 UTC
Labels: enhancement, mojo-lang, mojo
