### ISSUE TITLE
[BUG]: Docs code not work

### ISSUE THREAD

**Issue by lordkeker31** [modularml/mojo#489] opened 2023-08-04 14:25 UTC
### Where is the problem?

https://docs.modular.com/mojo/notebooks/BoolMLIR.html#implementing-__bool__

### What can we do better?

i use this code:
alias OurTrue = OurBool(__mlir_attr.`true`)
alias OurFalse: OurBool = __mlir_attr.`false`

@register_passable("trivial")
struct OurBool:
    var value: __mlir_type.i1

    fn __init__(value: __mlir_type.i1) -> Self:
        return Self {value: value}
    
    fn __bool__(self) -> Bool:
        return Bool(self.value)
ob = OurTrue
if ob: print("work!");

and i get error:

error: Expression [62]:30:10: cannot implicitly convert 'OurBool' value to 'OurBool' in assignment
    ob = OurTrue
         ^~~~~~~

error: Expression [62]:31:8: 'OurBool' does not implement the '__bool__' method
    if ob: print("work!");
       ^

expression failed to parse (no further compiler diagnostics)

**Comment by Mogball** [comment] 2023-08-08 06:33
cc @modocache @scottamain

**Comment by modocache** [comment] 2023-08-08 15:06
Interesting, thanks for the bug report!

Just a few quick notes -- as of today, playground.modular.com's BoolMLIR notebook executes with no error, and the following works for me as well:

<img width="580" alt="A screenshot of playground.modular.com executing the code from the bug report with no errors. 'work!' is printed." src="https://github.com/modularml/mojo/assets/552921/5c1f5316-391f-4816-bcfc-ca50999acb02">

But I do believe that you could encounter the error you posted, maybe when executing multiple cells with multiple definitions of `OurBool` and `OurTrue`. For example:

<img width="827" alt="A screenshot of playground.modular.com with a sequence of cells that reproduce the errors from the bug report." src="https://github.com/modularml/mojo/assets/552921/418c5927-b935-4419-a383-a875ec5e7572">

What can be confusing about the playground's mode of execution is that the `OurBool` definition that `OurTrue` uses is the one that's available at the point that `OurBool` is defined. So, if `OurTrue` is defined to refer to an `OurBool` that does not implement a `__bool__` method, then even if `OurBool` is re-defined to now implement the `__bool__` method, the `OurTrue` alias is not "updated" in any way to refer to that re-definition.

This is why, in the BoolMLIR notebook, `OurTrue` and `OurFalse` are re-defined in each cell that `OurBool` is re-defined. They need to point to the latest re-definition of `OurBool`. Does that make sense?

This is similar to the issues reported in #352 and #415. These are all basically "working as intended," but the behavior can definitely be confusing. We're discussing whether we ought to make any changes to make this clearer or work differently. But since those issues track similar work, I'll close this for now. Please re-open if my explanation isn't clear or if you disagree -- thanks!

**Closed by modocache** 2023-08-08 15:06 UTC
Labels: documentation
