### ISSUE TITLE
[BUG]: Excessive memory consumption due to large range object creation; optimize efficiency.

### ISSUE THREAD

**Issue by Alex19578** [modularml/mojo#399] opened 2023-06-21 07:02 UTC
### Bug description

```shell
from Range import range

# Creating a zero-based range from 0 to 10
var zero_based_range = range(10)

print(zero_based_range.__len__())  # Output: 10

print(zero_based_range.__getitem__(1))  # Output: 1

print(zero_based_range.__getitem__(10))  # Output: 10

# Creating a sequential range from 1 to 10
var sequential_range = range(1, 10)

print(sequential_range.__len__())  # Output: 9

print(sequential_range.__getitem__(1))  # Output: 1

print(sequential_range.__getitem__(10))  # Output: 11

print(sequential_range.__getitem__(100))  # Output: 101

print(sequential_range.__getitem__(1000000000000000000))  # Output: 1000000000000000001

print(sequential_range.__getitem__(10000000000000000000))  # Output: -8446744073709551615

print(sequential_range.__getitem__(100000000000000000000))  # Output: 7766279631452241921

# Creating a strided range from 1 to 100 with a stride of 5
var strided_range = range(1, 100, 5)

print(strided_range.__len__())  # Output: 20

print(strided_range.__getitem__(1))  # Output: 1

print(strided_range.__getitem__(10))  # Output: 51

print(strided_range.__getitem__(100))  # Output: 501

print(strided_range.__getitem__(1000000000000000000))  # Output: 5000000000000000001

print(strided_range.__getitem__(100000000000000000000))  # Output: 1937910009842106369
```

### Steps to reproduce

```shell
- Name the pre-existing notebook that failed and the steps that led to failure.
- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.
```

### System information

```shell
11:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
10:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
9:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
8:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
7:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
6:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
5:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
4:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
3:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
2:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3cf7faef_6806_48d3_a614_fc63a1e8b65a.slice/cri-containerd-36e12624670736af25c17ac71af6ae9c7591abe72186559597faa26a542090a1.scope
0::/
```

**Comment by abduld** [comment] 2023-06-22 01:54
The range struct is actually optimized and uses at most 3 integers for the range values. It does not materialize the range into a buffer. We do not support arbitrary precision integers which I believe this is the root cause of the issue you are reporting. 

I am closing this, but please reopen if you have more details. Thanks

**Closed by abduld** 2023-06-22 01:54 UTC
Labels: bug
