### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by Charanvigneshnr** [modularml/mojo#1497] opened 2023-12-16 09:20 UTC
### Issue description

no packages found for the current target hardware

Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver1
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, lzcnt, mmx, movbe, mwaitx, pclmul, popcnt, prfchw, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, x87, xsave, xsavec, xsaveopt, xsaves
  CPU: AMD Ryzen 5 4600H, Nvidia GTX 1650 GDDR6

### Steps to reproduce

Just followed the default installation guide from Modular, got the same issue in both normal user and root user in Ubuntu

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v` : 0.3.0 (8afa5600)
- What OS did you install modular CLI on ? : 

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by Sharktheone** [comment] 2023-12-16 13:36
Duplicate of #1492

**Comment by zbowling** [comment] 2023-12-16 19:35
I just pushed a new patch release for the modular CLI (version 0.3.1) that should hopefully resolve this issue on AMD CPUs.

If you have already installed the modular CLI from the [modular.com](http://modular.com/) site you can update modular on Ubuntu with:
```
> apt-get update && apt-get upgrade modular
```

After that you can test you have the latest version of modular with:
```
> modular --version
modular 0.3.1 (589ce200)
```

Both `modular install mojo` and `modular upgrade mojo` commands should work. 

Let me know if you run into any more trouble on #1492!

**Closed by zbowling** 2023-12-16 19:35 UTC
Labels: modular-cli

**Comment by Charanvigneshnr** [comment] 2023-12-17 05:47
> I just pushed a new patch release for the modular CLI (version 0.3.1) that should hopefully resolve this issue on AMD CPUs.
> 
> If you have already installed the modular CLI from the [modular.com](http://modular.com/) site you can update modular on Ubuntu with:
> 
> ```
> > apt-get update && apt-get upgrade modular
> ```
> 
> After that you can test you have the latest version of modular with:
> 
> ```
> > modular --version
> modular 0.3.1 (589ce200)
> ```
> 
> Both `modular install mojo` and `modular upgrade mojo` commands should work.
> 
> Let me know if you run into any more trouble on #1492!

It's working now, thanks!
