### ISSUE TITLE
[Modular CLI]: Failed to reach URL timeout was reached

### ISSUE THREAD

**Issue by jonas1ara** [modularml/mojo#598] opened 2023-09-08 01:20 UTC
### Issue description

Modular CLI does not install mojo on Ubuntu 23.10

### Steps to reproduce

When I type "modular install mojo" it throws the following error:

```
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/jonas/.modular/pkg/packages.modular.com_mojo
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
	- http error: failed to reach URL https://cas.modular.com/0/iisvduXJopAOS6hz_gfOLyrHvUjHLS3xlxQZfK1qJ78 with cURL error Timeout was reached - Looking for iisvduXJopAOS6hz_gfOLyrHvUjHLS3xlxQZfK1qJ78
	- http error: failed to reach URL https://cas.modular.com/0/Nu1dXa7TduXwZPCjWScIw6KHxvmDS8JBSnruX88Wfxk with cURL error Timeout was reached - Looking for Nu1dXa7TduXwZPCjWScIw6KHxvmDS8JBSnruX88Wfxk
	- http error: failed to reach URL https://cas.modular.com/0/q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU with cURL error Timeout was reached - Looking for q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU
```

Of course, type "modular clean"

### Version Info

```shell
- Modular 0.1.4 (6b54d308)
- Ubuntu 23.10 mantic minotaur
```

**Comment by dog-dev-mel** [comment] 2023-09-08 10:33
I use the WSL Ubuntu 22.04.2LTS show the similar output as below:
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA with cURL error Timeout was reached - Looking for zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA
        - http error: failed to reach URL https://cas.modular.com/0/q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU with cURL error Timeout was reached - Looking for q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU

**Comment by bzcheeseman** [comment] 2023-09-08 15:40
Do you happen to know what your internet connection parameters are?

**Comment by aetherclouds** [comment] 2023-09-08 23:18
same here:
```
root@PC-ERIK:/home/prj/mojo# modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /root/.modular/pkg/packages.modular.com_mojo
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU with cURL error Timeout was reached - Looking for q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU
        - http error: failed to reach URL https://cas.modular.com/0/m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8 with cURL error Timeout was reached - Looking for m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8
==========================
```
@bzcheeseman is this what you mean?
```
root@PC-ERIK:/home/prj/mojo# ip a
. . .
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:43:d8:e4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.126.208/20 brd 192.168.127.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe42:d8e4/64 scope link 
       valid_lft forever preferred_lft forever
```

- WSL 2
- Ubuntu 20.04

**Comment by bzcheeseman** [comment] 2023-09-08 23:34
I more meant like "how fast is your internet" :P Basically it's a big package and we still have work to do optimizing its size, but in the meantime, it could hit a timeout or something similar.

**Comment by aetherclouds** [comment] 2023-09-08 23:45
> I more meant like "how fast is your internet" :P Basically it's a big package and we still have work to do optimizing its size, but in the meantime, it could hit a timeout or something similar.

so how do we increase the timeout parameter?

**Comment by bzcheeseman** [comment] 2023-09-08 23:46
It's set to 10 minutes currently, there's not really a knob for that at the moment, sorry.

**Comment by meicale** [comment] 2023-09-09 00:48
> It's set to 10 minutes currently, there's not really a knob for that at the moment, sorry.

I think longer time limitation is reasonable. I fininally intalled it in the early morning just due to higher connection speed.

**Comment by dog-dev-mel** [comment] 2023-09-09 01:29
> Do you happen to know what your internet connection parameters are?
With a 1000 Mbps broadband plan and being the sole user in Austrlia.

**Comment by dog-dev-mel** [comment] 2023-09-09 01:41
> > Do you happen to know what your internet connection parameters are?
> > With a 1000 Mbps broadband plan and being the sole user in Austrlia.

I fininally intalled it now. It would be better to provide a download progress for an installation script since I am not sure what happened if i do not not check this issue details.

**Comment by jonas1ara** [comment] 2023-09-09 02:34
> > > Do you happen to know what your internet connection parameters are?
> > > With a 1000 Mbps broadband plan and being the sole user in Austrlia.
> 
> I fininally intalled it now. It would be better to provide a download progress for an installation script since I am not sure what happened if i do not not check this issue details.

Yep, a progress bar always helps

**Comment by jonas1ara** [comment] 2023-09-09 02:35
I think if the problem is the connection speed it is clear that I can close the issue

**Comment by aetherclouds** [comment] 2023-09-09 03:16
well, it is arguably an issue and it's lacking a solution

**Comment by NaAquelo** [comment] 2023-09-09 06:52
Yes, I'm still getting this issue and I've tried on 2 different networks both of which have a reasonable connection speed

**Comment by jonas1ara** [comment] 2023-09-09 06:55
> Yes, I'm still getting this issue and I've tried on 2 different networks both of which have a reasonable connection speed

I'm have the same problem

**Comment by ubaiidullaah** [comment] 2023-09-09 07:16
Hope it is solved soon, meanwhile ran in their playground. Eager to learn more.

**Comment by dog-dev-mel** [comment] 2023-09-09 07:53
You can install the dstat( sudo apt-get install dstat) and then run 'moudlar install mojo' again and check whether it is downloaded by the  "-net/total" column ((recv).
In addtion, please make sure your ubuntu ufw is inactive.

**Comment by dog-dev-mel** [comment] 2023-09-09 08:00
In addition, I ran the same commands and steps successfully this morning. I speculate that the Amazon cloud may have limited network traffic due to a high volume of people downloading the mojo simultaneously. So please try running the same commands and steps during off-peak hours in the United States to avoid network traffic limitations. 

I still believe that increasing the download time or adding a progress indicator would be a better approach, as it would help everyone understand which step the issue is occurring.

**Comment by smuniraj2018** [comment] 2023-09-15 23:28
closing because its a duplicate of [iss697](https://github.com/modularml/mojo/issues/697)

**Comment by jackos** [comment] 2024-06-06 19:47
Fixed in a prior release

**Closed by jackos** 2024-06-06 19:47 UTC
Labels: modular-cli, mojo-repo

**Comment by jonas1ara** [comment] 2024-06-07 07:18
Cool !
