### ISSUE TITLE
[Feature Request] Provide a 128 bit signed and unsigned integer

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1873] opened 2024-03-04 07:43 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Get `Int128` and `UInt128`

### What is your motivation for this change?

Using 128 bits signed or unsigned int can simplify massively some big computations. Let's says that I want to represent datetime with a nanosecond precision (the precision commonly used in computers). If i use a Int64, then I 
can represent `(2**64) / (1_000_000_000 * 60 * 60 * 24 *365) ` ~= 585 years. If I use a Int128, I can represent `(2**128) / (1_000_000_000 * 60 * 60 * 24 *365) ` ~= 1.1e+22 years which is enough to work with any date without any issue. For astrophysical computing, that would be enough since the age of the universe is 1.3e+10 years.

Another use case is UUIDs which are represented with 128 bits, and since they do a lot of bit operations, can be simplified by using a 128 bits integer, this is the case in the python's stdlib.

### Any other details?

Rust already have 128 bits ints: 
* https://doc.rust-lang.org/std/primitive.u128.html 
* https://doc.rust-lang.org/std/primitive.i128.html

**Comment by ematejska** [comment] 2024-04-30 03:27
Duplicate of https://github.com/modularml/mojo/issues/353

**Closed by ematejska** 2024-04-30 03:26 UTC
Labels: enhancement, mojo-repo
