### ISSUE TITLE
[BUG] None should  print  normally

### ISSUE THREAD

**Issue by lydiandy** [modularml/mojo#3760] opened 2024-11-10 00:53 UTC
### Bug description

here is the example:
```
fn main():
    var a = None
    var b = NoneType()
    var c: NoneType = None
    print(str(a), b, c) # str(a) can print.
    print(a, b, c) # should not report an error.

```
raises an error:
```
error: invalid call to 'print': callee with non-empty variadic pack argument expects 0 positional operands, but 3 were specified

```

### Steps to reproduce

run the example code.

### System information

```shell
latest nightly version of mojo.
```

**Comment by soraros** [comment] 2024-11-10 01:02
Duplicate of #3319.

**Comment by JoeLoser** [comment] 2024-11-10 15:38
Thanks for filing the issue! Closing as duplicate of https://github.com/modularml/mojo/issues/3319

**Closed by JoeLoser** 2024-11-10 15:38 UTC
Labels: bug, mojo-repo
