### ISSUE TITLE
[Feature Request]  Native Windows support

### ISSUE THREAD

**Issue by Ibrahim758** [modularml/mojo#1948] opened 2024-03-13 16:47 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

native support for windows.

when will it be available?

### What is your motivation for this change?

I use Windows

**Comment by soraros** [comment] 2024-03-13 17:35
Duplicate of #620.

**Comment by akirchhoff-modular** [comment] 2024-03-13 22:41
Thanks @soraros. Yes, this looks like a duplicate of #620. @Ibrahim758, please leave a reaction on #620 to indicate your interest.

**Closed by akirchhoff-modular** 2024-03-13 22:41 UTC
Labels: enhancement, mojo
