### ISSUE TITLE
[BUG] UInt32 or UInt64 conversion to Float32 or Float64 does not work correctly

### ISSUE THREAD

**Issue by AndrewPastrello** [modularml/mojo#3244] opened 2024-07-14 12:38 UTC
### Bug description

Implicitly or explicitly onverting a UInt32 or UInt64 to a Float32 or Float64 does not work correctly, seeming to saturate at 1.0, and has behavior inconsistent with Int. Using the cast method appears to work correctly.

### Steps to reproduce

```
def main():
    var y: UInt64 = 1
    for x in range(1, 4):
        print((4.0 * x) / 3.0)
        print((4.0 * Float64(x)) / 3.0)
        print((4.0 * y) / 3.0)
        print((4.0 * Float64(y)) / 3.0)
        print((4.0 * y.cast[DType.float64]()) / 3.0)
        print()
        y += 1
```

### System information

```shell
mojo 2024.7.1305 (a4455bc9)
mojo 24.4.0 (2cb57382)
```

**Comment by soraros** [comment] 2024-07-14 15:36
Duplicate of #3065.

**Closed** 2024-10-07 23:20 UTC
Labels: bug, mojo-repo
