### ISSUE TITLE
[BUG] Pretty fundamental issue with ListLiteral

### ISSUE THREAD

**Issue by carlca** [modularml/mojo#2070] opened 2024-03-29 13:52 UTC
### Bug description

* macOS 14.4.1
* Modular 0.6.0
* Mojo 24.2.0

![SCR-20240329-mhpt](https://github.com/modularml/mojo/assets/260612/cbaf93ca-58af-4164-bdbf-2a3391bfa4a5)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by arthurevans** [comment] 2024-03-29 17:49
All I see here is a screenshot. Can you add some context?

I see this message, but only when I type an open paren after the literal `var l = [1, 2, 3](` ... are you seeing it when you type the closing square bracket?

**Comment by carlca** [comment] 2024-03-29 19:34
Interestingly, since I posted that message, I've installed the nightly builds of Mojo and the VSCode extension, and the problem seems to have vanished... 🤷🏽

**Comment by ematejska** [comment] 2024-04-02 17:17
Closing this out since it's working in the nightly builds and any fix should make it's way into 24.3.  If this becomes more widely reported/reproducible we'll consider for a bug fix update.

**Closed by ematejska** 2024-04-02 17:17 UTC
Labels: bug, mojo
