### ISSUE TITLE
[BUG]: A crash happened in the mojo parser

### ISSUE THREAD

**Issue by treeshateorcs** [modularml/mojo#1781] opened 2024-02-20 01:18 UTC
### Bug description

This is the code that invokes the crash (it's the first example from [this](https://docs.modular.com/mojo/manual/lifecycle/death.html) page), i only added a main function

```
@value
struct MyPet:
    var name: String
    var age: Int

    fn __del__(owned self):
        print("Destruct", self.name)


fn pets():
    var a = MyPet("Loki", 4)
    var b = MyPet("Sylvie", 2)
    print(a.name)
    a = MyPet("Charlie", 8)
    print(b.name)


fn main():
    pets()

```

and this is the log after trying to build it with `mojo build main.🔥`

```
mojo: /__w/modular/modular/third-party/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = M::KGEN::LIT::RefType, From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo build main.\360\237\224\245
[359273:359274:20240219,201707.563214:ERROR directory_reader_posix.cc:42] opendir /home/tho/.modular/crashdb/attachments/194a5b6c-86e0-437e-9b20-cce4c7fe66c3: No such file or directory (2)
 #0 0x000059e1b11aa337 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x621337)
 #1 0x000059e1b11a7f0e (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x61ef0e)
 #2 0x000059e1b11aaa0f (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x621a0f)
 #3 0x000078320485a770 (/usr/lib/libc.so.6+0x3c770)
 #4 0x00007832048ab32c (/usr/lib/libc.so.6+0x8d32c)
 #5 0x000078320485a6c8 raise (/usr/lib/libc.so.6+0x3c6c8)
 #6 0x00007832048424b8 abort (/usr/lib/libc.so.6+0x244b8)
 #7 0x00007832048423dc (/usr/lib/libc.so.6+0x243dc)
 #8 0x0000783204852d46 (/usr/lib/libc.so.6+0x34d46)
 #9 0x000059e1b27f2d3c (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1c69d3c)
#10 0x000059e1b27f2322 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1c69322)
#11 0x000059e1b27f15cb (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1c685cb)
#12 0x000059e1b27f0078 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1c67078)
#13 0x000059e1b27efb2e (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1c66b2e)
#14 0x000059e1b27e78a3 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1c5e8a3)
#15 0x000059e1b3afed36 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2f75d36)
#16 0x000059e1b3aff3c1 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2f763c1)
#17 0x000059e1b3b01912 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2f78912)
#18 0x000059e1b277ffda (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1bf6fda)
#19 0x000059e1b16ed709 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xb64709)
#20 0x000059e1b277f562 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1bf6562)
#21 0x000059e1b2faafda (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2421fda)
#22 0x000059e1b2fb17af (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x24287af)
#23 0x000059e1b2fb1c35 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x2428c35)
#24 0x000059e1b3447b99 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x28beb99)
#25 0x000059e1b3447e09 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x28bee09)
#26 0x000059e1b3442c54 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x28b9c54)
#27 0x000059e1b2fb02a1 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x24272a1)
#28 0x000059e1b16e65e4 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0xb5d5e4)
#29 0x000059e1b115ad97 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5d1d97)
#30 0x000059e1b1159492 (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5d0492)
#31 0x0000783204843cd0 (/usr/lib/libc.so.6+0x25cd0)
#32 0x0000783204843d8a __libc_start_main (/usr/lib/libc.so.6+0x25d8a)
#33 0x000059e1b1158c9e (/home/tho/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5cfc9e)
zsh: IOT instruction (core dumped)  mojo build main.🔥
```

### System information

```shell
- What OS did you do install Mojo on ?
archlinux, neovim v0.9.5
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.7.0 (af002202)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.4.1 (2d8afe15)
```

p.s. minimal reproducible example:

```
struct MyPet:
    var name: String

    fn __del__(owned self):
        print("Destruct", self.name)
```

**Comment by sibarras** [comment] 2024-02-20 18:36
Same happens with this simplified code:
```mojo
struct Foo:
    var bar: String

    fn __del__(owned self):
        print("Destruct", self.bar)
```

Using Kali in Win 11 WSL 2. mojo 0.7.0 (af002202) modular 0.4.1 (2d8afe15)

**Comment by RtyLiu** [comment] 2024-02-25 14:02
It happens by me too. Interesting is that if I change the __del__ function to this is working:
```mojo
...
    fn __del__(owned self):
        print_no_newline("Destruct ")
        print(self.name)
...
```

**Comment by sibarras** [comment] 2024-02-26 14:10
This seems like is not a problem for regular `fn` functions.

Could be related to the special behaviour on the String descturctor on __del__ methods. If we extend the lifetime of the self.name value after the print statement, the error dissapears.
```mojo
struct MyPet:
    var name: String

    fn __del__(owned self):
        print("Destruct", self.name)
        _ = self.name

```

But if we define the lifetime before the print statement, the error comes back.
```mojo
struct MyPet:
    var name: String

    fn __del__(owned self):
        _ = self.name
        print("Destruct", self.name)
```

More intersting, if we explicitly move the value into the print function, the error dissapears.
```mojo
struct MyPet:
    var name: String

    fn __del__(owned self):
        print("Destruct", self.name^)

```

**Comment by gryznar** [comment] 2024-02-29 15:16
@sibarras is that mean, that issue can be closed and fix would be available in next release?

**Comment by sibarras** [comment] 2024-02-29 20:13
> @sibarras is that mean, that issue can be closed and fix would be available in next release?

My mistake, the error is still there

**Comment by arthurevans** [comment] 2024-02-29 21:36
@sibarras that is really interesting. It also works if you explicitly extend the lifetime of `self.value`:

```
struct Foo:
    var value: String

    fn __del__(owned self):
        print("", self.value)
        _ = self.value
```

My guess is it's something to do with Mojo misidentifying the lifetime of `self.value` when calling the variadic overload for `print()`.

**Comment by lattner** [comment] 2024-03-01 00:20
This is my bug, it is an intersection of changes, where print is now using heterogenous variadics of trait type (!):

```
fn print[
    T: Stringable, *Ts: Stringable
](first: T, *rest: *Ts, end: StringLiteral = "\n"):
```

... and destructor insertion is not doing the right thing.  I'll need to investigate this when there is more time.  Thank you for mentioning this!

**Comment by lattner** [comment] 2024-03-02 18:51
Actually, this isn't a destructor insertion problem, the issue is earlier in the parser.  We still need to implement this properly, but in the meantime, we now generate an error message:

```
t.mojo:6:23: error: internal error: cannot bind memory-only type 'String' to variadic pack
        print("", self.value)
                      ^
```

I'm going to leave this open until we support this correctly.

**Comment by ematejska** [comment] 2024-04-03 18:02
Dup of https://github.com/modularml/mojo/issues/1386?

**Comment by lattner** [comment] 2024-04-04 16:53
This is fixed in the next release, thank you!  Poor sylvie:
```
Loki
Destruct Loki
Destruct Charlie
Sylvie
Destruct Sylvie
```

**Closed by lattner** 2024-04-04 16:53 UTC
Labels: bug, mojo-lang, mojo, crash
