### ISSUE TITLE
[BUG]: Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler

### ISSUE THREAD

**Issue by wangwendong1024** [modularml/mojo#1132] opened 2023-10-21 14:27 UTC
### Bug description

C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu20.04LTS_2004.6.16.0_x64__79rhkp1fndgsc>ubuntu2004.exe
适用于 Linux 的 Windows 子系统现已在 Microsoft Store 中可用!
你可以通过运行“wsl.exe --update”或通过访问 https://aka.ms/wslstorepage 进行升级
从 Microsoft Store 安装 WSL 将可以更快地获取最新的 WSL 更新。
有关详细信息，请访问 https://aka.ms/wslstoreinfo

pi@DESKTOP-D4L6E9F:~$ sudo apt update
[sudo] password for pi:
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:4 https://dl.modular.com/public/installer/deb/ubuntu focal InRelease [5076 B]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2917 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2419 kB]
Fetched 5639 kB in 40s (141 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
78 packages can be upgraded. Run 'apt list --upgradable' to see them.
pi@DESKTOP-D4L6E9F:~$ modular clean
[372:372:20231021,200612.817484:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[370:370:20231021,200612.818869:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
pi@DESKTOP-D4L6E9F:~$ curl https://get.modular.com | sh - && modular auth 'my auth token'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3885  100  3885    0     0    823      0  0:00:04  0:00:04 --:--:--   930
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=20.04  codename=focal  arch=x86_64
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'modular/installer' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'modular/installer' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 78 not upgraded.
Need to get 48.1 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://dl.modular.com/public/installer/deb/ubuntu focal/main amd64 modular amd64 0.2.1 [48.1 MB]
Fetched 48.1 MB in 37s (1309 kB/s)
(Reading database ... 39279 files and directories currently installed.)
Preparing to unpack .../modular_0.2.1_amd64.deb ...
Unpacking modular (0.2.1) over (0.2.1) ...
Setting up modular (0.2.1) ...
Processing triggers for man-db (2.9.1-1) ...
sh: 80: [[: not found
  __  __           _       _
 |  \/  | ___   __| |_   _| | __ _ _ __
 | |\/| |/ _ \ / _` | | | | |/ _` | '__|
 | |  | | (_) | (_| | |_| | | (_| | |
 |_|  |_|\___/ \__,_|\__,_|_|\__,_|_|

Welcome to the Modular CLI!
For info about this tool, type "modular --help".

To install Mojo🔥, type "modular install mojo".

For Mojo documentation, see https://docs.modular.com/mojo.
To chat on Discord, visit https://discord.gg/modular.
To report issues, go to https://github.com/modularml/mojo/issues.
[972:972:20231021,200735.705152:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[970:970:20231021,200735.706357:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.
C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu20.04LTS_2004.6.16.0_x64__79rhkp1fndgsc>ubuntu2004.exe
适用于 Linux 的 Windows 子系统现已在 Microsoft Store 中可用!
你可以通过运行“wsl.exe --update”或通过访问 https://aka.ms/wslstorepage 进行升级
从 Microsoft Store 安装 WSL 将可以更快地获取最新的 WSL 更新。
有关详细信息，请访问 https://aka.ms/wslstoreinfo

pi@DESKTOP-D4L6E9F:~$ sudo apt update
[sudo] password for pi:
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:4 https://dl.modular.com/public/installer/deb/ubuntu focal InRelease [5076 B]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2917 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2419 kB]
Fetched 5639 kB in 40s (141 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
78 packages can be upgraded. Run 'apt list --upgradable' to see them.
pi@DESKTOP-D4L6E9F:~$ modular clean
[372:372:20231021,200612.817484:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[370:370:20231021,200612.818869:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
pi@DESKTOP-D4L6E9F:~$ curl https://get.modular.com | sh - && modular auth 'my auth token'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3885  100  3885    0     0    823      0  0:00:04  0:00:04 --:--:--   930
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=20.04  codename=focal  arch=x86_64
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'modular/installer' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'modular/installer' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 78 not upgraded.
Need to get 48.1 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://dl.modular.com/public/installer/deb/ubuntu focal/main amd64 modular amd64 0.2.1 [48.1 MB]
Fetched 48.1 MB in 37s (1309 kB/s)
(Reading database ... 39279 files and directories currently installed.)
Preparing to unpack .../modular_0.2.1_amd64.deb ...
Unpacking modular (0.2.1) over (0.2.1) ...
Setting up modular (0.2.1) ...
Processing triggers for man-db (2.9.1-1) ...
sh: 80: [[: not found
  __  __           _       _
 |  \/  | ___   __| |_   _| | __ _ _ __
 | |\/| |/ _ \ / _` | | | | |/ _` | '__|
 | |  | | (_) | (_| | |_| | | (_| | |
 |_|  |_|\___/ \__,_|\__,_|_|\__,_|_|

Welcome to the Modular CLI!
For info about this tool, type "modular --help".

To install Mojo🔥, type "modular install mojo".

For Mojo documentation, see https://docs.modular.com/mojo.
To chat on Discord, visit https://discord.gg/modular.
To report issues, go to https://github.com/modularml/mojo/issues.
[972:972:20231021,200735.705152:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[970:970:20231021,200735.706357:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
pi@DESKTOP-D4L6E9F:~$ modular install mojo
[977:977:20231021,200756.555206:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[975:975:20231021,200756.556772:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/pi/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/xnvEJlCJKtoZB5TOFuL77x5fgzT8p5Ol68H4uazm6O4 with cURL error Timeout was reached - Looking for xnvEJlCJKtoZB5TOFuL77x5fgzT8p5Ol68H4uazm6O4
        - http error: failed to reach URL https://cas.modular.com/0/JIUSVJZEIqnkhI2ChMnS7i0mfrBQ3kyNkW8dJSUPV3s with cURL error Timeout was reached - Looking for JIUSVJZEIqnkhI2ChMnS7i0mfrBQ3kyNkW8dJSUPV3s
        - http error: failed to reach URL https://cas.modular.com/0/xzmkI9Xc04mvbPwhSbmBMwJ1haMC6V8GizBC7T9HBKo with cURL error Timeout was reached - Looking for xzmkI9Xc04mvbPwhSbmBMwJ1haMC6V8GizBC7T9HBKo
        - http error: failed to reach URL https://cas.modular.com/0/XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw with cURL error Timeout was reached - Looking for XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw
        - http error: failed to reach URL https://cas.modular.com/0/aj835pvd19Ph_U2Zg88ENHUOFcUnCM-TsC5arlV3Azw with cURL error Timeout was reached - Looking for aj835pvd19Ph_U2Zg88ENHUOFcUnCM-TsC5arlV3Azw
        - http error: failed to reach URL https://cas.modular.com/0/nuDwXhUin3vvcPssVPO8qL4XjHqEU8CnbnCCP5pGdz8 with cURL error Timeout was reached - Looking for nuDwXhUin3vvcPssVPO8qL4XjHqEU8CnbnCCP5pGdz8
==========================

pi@DESKTOP-D4L6E9F:~$ modular clean
[1217:1217:20231021,222145.555456:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[1215:1215:20231021,222145.556850:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
pi@DESKTOP-D4L6E9F:~$

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`

C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu20.04LTS_2004.6.16.0_x64__79rhkp1fndgsc>ubuntu2004.exe
适用于 Linux 的 Windows 子系统现已在 Microsoft Store 中可用!
你可以通过运行“wsl.exe --update”或通过访问 https://aka.ms/wslstorepage 进行升级
从 Microsoft Store 安装 WSL 将可以更快地获取最新的 WSL 更新。
有关详细信息，请访问 https://aka.ms/wslstoreinfo
pi@DESKTOP-D4L6E9F:~$ curl https://get.modular.com | sh - && modular auth 'my auth token'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3885  100  3885    0     0    823      0  0:00:04  0:00:04 --:--:--   930
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=20.04  codename=focal  arch=x86_64
 >>>>:
```

**Comment by yihualou** [comment] 2023-11-09 09:59
Duplicate of #984

**Closed by yihualou** 2023-11-09 09:59 UTC
Labels: bug, modular-cli
